MelloMario.Objects.BaseUIObject Class Reference
Public Member Functions
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Member Functions
 BaseUIObject (IPlayer player)
void Offset (ref Rectangle rect)
void UpdateOrigin ()
abstract void OnUpdate (int time)
abstract void OnDraw (int time, SpriteBatch spriteBatch)
Protected Attributes
 IPlayer Player
Point RelativeOrigin
Detailed Description
Definition at line 10 of file BaseUIObject.cs.
Constructor & Destructor Documentation
BaseUIObject()
MelloMario.Objects.BaseUIObject.BaseUIObject (IPlayer player) [protected]
Definition at line 15 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
        {
            // TODO: use another spritebatch
            Player = player;
            RelativeOrigin = player.Camera.Viewport.Location;
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseUIObject.Draw (int time, SpriteBatch spriteBatch)
Implements MelloMario.IObject .
Definition at line 27 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnDraw().
        {
            OnDraw(time, spriteBatch);
        }
Offset()
void MelloMario.Objects.BaseUIObject.Offset (ref Rectangle rect) [protected]
Definition at line 32 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            rect.Offset(Player.Camera.Viewport.Location - RelativeOrigin);
        }
OnDraw()
abstract void MelloMario.Objects.BaseUIObject.OnDraw (int time, SpriteBatch spriteBatch) [protected], [pure virtual]
Implemented in MelloMario.Objects.UserInterfaces.GameOver , MelloMario.Objects.UserInterfaces.HUD , MelloMario.Objects.UserInterfaces.GameWon , and MelloMario.Objects.UserInterfaces.GameStart .
Referenced by MelloMario.Objects.BaseUIObject.Draw(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
OnUpdate()
abstract void MelloMario.Objects.BaseUIObject.OnUpdate (int time) [protected], [pure virtual]
Implemented in MelloMario.Objects.UserInterfaces.GameOver , MelloMario.Objects.UserInterfaces.GameWon , MelloMario.Objects.UserInterfaces.HUD , and MelloMario.Objects.UserInterfaces.GameStart .
Referenced by MelloMario.Objects.BaseUIObject.Update(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
Update()
void MelloMario.Objects.BaseUIObject.Update (int time)
Implements MelloMario.IObject .
Definition at line 22 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnUpdate().
        {
            OnUpdate(time);
        }
UpdateOrigin()
void MelloMario.Objects.BaseUIObject.UpdateOrigin () [protected]
Definition at line 37 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, MelloMario.Objects.BaseUIObject.OnDraw(), MelloMario.Objects.BaseUIObject.OnUpdate(), and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            RelativeOrigin = Player.Camera.Viewport.Location;
        }
Member Data Documentation
Player
 IPlayer MelloMario.Objects.BaseUIObject.Player [protected]
Definition at line 12 of file BaseUIObject.cs.
RelativeOrigin
Point MelloMario.Objects.BaseUIObject.RelativeOrigin [protected]
Definition at line 13 of file BaseUIObject.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/BaseClasses/Objects/ BaseUIObject.cs