MelloMario.Objects.Miscs.Background Class Reference
Public Member Functions
 Background (IWorld world, Point location, string type, ZIndex zIndex)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
override void OnUpdate (int time)
override void OnSimulation (int time)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 IWorld World
Properties
Rectangle Boundary [get]
Private Member Functions
void UpdateSprite ()
Private Attributes
readonly ZIndex targetZIndex
readonly string type
Detailed Description
Definition at line 13 of file Background.cs.
Member Enumeration Documentation
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected], [inherited]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected], [inherited]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
Background()
MelloMario.Objects.Miscs.Background.Background (IWorld world, Point location, string type, ZIndex zIndex)
Definition at line 18 of file Background.cs.
References MelloMario.Objects.Miscs.Background.type, and MelloMario.Objects.Miscs.Background.UpdateSprite().
                                                                                    : base(
            world,
            location,
            new Point(32, 32))
        {
            this.type = type;
            targetZIndex = zIndex;
            UpdateSprite();
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected], [inherited]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
OnDraw()
override void MelloMario.Objects.Miscs.Background.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 41 of file Background.cs.
        {
        }
OnSimulation()
override void MelloMario.Objects.Miscs.Background.OnSimulation (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 37 of file Background.cs.
        {
        }
OnUpdate()
override void MelloMario.Objects.Miscs.Background.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 33 of file Background.cs.
        {
        }
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected], [inherited]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected], [inherited]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected], [inherited]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
UpdateSprite()
void MelloMario.Objects.Miscs.Background.UpdateSprite () [private]
Definition at line 28 of file Background.cs.
References MelloMario.ISpriteFactory< T >.CreateSceneSprite(), MelloMario.Factories.SpriteFactory.Instance, and MelloMario.Objects.BaseGameObject.ShowSprite().
Referenced by MelloMario.Objects.Miscs.Background.Background().
        {
            ShowSprite(SpriteFactory.Instance.CreateSceneSprite(type,
      targetZIndex));
        }
Member Data Documentation
targetZIndex
readonly ZIndex MelloMario.Objects.Miscs.Background.targetZIndex [private]
Definition at line 15 of file Background.cs.
type
readonly string MelloMario.Objects.Miscs.Background.type [private]
Definition at line 16 of file Background.cs.
Referenced by MelloMario.Objects.Miscs.Background.Background().
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected], [inherited]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get], [inherited]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Miscs/ Background.cs