MelloMario.Objects.Characters.MovementStates.Jumping Class Reference
Public Member Functions
 Jumping (Mario owner)
void Crouch ()
void Idle ()
void Land ()
void Jump ()
void Walk ()
override void Update (int time)
void Update (int time)
Protected Member Functions
override void OnTimer (int time)
Properties
bool Finished [get, set]
float Progress [get]
Private Attributes
 IMarioMovementState previous
Detailed Description
Definition at line 10 of file Jumping.cs.
Constructor & Destructor Documentation
Jumping()
MelloMario.Objects.Characters.MovementStates.Jumping.Jumping (Mario owner)
Definition at line 14 of file Jumping.cs.
References MelloMario.Objects.Characters.MovementStates.Jumping.Finished, and MelloMario.Objects.Characters.Mario.MovementState.
                                    : base(owner, 200)
        {
            previous = owner.MovementState;
            Finished = false;
        }
Member Function Documentation
Crouch()
void MelloMario.Objects.Characters.MovementStates.Jumping.Crouch ()
Implements MelloMario.IMarioMovementState .
Definition at line 22 of file Jumping.cs.
        {
            Owner.MovementState = new Crouching(Owner);
        }
Idle()
void MelloMario.Objects.Characters.MovementStates.Jumping.Idle ()
Implements MelloMario.IMarioMovementState .
Definition at line 27 of file Jumping.cs.
        {
            previous = new Standing(Owner);
        }
Jump()
void MelloMario.Objects.Characters.MovementStates.Jumping.Jump ()
Implements MelloMario.IMarioMovementState .
Definition at line 37 of file Jumping.cs.
        {
        }
Land()
void MelloMario.Objects.Characters.MovementStates.Jumping.Land ()
Implements MelloMario.IMarioMovementState .
Definition at line 32 of file Jumping.cs.
References MelloMario.Objects.Characters.MovementStates.Jumping.previous.
        {
            Owner.MovementState = previous;
        }
OnTimer()
override void MelloMario.Objects.Characters.MovementStates.Jumping.OnTimer (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseTimedState< Mario > .
Definition at line 46 of file Jumping.cs.
References MelloMario.Objects.Characters.MovementStates.Jumping.Finished.
        {
            Finished = true;
        }
Update() [1/2]
void MelloMario.IState.Update (int time) [inherited]
Implemented in MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Characters.PowerUpStates.Standard , MelloMario.Objects.Characters.MovementStates.Standing , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , MelloMario.Objects.Characters.PowerUpStates.Fire , MelloMario.Objects.Characters.PowerUpStates.Super , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Enemies.KoopaStates.Defeated , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Normal , MelloMario.Objects.Blocks.QuestionStates.Used , MelloMario.Objects.Enemies.KoopaStates.MovingShell , MelloMario.Objects.BaseTimedState< T > , MelloMario.Objects.Enemies.KoopaStates.Normal , MelloMario.Objects.Items.CoinStates.Unveil , MelloMario.Objects.Items.FireFlowerStates.Unveil , MelloMario.Objects.Items.OneUpMushroomStates.Unveil , MelloMario.Objects.Items.StarStates.Unveil , MelloMario.Objects.Items.SuperMushroomStates.Unveil , MelloMario.Objects.Enemies.GoombaStates.Defeated , MelloMario.Objects.Characters.ProtectionStates.Normal , MelloMario.Objects.Enemies.GoombaStates.Normal , MelloMario.Objects.Enemies.ThwompStates.Defeated , MelloMario.Objects.Enemies.ThwompStates.Normal , MelloMario.Objects.Items.CoinStates.Normal , MelloMario.Objects.Items.FireFlowerStates.Normal , MelloMario.Objects.Items.OneUpMushroomStates.Normal , MelloMario.Objects.Items.StarStates.Normal , MelloMario.Objects.Items.SuperMushroomStates.Normal , MelloMario.Objects.Enemies.PiranhaStates.Defeated , MelloMario.Objects.Enemies.PiranhaStates.MovingDown , MelloMario.Objects.Enemies.PiranhaStates.MovingUp , and MelloMario.Objects.BaseState< T > .
Referenced by MelloMario.Objects.Enemies.Thwomp.OnUpdate(), MelloMario.Objects.Enemies.Goomba.OnUpdate(), MelloMario.Objects.Items.OneUpMushroom.OnUpdate(), MelloMario.Objects.Enemies.Piranha.OnUpdate(), MelloMario.Objects.Items.Star.OnUpdate(), MelloMario.Objects.Items.FireFlower.OnUpdate(), MelloMario.Objects.Enemies.Koopa.OnUpdate(), MelloMario.Objects.Blocks.Question.OnUpdate(), MelloMario.Objects.Items.Coin.OnUpdate(), MelloMario.Objects.Items.SuperMushroom.OnUpdate(), MelloMario.Objects.Blocks.Brick.OnUpdate(), and MelloMario.Objects.Characters.Mario.OnUpdate().
Update() [2/2]
override void MelloMario.Objects.BaseTimedState< T >.Update (int time) [inherited]
Definition at line 30 of file BaseTimedState.cs.
        {
            // Note: if we will support recording/replaying, use a constant number here
            elapsed += time;
            if (elapsed >= interval)
            {
                OnTimer(time);
                elapsed -= interval;
            }
        }
Walk()
void MelloMario.Objects.Characters.MovementStates.Jumping.Walk ()
Implements MelloMario.IMarioMovementState .
Definition at line 41 of file Jumping.cs.
        {
            previous = new Walking(Owner);
        }
Member Data Documentation
previous
 IMarioMovementState MelloMario.Objects.Characters.MovementStates.Jumping.previous [private]
Definition at line 12 of file Jumping.cs.
Referenced by MelloMario.Objects.Characters.MovementStates.Jumping.Land().
Property Documentation
Finished
bool MelloMario.Objects.Characters.MovementStates.Jumping.Finished [get], [set]
Definition at line 20 of file Jumping.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Jump(), MelloMario.Objects.Characters.MovementStates.Jumping.Jumping(), and MelloMario.Objects.Characters.MovementStates.Jumping.OnTimer().
Progress
float MelloMario.Objects.BaseTimedState< T >.Progress [get], [protected], [inherited]
Definition at line 21 of file BaseTimedState.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Characters/MovementStates/ Jumping.cs