MelloMario.Controls.Scripts.PausedScript Class Reference
Public Member Functions
void Bind (IEnumerable< IController > controllers, IModel model, ICharacter character)
Detailed Description
Definition at line 11 of file PausedScript.cs.
Member Function Documentation
Bind()
void MelloMario.Controls.Scripts.PausedScript.Bind (IEnumerable< IController > controllers, IModel model, ICharacter character)
Implements MelloMario.IScript .
Definition at line 13 of file PausedScript.cs.
References MelloMario.IController.AddCommand(), MelloMario.Factories.CommandFactory.Instance, and MelloMario.IController.Reset().
Referenced by MelloMario.Theming.GameModel.Pause().
        {
            ICommandFactory factory = CommandFactory.Instance;
            foreach (IController controller in controllers)
            {
                controller.Reset();
                controller.AddCommand(
                    Keys.F12,
                    factory.CreateModelCommand("ToggleFullScreen", model),
                    KeyBehavior.press);
                controller.AddCommand(Keys.P, factory.CreateModelCommand("Resume", model),
      KeyBehavior.press);
                controller.AddCommand(Keys.R, factory.CreateModelCommand("Reset", model),
      KeyBehavior.press);
                controller.AddCommand(Keys.Q, factory.CreateModelCommand("Quit", model),
      KeyBehavior.press);
            }
        }
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Controls/Scripts/ PausedScript.cs