MelloMario.Graphics.Sprites.BaseTextureSprite Class Reference
Public Member Functions
void Draw (int time, SpriteBatch spriteBatch, Rectangle destination)
Protected Member Functions
 BaseTextureSprite (Texture2D texture, Rectangle source, ZIndex zIndex)
abstract void OnAnimate (int time)
void ChangeSource (Point location)
void ChangeColor (Color newColor)
override void OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination)
void Toggle ()
Properties
float LayerDepth [get]
Point PixelSize [get]
Private Attributes
readonly Texture2D texture
Color color
Rectangle source
Detailed Description
Definition at line 12 of file BaseTextureSprite.cs.
Constructor & Destructor Documentation
BaseTextureSprite()
MelloMario.Graphics.Sprites.BaseTextureSprite.BaseTextureSprite (Texture2D texture, Rectangle source, ZIndex zIndex) [protected]
Definition at line 18 of file BaseTextureSprite.cs.
References MelloMario.Graphics.Sprites.BaseTextureSprite.OnAnimate(), MelloMario.Graphics.Sprites.BaseTextureSprite.source, and MelloMario.Graphics.Sprites.BaseTextureSprite.texture.
                                                                                        : base(
      source.Size, zIndex)
        {
            this.texture = texture;
            this.source = source;
            color = Color.White;
        }
Member Function Documentation
ChangeColor()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeColor (Color newColor) [protected]
Definition at line 32 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.FlickingAnimatedSprite.OnFrame().
        {
            color = newColor;
        }
ChangeSource()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeSource (Point location) [protected]
Definition at line 27 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
        {
            source.Location = location;
        }
Draw()
void MelloMario.Graphics.Sprites.BaseSprite.Draw (int time, SpriteBatch spriteBatch, Rectangle destination) [inherited]
Implements MelloMario.ISprite .
Definition at line 56 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.OnDraw().
        {
            if (visible)
            {
                OnDraw(time, spriteBatch, destination);
            }
        }
OnAnimate()
abstract void MelloMario.Graphics.Sprites.BaseTextureSprite.OnAnimate (int time) [protected], [pure virtual]
Implemented in MelloMario.Graphics.Sprites.AnimatedSprite , and MelloMario.Graphics.Sprites.StaticSprite .
Referenced by MelloMario.Graphics.Sprites.BaseTextureSprite.BaseTextureSprite(), and MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw().
OnDraw()
override void MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination) [protected], [virtual]
Implements MelloMario.Graphics.Sprites.BaseSprite .
Definition at line 37 of file BaseTextureSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.LayerDepth, and MelloMario.Graphics.Sprites.BaseTextureSprite.OnAnimate().
        {
            OnAnimate(time);
            spriteBatch.Draw(
                texture,
                destination,
                source,
                color,
                0f, //rotation
                new Vector2(), //origin
                SpriteEffects.None,
                LayerDepth);
        }
Toggle()
void MelloMario.Graphics.Sprites.BaseSprite.Toggle () [protected], [inherited]
Definition at line 66 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.visible.
Referenced by MelloMario.Graphics.Sprites.FlashingAnimatedSprite.OnFrame().
        {
            visible = !visible;
        }
Member Data Documentation
color
Color MelloMario.Graphics.Sprites.BaseTextureSprite.color [private]
Definition at line 15 of file BaseTextureSprite.cs.
source
Rectangle MelloMario.Graphics.Sprites.BaseTextureSprite.source [private]
Definition at line 16 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseTextureSprite.BaseTextureSprite().
texture
readonly Texture2D MelloMario.Graphics.Sprites.BaseTextureSprite.texture [private]
Definition at line 14 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseTextureSprite.BaseTextureSprite().
Property Documentation
LayerDepth
float MelloMario.Graphics.Sprites.BaseSprite.LayerDepth [get], [protected], [inherited]
Definition at line 25 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite(), MelloMario.Graphics.Sprites.SplashSprite.OnDraw(), MelloMario.Graphics.Sprites.BrickPieceSprite.OnDraw(), MelloMario.Graphics.Sprites.TextSprite.OnDraw(), and MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw().
PixelSize
Point MelloMario.Graphics.Sprites.BaseSprite.PixelSize [get], [inherited]
Definition at line 54 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/BaseClasses/Graphics/ BaseTextureSprite.cs