MelloMario.Objects.BaseCollidableObject Class Reference
Public Member Functions
delegate void LivesHandler (BaseCollidableObject m, ScoreEventArgs e)
delegate void PointHandler (BaseCollidableObject m, ScoreEventArgs e)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum CollisionMode {
 CollisionMode.Left,
 CollisionMode.Right,
 CollisionMode.Top,
 CollisionMode.Bottom,
 CollisionMode.InnerLeft,
 CollisionMode.InnerRight,
 CollisionMode.InnerTop,
 CollisionMode.InnerBottom
 }
enum CornerMode {
 CornerMode.Left,
 CornerMode.Right,
 CornerMode.Top,
 CornerMode.Bottom,
 CornerMode.Center
 }
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
 BaseCollidableObject (IWorld world, Point location, IListener< IGameObject > listener, Point size)
abstract void OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive)
abstract void OnCollideWorld (CollisionMode mode, CollisionMode modePassive)
void Move (Point delta)
void StopHorizontalMovement ()
void StopVerticalMovement ()
void RemoveSelf ()
override void OnSimulation (int time)
void ScorePoints (int points)
void ChangeLives ()
abstract void OnUpdate (int time)
abstract void OnDraw (int time, SpriteBatch spriteBatch)
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 IWorld World
Properties
Rectangle Boundary [get]
Events
 PointHandler HandlerPoints
 LivesHandler HandlerLives
Private Member Functions
IEnumerable< Tuple< CollisionMode, CollisionMode, CornerMode, CornerMode > > ScanCollideModes (Rectangle targetBoundary)
void CollideAll ()
Private Attributes
Point movement
Detailed Description
Definition at line 13 of file BaseCollidableObject.cs.
Member Enumeration Documentation
CollisionMode
enum MelloMario.Objects.BaseCollidableObject.CollisionMode [strong], [protected]
Enumerator
Left
Right
Top
Bottom
InnerLeft
InnerRight
InnerTop
InnerBottom
Definition at line 266 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            InnerLeft,
            InnerRight,
            InnerTop,
            InnerBottom
        }
CornerMode
enum MelloMario.Objects.BaseCollidableObject.CornerMode [strong], [protected]
Enumerator
Left
Right
Top
Bottom
Center
Definition at line 278 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            Center
        }
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected], [inherited]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected], [inherited]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
BaseCollidableObject()
MelloMario.Objects.BaseCollidableObject.BaseCollidableObject (IWorld world, Point location, IListener< IGameObject > listener, Point size) [protected]
Definition at line 21 of file BaseCollidableObject.cs.
References MelloMario.IListener< in in T >.Subscribe().
                        : base(world, location, size)
        {
            listener?.Subscribe(this);
            movement = new Point();
        }
Member Function Documentation
ChangeLives()
void MelloMario.Objects.BaseCollidableObject.ChangeLives () [protected]
Definition at line 256 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.OneUpMushroom.Collect(), and MelloMario.Objects.Blocks.Flag.OnCollision().
        {
            HandlerLives?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = 1
                });
        }
CollideAll()
void MelloMario.Objects.BaseCollidableObject.CollideAll () [private]
Definition at line 135 of file BaseCollidableObject.cs.
References MelloMario.IGameObject.Boundary, MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Containers.World.Boundary, MelloMario.Objects.BaseCollidableObject.OnCollideWorld(), MelloMario.Objects.BaseCollidableObject.OnCollision(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Containers.World.ScanNearby().
Referenced by MelloMario.Objects.BaseCollidableObject.OnSimulation().
        {
            foreach (IGameObject target in World.ScanNearby(Boundary))
            {
                if (target != this && target is BaseCollidableObject obj)
                {
                    foreach (Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode> pair in
      ScanCollideModes(
                        target.Boundary))
                    {
                        OnCollision(target, pair.Item1, pair.Item2, pair.Item3, pair.Item4);
                        obj.OnCollision(this, pair.Item2, pair.Item1, pair.Item4, pair.Item3);
                    }
                }
            }
            foreach (Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode> pair in
      ScanCollideModes(
                World.Boundary))
            {
                OnCollideWorld(pair.Item1, pair.Item2);
            }
        }
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected], [inherited]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
LivesHandler()
delegate void MelloMario.Objects.BaseCollidableObject.LivesHandler (BaseCollidableObject m, ScoreEventArgs e)
Move()
void MelloMario.Objects.BaseCollidableObject.Move (Point delta) [protected]
Definition at line 166 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Move().
Referenced by MelloMario.Objects.Blocks.Question.BumpMove(), MelloMario.Objects.Blocks.Brick.BumpMove(), MelloMario.Objects.BasePhysicalObject.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Items.FireFlower.UnveilMove(), MelloMario.Objects.Items.Coin.UnveilMove(), MelloMario.Objects.Items.OneUpMushroom.UnveilMove(), MelloMario.Objects.Items.Star.UnveilMove(), and MelloMario.Objects.Items.SuperMushroom.UnveilMove().
        {
            movement += delta;
            World.Move(this);
        }
OnCollideWorld()
abstract void MelloMario.Objects.BaseCollidableObject.OnCollideWorld (CollisionMode mode, CollisionMode modePassive) [protected], [pure virtual]
Implemented in MelloMario.Objects.Characters.Mario , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Items.Star , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Items.FireBall , MelloMario.Objects.Blocks.Floor , and MelloMario.Objects.Blocks.Stair .
Referenced by MelloMario.Objects.BaseCollidableObject.CollideAll().
OnCollision()
abstract void MelloMario.Objects.BaseCollidableObject.OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive) [protected], [pure virtual]
Implemented in MelloMario.Objects.Characters.Mario , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Items.Star , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Items.FireBall , MelloMario.Objects.Blocks.Floor , and MelloMario.Objects.Blocks.Stair .
Referenced by MelloMario.Objects.BaseCollidableObject.CollideAll().
OnDraw()
abstract void MelloMario.Objects.BaseGameObject.OnDraw (int time, SpriteBatch spriteBatch) [protected], [pure virtual], [inherited]
Implemented in MelloMario.Objects.Characters.Mario , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Items.Star , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Blocks.Floor , MelloMario.Objects.Blocks.Stair , MelloMario.Objects.Miscs.Background , MelloMario.Objects.UserInterfaces.PopingUpPoints , and MelloMario.Objects.Items.FireBall .
Referenced by MelloMario.Objects.BaseGameObject.Draw().
OnSimulation()
override void MelloMario.Objects.BaseCollidableObject.OnSimulation (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Reimplemented in MelloMario.Objects.Characters.MarioCharacter , MelloMario.Objects.Characters.Mario , MelloMario.Objects.BasePhysicalObject , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.Star , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Enemies.Piranha , and MelloMario.Objects.Items.FireBall .
Definition at line 191 of file BaseCollidableObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.BaseGameObject.location, and MelloMario.Objects.BaseGameObject.Relocate().
        {
            float offset = 0;
            while (true)
            {
                if (movement.X == 0 && movement.Y == 0)
                {
                    break;
                }
                CollideAll();
                if (movement.X == 0 && movement.Y == 0)
                {
                    break;
                }
                float sqrX = movement.X * movement.X;
                float sqrY = movement.Y * movement.Y;
                float offsetX = (float) Math.Sqrt(sqrY / (sqrX + sqrY));
                float offsetY = (float) Math.Sqrt(sqrX / (sqrX + sqrY));
                Point location = Boundary.Location;
                if (Math.Abs(offset + offsetX) < Math.Abs(offset - offsetY))
                {
                    if (movement.X < 0)
                    {
                        location.X -= 1;
                        movement.X += 1;
                    }
                    else
                    {
                        location.X += 1;
                        movement.X -= 1;
                    }
                }
                else
                {
                    if (movement.Y < 0)
                    {
                        location.Y -= 1;
                        movement.Y += 1;
                    }
                    else
                    {
                        location.Y += 1;
                        movement.Y -= 1;
                    }
                }
                Relocate(location);
            }
        }
OnUpdate()
abstract void MelloMario.Objects.BaseGameObject.OnUpdate (int time) [protected], [pure virtual], [inherited]
Implemented in MelloMario.Objects.Characters.MarioCharacter , MelloMario.Objects.Characters.Mario , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Items.Star , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Blocks.Floor , MelloMario.Objects.Blocks.Stair , MelloMario.Objects.Miscs.Background , MelloMario.Objects.Items.FireBall , and MelloMario.Objects.UserInterfaces.PopingUpPoints .
Referenced by MelloMario.Objects.BaseGameObject.Draw(), and MelloMario.Objects.BaseGameObject.Update().
PointHandler()
delegate void MelloMario.Objects.BaseCollidableObject.PointHandler (BaseCollidableObject m, ScoreEventArgs e)
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected], [inherited]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
RemoveSelf()
void MelloMario.Objects.BaseCollidableObject.RemoveSelf () [protected]
Definition at line 183 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Remove(), MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Items.Coin.Coin(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.OneUpMushroom.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Objects.Blocks.Brick.Remove(), MelloMario.Objects.Characters.MarioCharacter.Remove(), MelloMario.Objects.Items.Star.Star(), and MelloMario.Objects.Items.SuperMushroom.SuperMushroom().
        {
            StopHorizontalMovement();
            StopVerticalMovement();
            World.Remove(this);
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected], [inherited]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
ScanCollideModes()
IEnumerable<Tuple< CollisionMode, CollisionMode, CornerMode, CornerMode> > MelloMario.Objects.BaseCollidableObject.ScanCollideModes (Rectangle targetBoundary) [private]
Definition at line 34 of file BaseCollidableObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary.
Referenced by MelloMario.Objects.BaseCollidableObject.CollideAll().
        {
            Rectangle rectA = Boundary;
            Rectangle rectB = targetBoundary;
            if (rectA.Top < rectB.Bottom && rectB.Top < rectA.Bottom)
            {
                CornerMode cornerY = rectA.Center.Y <= rectB.Top
                    ? CornerMode.Top
                    : rectA.Center.Y >= rectB.Bottom
                        ? CornerMode.Bottom
                        : CornerMode.Center;
                CornerMode cornerYPassive = rectB.Center.Y <= rectA.Top
                    ? CornerMode.Top
                    : rectB.Center.Y >= rectA.Bottom
                        ? CornerMode.Bottom
                        : CornerMode.Center;
                if (rectA.Left == rectB.Right)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.Left,
                        CollisionMode.Right,
                        cornerY,
                        cornerYPassive);
                }
                if (rectA.Right == rectB.Left)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.Right,
                        CollisionMode.Left,
                        cornerY,
                        cornerYPassive);
                }
                if (rectA.Left == rectB.Left)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.InnerLeft,
                        CollisionMode.InnerLeft,
                        cornerY,
                        cornerYPassive);
                }
                if (rectA.Right == rectB.Right)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.InnerRight,
                        CollisionMode.InnerRight,
                        cornerY,
                        cornerYPassive);
                }
            }
            if (rectA.Left < rectB.Right && rectB.Left < rectA.Right)
            {
                CornerMode cornerX = rectA.Center.X <= rectB.Left
                    ? CornerMode.Left
                    : rectA.Center.X >= rectB.Right
                        ? CornerMode.Right
                        : CornerMode.Center;
                CornerMode cornerXPassive = rectB.Center.X <= rectA.Left
                    ? CornerMode.Left
                    : rectB.Center.X >= rectA.Right
                        ? CornerMode.Right
                        : CornerMode.Center;
                if (rectA.Top == rectB.Bottom)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.Top,
                        CollisionMode.Bottom,
                        cornerX,
                        cornerXPassive);
                }
                if (rectA.Bottom == rectB.Top)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.Bottom,
                        CollisionMode.Top,
                        cornerX,
                        cornerXPassive);
                }
                if (rectA.Top == rectB.Top)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.InnerTop,
                        CollisionMode.InnerTop,
                        cornerX,
                        cornerXPassive);
                }
                if (rectA.Bottom == rectB.Bottom)
                {
                    yield return new Tuple<CollisionMode, CollisionMode, CornerMode, CornerMode>(
                        CollisionMode.InnerBottom,
                        CollisionMode.InnerBottom,
                        cornerX,
                        cornerXPassive);
                }
            }
        }
ScorePoints()
void MelloMario.Objects.BaseCollidableObject.ScorePoints (int points) [protected]
Definition at line 246 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Blocks.Flag.OnCollision(), and MelloMario.Objects.Blocks.Brick.OnDestroy().
        {
            HandlerPoints?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = points
                });
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected], [inherited]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
StopHorizontalMovement()
void MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement () [protected]
Definition at line 173 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.X = 0;
        }
StopVerticalMovement()
void MelloMario.Objects.BaseCollidableObject.StopVerticalMovement () [protected]
Definition at line 178 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.Y = 0;
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
Member Data Documentation
movement
Point MelloMario.Objects.BaseCollidableObject.movement [private]
Definition at line 19 of file BaseCollidableObject.cs.
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected], [inherited]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get], [inherited]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
Event Documentation
HandlerLives
 LivesHandler MelloMario.Objects.BaseCollidableObject.HandlerLives
Definition at line 32 of file BaseCollidableObject.cs.
HandlerPoints
 PointHandler MelloMario.Objects.BaseCollidableObject.HandlerPoints
Definition at line 31 of file BaseCollidableObject.cs.
Referenced by MelloMario.Theming.ScoreListener.Subscribe().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/BaseClasses/Objects/ BaseCollidableObject.cs