MelloMario.Containers.Session Class Reference
Public Member Functions
IEnumerable< IWorld > ScanWorlds ()
IEnumerable< IPlayer > ScanPlayers ()
void Add (Value value)
void Move (Value value)
void Remove (Value value)
void Update ()
void Add (T value)
void Move (T value)
void Remove (T value)
void Update ()
Protected Member Functions
override IWorld GetKey (IPlayer value)
abstract Key GetKey (Value value)
IEnumerable< Value > Scan (Key key)
IEnumerable< Key > ScanKeys ()
IEnumerable< Value > ScanValues ()
Detailed Description
Definition at line 11 of file Session.cs.
Member Function Documentation
Add() [1/2]
void MelloMario.IContainer< T >.Add (T value) [inherited]
Add() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Add (Value value) [inherited]
Definition at line 78 of file BaseContainer.cs.
        {
            toAdd.Add(value);
        }
GetKey() [1/2]
override IWorld MelloMario.Containers.Session.GetKey (IPlayer value) [protected]
Definition at line 23 of file Session.cs.
References MelloMario.IPlayer.Character, and MelloMario.ICharacter.CurrentWorld.
        {
            return value.Character.CurrentWorld;
        }
GetKey() [2/2]
abstract Key MelloMario.Containers.BaseContainer< Key, Value >.GetKey (Value value) [protected], [pure virtual], [inherited]
Move() [1/2]
void MelloMario.IContainer< T >.Move (T value) [inherited]
Move() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Move (Value value) [inherited]
Definition at line 83 of file BaseContainer.cs.
        {
            toMove.Add(value);
        }
Remove() [1/2]
void MelloMario.IContainer< T >.Remove (T value) [inherited]
Remove() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Remove (Value value) [inherited]
Definition at line 88 of file BaseContainer.cs.
        {
            toRemove.Add(value);
        }
Scan()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.Scan (Key key) [protected], [inherited]
Definition at line 53 of file BaseContainer.cs.
        {
            if (values.ContainsKey(key))
            {
                return values[key];
            }
            return Enumerable.Empty<Value>();
        }
ScanKeys()
IEnumerable<Key> MelloMario.Containers.BaseContainer< Key, Value >.ScanKeys () [protected], [inherited]
Definition at line 62 of file BaseContainer.cs.
Referenced by MelloMario.Containers.Session::ScanWorlds().
        {
            return values.Keys;
        }
ScanPlayers()
IEnumerable< IPlayer> MelloMario.Containers.Session.ScanPlayers ()
Implements MelloMario.ISession .
Definition at line 18 of file Session.cs.
References MelloMario.Containers.BaseContainer< IWorld, IPlayer >.ScanValues().
        {
            return ScanValues();
        }
ScanValues()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.ScanValues () [protected], [inherited]
Definition at line 67 of file BaseContainer.cs.
Referenced by MelloMario.Containers.Session::ScanPlayers().
        {
            foreach (ISet<Value> value in values.Values)
            {
                foreach (Value item in value)
                {
                    yield return item;
                }
            }
        }
ScanWorlds()
IEnumerable< IWorld> MelloMario.Containers.Session.ScanWorlds ()
Implements MelloMario.ISession .
Definition at line 13 of file Session.cs.
References MelloMario.Containers.BaseContainer< IWorld, IPlayer >.ScanKeys().
        {
            return ScanKeys();
        }
Update() [1/2]
void MelloMario.IContainer< T >.Update () [inherited]
Update() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Update () [inherited]
Definition at line 93 of file BaseContainer.cs.
References MelloMario.Containers.BaseContainer< Key, Value >::DoAdd(), and MelloMario.Containers.BaseContainer< Key, Value >::DoRemove().
        {
            foreach (Value value in toAdd)
            {
                if (!keys.ContainsKey(value))
                {
                    DoAdd(value);
                }
            }
            toAdd.Clear();
            foreach (Value value in toMove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                    DoAdd(value);
                }
            }
            toMove.Clear();
            foreach (Value value in toRemove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                }
            }
            toRemove.Clear();
        }
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Containers/ Session.cs