MelloMario.Objects.UserInterfaces.HUD Class Reference
Public Member Functions
 HUD (IPlayer player)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Member Functions
override void OnUpdate (int time)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Offset (ref Rectangle rect)
void UpdateOrigin ()
Protected Attributes
 IPlayer Player
Point RelativeOrigin
Private Attributes
readonly ISprite coinSprite
readonly ISprite oneUpSprite
Rectangle coinDestinationRect
Rectangle oneUpDestinationRect
Rectangle textDestinationRect
string text
 ISprite textSprite
Detailed Description
Definition at line 11 of file HUD.cs.
Constructor & Destructor Documentation
HUD()
MelloMario.Objects.UserInterfaces.HUD.HUD (IPlayer player)
Definition at line 21 of file HUD.cs.
References MelloMario.ISpriteFactory< T >.CreateCoinSprite(), MelloMario.ISpriteFactory< T >.CreateOneUpMushroomSprite(), MelloMario.ISpriteFactory< T >.CreateTextSprite(), and MelloMario.Factories.SpriteFactory.Instance.
                                   : base(player)
        {
            textSprite = SpriteFactory.Instance.CreateTextSprite("");
            coinSprite = SpriteFactory.Instance.CreateCoinSprite(true);
            oneUpSprite = SpriteFactory.Instance.CreateOneUpMushroomSprite();
            textDestinationRect = new Rectangle(42, 42, 800, 200);
            coinDestinationRect = new Rectangle(255, 74, 26, 30);
            oneUpDestinationRect = new Rectangle(255, 42, 26, 30);
            // OnUpdate(0);
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseUIObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 27 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnDraw().
        {
            OnDraw(time, spriteBatch);
        }
Offset()
void MelloMario.Objects.BaseUIObject.Offset (ref Rectangle rect) [protected], [inherited]
Definition at line 32 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            rect.Offset(Player.Camera.Viewport.Location - RelativeOrigin);
        }
OnDraw()
override void MelloMario.Objects.UserInterfaces.HUD.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 57 of file HUD.cs.
References MelloMario.ISprite.Draw().
        {
            textSprite.Draw(time, spriteBatch, textDestinationRect);
            coinSprite.Draw(time, spriteBatch, coinDestinationRect);
            oneUpSprite.Draw(time, spriteBatch, oneUpDestinationRect);
        }
OnUpdate()
override void MelloMario.Objects.UserInterfaces.HUD.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 32 of file HUD.cs.
References MelloMario.Theming.Player.Coins, MelloMario.ISpriteFactory< T >.CreateTextSprite(), MelloMario.Factories.SpriteFactory.Instance, MelloMario.Theming.Player.Lifes, MelloMario.Objects.BaseUIObject.Offset(), MelloMario.Theming.Player.Score, MelloMario.Theming.Player.TimeRemain, and MelloMario.Objects.BaseUIObject.UpdateOrigin().
        {
            Offset(ref coinDestinationRect);
            Offset(ref textDestinationRect);
            Offset(ref oneUpDestinationRect);
            UpdateOrigin();
            string newText = "MARIO *"
                + Player.Lifes.ToString().PadLeft(2, '0')
                + " WORLD TIME\n"
                + Player.Score.ToString().PadLeft(6, '0')
                + " *"
                + Player.Coins.ToString().PadLeft(2, '0')
                + " "
                + "1-1"
                + " "
                + Player.TimeRemain / 1000; // TODO: get World name from player.CurrentWorld
            if (newText != text)
            {
                text = newText;
                textSprite = SpriteFactory.Instance.CreateTextSprite(text);
            }
        }
Update()
void MelloMario.Objects.BaseUIObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 22 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnUpdate().
        {
            OnUpdate(time);
        }
UpdateOrigin()
void MelloMario.Objects.BaseUIObject.UpdateOrigin () [protected], [inherited]
Definition at line 37 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, MelloMario.Objects.BaseUIObject.OnDraw(), MelloMario.Objects.BaseUIObject.OnUpdate(), and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            RelativeOrigin = Player.Camera.Viewport.Location;
        }
Member Data Documentation
coinDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.HUD.coinDestinationRect [private]
Definition at line 15 of file HUD.cs.
coinSprite
readonly ISprite MelloMario.Objects.UserInterfaces.HUD.coinSprite [private]
Definition at line 13 of file HUD.cs.
oneUpDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.HUD.oneUpDestinationRect [private]
Definition at line 16 of file HUD.cs.
oneUpSprite
readonly ISprite MelloMario.Objects.UserInterfaces.HUD.oneUpSprite [private]
Definition at line 14 of file HUD.cs.
Player
 IPlayer MelloMario.Objects.BaseUIObject.Player [protected], [inherited]
Definition at line 12 of file BaseUIObject.cs.
RelativeOrigin
Point MelloMario.Objects.BaseUIObject.RelativeOrigin [protected], [inherited]
Definition at line 13 of file BaseUIObject.cs.
text
string MelloMario.Objects.UserInterfaces.HUD.text [private]
Definition at line 18 of file HUD.cs.
textDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.HUD.textDestinationRect [private]
Definition at line 17 of file HUD.cs.
textSprite
 ISprite MelloMario.Objects.UserInterfaces.HUD.textSprite [private]
Definition at line 19 of file HUD.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/UserInterfaces/ HUD.cs