MelloMario.Controls.Controllers.KeyboardController Class Reference
Public Member Functions
 KeyboardController ()
void AddCommand (object key, ICommand value, KeyBehavior behavior)
void Update ()
void Reset ()
Protected Member Functions
override void OnUpdate ()
void RunCommand (T key, KeyBehavior behavior)
Private Attributes
KeyboardState previousState
Detailed Description
Definition at line 9 of file KeyboardController.cs.
Constructor & Destructor Documentation
KeyboardController()
MelloMario.Controls.Controllers.KeyboardController.KeyboardController ()
Definition at line 13 of file KeyboardController.cs.
        {
            previousState = Keyboard.GetState();
        }
Member Function Documentation
AddCommand()
void MelloMario.Controls.Controllers.BaseController< T >.AddCommand (object key, ICommand value, KeyBehavior behavior) [inherited]
Definition at line 29 of file BaseController.cs.
        {
            if (key is T castedKey)
            {
                commands[behavior].Add(castedKey, value);
            }
        }
OnUpdate()
override void MelloMario.Controls.Controllers.KeyboardController.OnUpdate () [protected], [virtual]
Implements MelloMario.Controls.Controllers.BaseController< Keys > .
Definition at line 18 of file KeyboardController.cs.
References MelloMario.Controls.Controllers.BaseController< Keys >.RunCommand().
        {
            // Get the current Keyboard state.
            KeyboardState currentState = Keyboard.GetState();
            foreach (Keys key in currentState.GetPressedKeys())
            {
                if (!previousState.IsKeyDown(key))
                {
                    RunCommand(key, KeyBehavior.press);
                }
                else
                {
                    RunCommand(key, KeyBehavior.hold);
                }
            }
            foreach (Keys key in previousState.GetPressedKeys())
            {
                if (!currentState.IsKeyDown(key))
                {
                    RunCommand(key, KeyBehavior.release);
                }
            }
            // Update previous Keyboard state.
            previousState = currentState;
        }
Reset()
void MelloMario.Controls.Controllers.BaseController< T >. Reset () [inherited]
Definition at line 42 of file BaseController.cs.
References MelloMario.Controls.Controllers.BaseController< T >::OnUpdate().
        {
            foreach (IDictionary<T, ICommand> dict in commands.Values)
            {
                dict.Clear();
            }
        }
RunCommand()
void MelloMario.Controls.Controllers.BaseController< T >.RunCommand (T key, KeyBehavior behavior) [protected], [inherited]
Definition at line 52 of file BaseController.cs.
Referenced by MelloMario.Controls.Controllers.KeyboardController::OnUpdate().
        {
            if (commands[behavior].ContainsKey(key))
            {
                commands[behavior][key].Execute();
            }
        }
Update()
void MelloMario.Controls.Controllers.BaseController< T >.Update () [inherited]
Definition at line 37 of file BaseController.cs.
References MelloMario.Controls.Controllers.BaseController< T >::OnUpdate().
        {
            OnUpdate();
        }
Member Data Documentation
previousState
KeyboardState MelloMario.Controls.Controllers.KeyboardController.previousState [private]
Definition at line 11 of file KeyboardController.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Controls/Controllers/ KeyboardController.cs