MelloMario.Objects.Blocks.Brick Class Reference
Public Member Functions
 Brick (IWorld world, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener, bool isHidden=false)
void Initialize (bool hidden=false)
void OnDestroy ()
void Remove ()
void Bump (Mario mario)
void BumpMove (int delta)
void ReleaseNextItem ()
delegate void LivesHandler (BaseCollidableObject m, ScoreEventArgs e)
delegate void PointHandler (BaseCollidableObject m, ScoreEventArgs e)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum CollisionMode {
 CollisionMode.Left,
 CollisionMode.Right,
 CollisionMode.Top,
 CollisionMode.Bottom,
 CollisionMode.InnerLeft,
 CollisionMode.InnerRight,
 CollisionMode.InnerTop,
 CollisionMode.InnerBottom
 }
enum CornerMode {
 CornerMode.Left,
 CornerMode.Right,
 CornerMode.Top,
 CornerMode.Bottom,
 CornerMode.Center
 }
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
override void OnUpdate (int time)
override void OnSimulation (int time)
override void OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive)
override void OnCollideWorld (CollisionMode mode, CollisionMode modePassive)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Move (Point delta)
void StopHorizontalMovement ()
void StopVerticalMovement ()
void RemoveSelf ()
void ScorePoints (int points)
void ChangeLives ()
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 IWorld World
Properties
 ISoundArgs SoundEventArgs [get]
bool HasInitialItem [get, private set]
 IBlockState State [get, set]
Rectangle Boundary [get]
Events
 SoundHandler SoundEvent
 PointHandler HandlerPoints
 LivesHandler HandlerLives
Private Member Functions
void UpdateSprite ()
Private Attributes
bool isHidden
 IBlockState state
Detailed Description
Definition at line 17 of file Brick.cs.
Member Enumeration Documentation
CollisionMode
enum MelloMario.Objects.BaseCollidableObject.CollisionMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
InnerLeft
InnerRight
InnerTop
InnerBottom
Definition at line 266 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            InnerLeft,
            InnerRight,
            InnerTop,
            InnerBottom
        }
CornerMode
enum MelloMario.Objects.BaseCollidableObject.CornerMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
Center
Definition at line 278 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            Center
        }
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected], [inherited]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected], [inherited]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
Brick()
MelloMario.Objects.Blocks.Brick.Brick (IWorld world, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener, bool isHidden = false)
Definition at line 23 of file Brick.cs.
References MelloMario.Objects.Blocks.Brick.isHidden, MelloMario.Objects.Blocks.Brick.SoundEventArgs, and MelloMario.IListener< in in T >.Subscribe().
                                   : base(
            world,
            location,
            listener,
            new Point(32, 32))
        {
            this.isHidden = isHidden;
            soundListener.Subscribe(this);
            SoundEventArgs = new SoundArgs();
        }
Member Function Documentation
Bump()
void MelloMario.Objects.Blocks.Brick.Bump (Mario mario)
Definition at line 127 of file Brick.cs.
References MelloMario.IBlockState.Bump(), MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.Blocks.Brick.SoundEventArgs, and MelloMario.Objects.Blocks.Brick.State.
Referenced by MelloMario.Objects.Characters.Mario.OnCollision().
        {
            SoundEventArgs.SetMethodCalled();
            State.Bump(mario);
        }
BumpMove()
void MelloMario.Objects.Blocks.Brick.BumpMove (int delta)
Definition at line 133 of file Brick.cs.
References MelloMario.Objects.BaseCollidableObject.Move().
        {
            Move(new Point(0, delta));
        }
ChangeLives()
void MelloMario.Objects.BaseCollidableObject.ChangeLives () [protected], [inherited]
Definition at line 256 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.OneUpMushroom.Collect(), and MelloMario.Objects.Blocks.Flag.OnCollision().
        {
            HandlerLives?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = 1
                });
        }
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected], [inherited]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
Initialize()
void MelloMario.Objects.Blocks.Brick.Initialize (bool hidden = false)
Definition at line 54 of file Brick.cs.
References MelloMario.Objects.Blocks.Brick.HasInitialItem, MelloMario.Theming.Database.HasItemEnclosed(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            isHidden = hidden;
            if (isHidden)
            {
                state = new Hidden(this);
            }
            else
            {
                state = new Normal(this);
            }
            HasInitialItem = Database.HasItemEnclosed(this);
            UpdateSprite();
        }
LivesHandler()
delegate void MelloMario.Objects.BaseCollidableObject.LivesHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
Move()
void MelloMario.Objects.BaseCollidableObject.Move (Point delta) [protected], [inherited]
Definition at line 166 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Move().
Referenced by MelloMario.Objects.Blocks.Question.BumpMove(), MelloMario.Objects.Blocks.Brick.BumpMove(), MelloMario.Objects.BasePhysicalObject.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Items.FireFlower.UnveilMove(), MelloMario.Objects.Items.Coin.UnveilMove(), MelloMario.Objects.Items.OneUpMushroom.UnveilMove(), MelloMario.Objects.Items.Star.UnveilMove(), and MelloMario.Objects.Items.SuperMushroom.UnveilMove().
        {
            movement += delta;
            World.Move(this);
        }
OnCollideWorld()
override void MelloMario.Objects.Blocks.Brick.OnCollideWorld (CollisionMode mode, CollisionMode modePassive) [protected], [virtual]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 108 of file Brick.cs.
        {
        }
OnCollision()
override void MelloMario.Objects.Blocks.Brick.OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive) [protected], [virtual]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 99 of file Brick.cs.
        {
        }
OnDestroy()
void MelloMario.Objects.Blocks.Brick.OnDestroy ()
Definition at line 116 of file Brick.cs.
References MelloMario.Theming.Const.SCORE_BRICK, MelloMario.Objects.BaseCollidableObject.ScorePoints(), MelloMario.ISoundArgs.SetMethodCalled(), and MelloMario.Objects.Blocks.Brick.SoundEventArgs.
        {
            SoundEventArgs.SetMethodCalled();
            ScorePoints(Const.SCORE_BRICK);
        }
OnDraw()
override void MelloMario.Objects.Blocks.Brick.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 112 of file Brick.cs.
        {
        }
OnSimulation()
override void MelloMario.Objects.Blocks.Brick.OnSimulation (int time) [protected], [virtual]
Reimplemented from MelloMario.Objects.BaseCollidableObject .
Definition at line 93 of file Brick.cs.
References MelloMario.Objects.Blocks.Brick.SoundEvent, and MelloMario.Objects.Blocks.Brick.SoundEventArgs.
        {
            SoundEvent?.Invoke(this, SoundEventArgs);
            base.OnSimulation(time);
        }
OnUpdate()
override void MelloMario.Objects.Blocks.Brick.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 88 of file Brick.cs.
References MelloMario.IState.Update().
        {
            state.Update(time);
        }
PointHandler()
delegate void MelloMario.Objects.BaseCollidableObject.PointHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
ReleaseNextItem()
void MelloMario.Objects.Blocks.Brick.ReleaseNextItem ()
Definition at line 138 of file Brick.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Add(), MelloMario.Theming.Database.GetNextItem(), MelloMario.Theming.Database.HasItemEnclosed(), and MelloMario.Containers.BaseContainer< Key, Value >.Update().
        {
            if (!Database.HasItemEnclosed(this))
            {
                return;
            }
            IGameObject item = Database.GetNextItem(this);
            World.Update();
            World.Add(item);
        }
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected], [inherited]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
Remove()
void MelloMario.Objects.Blocks.Brick.Remove ()
Definition at line 122 of file Brick.cs.
References MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            RemoveSelf();
        }
RemoveSelf()
void MelloMario.Objects.BaseCollidableObject.RemoveSelf () [protected], [inherited]
Definition at line 183 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Remove(), MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Items.Coin.Coin(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.OneUpMushroom.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Objects.Blocks.Brick.Remove(), MelloMario.Objects.Characters.MarioCharacter.Remove(), MelloMario.Objects.Items.Star.Star(), and MelloMario.Objects.Items.SuperMushroom.SuperMushroom().
        {
            StopHorizontalMovement();
            StopVerticalMovement();
            World.Remove(this);
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected], [inherited]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
ScorePoints()
void MelloMario.Objects.BaseCollidableObject.ScorePoints (int points) [protected], [inherited]
Definition at line 246 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Blocks.Flag.OnCollision(), and MelloMario.Objects.Blocks.Brick.OnDestroy().
        {
            HandlerPoints?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = points
                });
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected], [inherited]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
StopHorizontalMovement()
void MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement () [protected], [inherited]
Definition at line 173 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.X = 0;
        }
StopVerticalMovement()
void MelloMario.Objects.BaseCollidableObject.StopVerticalMovement () [protected], [inherited]
Definition at line 178 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.Y = 0;
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
UpdateSprite()
void MelloMario.Objects.Blocks.Brick.UpdateSprite () [private]
Definition at line 69 of file Brick.cs.
References MelloMario.ISpriteFactory< T >.CreateBrickSprite(), MelloMario.ISpriteFactory< T >.CreateQuestionSprite(), MelloMario.Objects.BaseGameObject.HideSprite(), MelloMario.Factories.SpriteFactory.Instance, and MelloMario.Objects.BaseGameObject.ShowSprite().
Referenced by MelloMario.Objects.Blocks.Brick.Initialize().
        {
            switch (state)
            {
                case IState s when s is Hidden:
                    HideSprite();
                    break;
                case IState s when s is Destroyed:
                    ShowSprite(SpriteFactory.Instance.CreateBrickSprite("Destroyed"));
                    break;
                case IState s when s is Normal:
                    ShowSprite(SpriteFactory.Instance.CreateBrickSprite("Normal"));
                    break;
                case IState s when s is Used:
                    ShowSprite(SpriteFactory.Instance.CreateQuestionSprite("Used"));
                    break;
            }
        }
Member Data Documentation
isHidden
bool MelloMario.Objects.Blocks.Brick.isHidden [private]
Definition at line 19 of file Brick.cs.
Referenced by MelloMario.Objects.Blocks.Brick.Brick().
state
 IBlockState MelloMario.Objects.Blocks.Brick.state [private]
Definition at line 20 of file Brick.cs.
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected], [inherited]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get], [inherited]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
HasInitialItem
bool MelloMario.Objects.Blocks.Brick.HasInitialItem [get], [private set]
Definition at line 39 of file Brick.cs.
Referenced by MelloMario.Objects.Blocks.Brick.Initialize().
SoundEventArgs
 ISoundArgs MelloMario.Objects.Blocks.Brick.SoundEventArgs [get]
Definition at line 21 of file Brick.cs.
Referenced by MelloMario.Objects.Blocks.Brick.Brick(), MelloMario.Objects.Blocks.Brick.Bump(), MelloMario.Objects.Blocks.Brick.OnDestroy(), and MelloMario.Objects.Blocks.Brick.OnSimulation().
State
 IBlockState MelloMario.Objects.Blocks.Brick.State [get], [set]
Definition at line 42 of file Brick.cs.
Referenced by MelloMario.Objects.Blocks.Brick.Bump(), MelloMario.Objects.Enemies.Goomba.OnCollision(), MelloMario.Objects.Items.OneUpMushroom.OnCollision(), MelloMario.Objects.Items.Star.OnCollision(), MelloMario.Objects.Enemies.Koopa.OnCollision(), MelloMario.Objects.Items.SuperMushroom.OnCollision(), and MelloMario.Objects.Characters.Mario.OnCollision().
Event Documentation
HandlerLives
 LivesHandler MelloMario.Objects.BaseCollidableObject.HandlerLives [inherited]
Definition at line 32 of file BaseCollidableObject.cs.
HandlerPoints
 PointHandler MelloMario.Objects.BaseCollidableObject.HandlerPoints [inherited]
Definition at line 31 of file BaseCollidableObject.cs.
Referenced by MelloMario.Theming.ScoreListener.Subscribe().
SoundEvent
 SoundHandler MelloMario.Objects.Blocks.Brick.SoundEvent
Definition at line 149 of file Brick.cs.
Referenced by MelloMario.Objects.Blocks.Brick.OnSimulation().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Blocks/ Brick.cs