MelloMario.Factories.SoundFactory Class Reference
Public Member Functions
void BindLoader (ContentManager loader)
 ISoundTrack CreateSoundTrack (string name)
 ISoundEffect CreateSoundEffect (string name)
void BindLoader (T loader)
Properties
static ISoundFactory< ContentManager > Instance [get]
Private Member Functions
 SoundFactory ()
Song GetSong (string name)
SoundEffectInstance GetSoundEffect (string name)
Private Attributes
readonly IDictionary< string, Song > songs
readonly IDictionary< string, SoundEffectInstance > soundEffects
ContentManager content
Detailed Description
Definition at line 13 of file SoundFactory.cs.
Constructor & Destructor Documentation
SoundFactory()
MelloMario.Factories.SoundFactory.SoundFactory () [private]
Definition at line 19 of file SoundFactory.cs.
        {
            songs = new Dictionary<string, Song>();
            soundEffects = new Dictionary<string, SoundEffectInstance>();
        }
Member Function Documentation
BindLoader() [1/2]
void MelloMario.ISoundFactory< T >.BindLoader (T loader) [inherited]
BindLoader() [2/2]
void MelloMario.Factories.SoundFactory.BindLoader (ContentManager loader)
Definition at line 47 of file SoundFactory.cs.
        {
            content = loader;
        }
CreateSoundEffect()
 ISoundEffect MelloMario.Factories.SoundFactory.CreateSoundEffect (string name)
Definition at line 70 of file SoundFactory.cs.
References MelloMario.Factories.SoundFactory.GetSoundEffect().
        {
            switch (name)
            {
                case "Bounce":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_jumpsmall"));
                case "PowerBounce":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_jump"));
                case "BumpBlock":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_bump"));
                case "BreakBlock":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_breakblock"));
                case "Coin":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_coin"));
                case "Death":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_mariodie"));
                case "PowerUp":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_powerup"));
                case "EnemyKill":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_stomp"));
                case "Pipe": //Same sound for downgrade to standard mario
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_pipe"));
                case "GameOver":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_gameover"));
                case "GameWon":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_stage_clear"));
                case "Unveil":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_powerup_appears"));
                case "OneUpCollect":
                    return new Sounds.SoundEffect(GetSoundEffect("SFX/smb_1"));
                default:
                    // never reach
                    return null;
            }
        }
CreateSoundTrack()
 ISoundTrack MelloMario.Factories.SoundFactory.CreateSoundTrack (string name)
Definition at line 52 of file SoundFactory.cs.
References MelloMario.Factories.SoundFactory.GetSong().
        {
            switch (name)
            {
                case "Normal":
                    return new SoundTrack(GetSong("Music/01-main-theme-overworld"));
                case "BelowGround":
                    return new SoundTrack(GetSong("Music/02-underworld"));
                case "Star":
                    return new SoundTrack(GetSong("Music/05-starman"));
                case "Hurry":
                    return new SoundTrack(GetSong("Music/18-hurry-overworld-"));
                default:
                    // never reach
                    return null;
            }
        }
GetSong()
Song MelloMario.Factories.SoundFactory.GetSong (string name) [private]
Definition at line 25 of file SoundFactory.cs.
Referenced by MelloMario.Factories.SoundFactory.CreateSoundTrack().
        {
            if (!songs.ContainsKey(name))
            {
                songs.Add(name, content.Load<Song>(name));
            }
            return songs[name];
        }
GetSoundEffect()
SoundEffectInstance MelloMario.Factories.SoundFactory.GetSoundEffect (string name) [private]
Definition at line 35 of file SoundFactory.cs.
Referenced by MelloMario.Factories.SoundFactory.CreateSoundEffect().
        {
            if (!soundEffects.ContainsKey(name))
            {
                soundEffects.Add(name, content.Load<Microsoft.Xna.Framework.Audio.SoundEffect>(name).
      CreateInstance());
            }
            return soundEffects[name];
        }
Member Data Documentation
content
ContentManager MelloMario.Factories.SoundFactory.content [private]
Definition at line 17 of file SoundFactory.cs.
songs
readonly IDictionary<string, Song> MelloMario.Factories.SoundFactory.songs [private]
Definition at line 15 of file SoundFactory.cs.
soundEffects
readonly IDictionary<string, SoundEffectInstance> MelloMario.Factories.SoundFactory.soundEffects [private]
Definition at line 16 of file SoundFactory.cs.
Property Documentation
Instance
 ISoundFactory<ContentManager> MelloMario.Factories.SoundFactory.Instance [static], [get]
Definition at line 45 of file SoundFactory.cs.
Referenced by MelloMario.Game1.LoadContent(), and MelloMario.Sounds.SoundEffectListener.PlayEffect().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Factories/ SoundFactory.cs