MelloMario.Objects.Enemies.Koopa Class Reference
Public Member Functions
 Koopa (IWorld world, Point location, IListener< IGameObject > listener, string color)
void JumpOn ()
void Pushed ()
void Defeat ()
delegate void LivesHandler (BaseCollidableObject m, ScoreEventArgs e)
delegate void PointHandler (BaseCollidableObject m, ScoreEventArgs e)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum FacingMode { FacingMode.left,
 FacingMode.right
 }
enum CollisionMode {
 CollisionMode.Left,
 CollisionMode.Right,
 CollisionMode.Top,
 CollisionMode.Bottom,
 CollisionMode.InnerLeft,
 CollisionMode.InnerRight,
 CollisionMode.InnerTop,
 CollisionMode.InnerBottom
 }
enum CornerMode {
 CornerMode.Left,
 CornerMode.Right,
 CornerMode.Top,
 CornerMode.Bottom,
 CornerMode.Center
 }
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
override void OnUpdate (int time)
override void OnSimulation (int time)
override void OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive)
override void OnCollideWorld (CollisionMode mode, CollisionMode modePassive)
override void OnDraw (int time, SpriteBatch spriteBatch)
void ApplyAccel (Vector2 delta)
void ApplyGravity (float gravity= Const.ACCEL_G)
void ApplyHorizontalFriction (float friction)
void ApplyVerticalFriction (float friction)
void SetHorizontalVelocity (float constVelocity)
void SetVerticalVelocity (float constVelocity)
bool Bounce (CollisionMode mode, Vector2 refVelocity, float rate=0)
void Move (Point delta)
void StopHorizontalMovement ()
void StopVerticalMovement ()
void RemoveSelf ()
void ScorePoints (int points)
void ChangeLives ()
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 FacingMode Facing
 IWorld World
Properties
 IKoopaState State [get, set]
Rectangle Boundary [get]
Events
 PointHandler HandlerPoints
 LivesHandler HandlerLives
Private Member Functions
void UpdateSprite ()
void ChangeFacing (FacingMode facing)
Private Attributes
readonly string color
 IKoopaState state
Detailed Description
Definition at line 21 of file Koopa.cs.
Member Enumeration Documentation
CollisionMode
enum MelloMario.Objects.BaseCollidableObject.CollisionMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
InnerLeft
InnerRight
InnerTop
InnerBottom
Definition at line 266 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            InnerLeft,
            InnerRight,
            InnerTop,
            InnerBottom
        }
CornerMode
enum MelloMario.Objects.BaseCollidableObject.CornerMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
Center
Definition at line 278 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            Center
        }
FacingMode
enum MelloMario.Objects.BasePhysicalObject.FacingMode [strong], [protected], [inherited]
Enumerator
left
right
Definition at line 203 of file BasePhysicalObject.cs.
        {
            left,
            right
        }
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected], [inherited]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected], [inherited]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
Koopa()
MelloMario.Objects.Enemies.Koopa.Koopa (IWorld world, Point location, IListener< IGameObject > listener, string color)
Definition at line 26 of file Koopa.cs.
References MelloMario.Objects.Enemies.Koopa.color, MelloMario.Objects.Enemies.Koopa.State, and MelloMario.Objects.Enemies.Koopa.UpdateSprite().
                                                                                                  :
            base(world, location, listener, new Point(32, 32), 32)
        {
            this.color = color;
            state = new KoopaStates.Normal(this);
            UpdateSprite();
        }
Member Function Documentation
ApplyAccel()
void MelloMario.Objects.BasePhysicalObject.ApplyAccel (Vector2 delta) [protected], [inherited]
Definition at line 33 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.ApplyGravity(), and MelloMario.Objects.Characters.MarioCharacter.OnUpdate().
        {
            accel += delta;
        }
ApplyGravity()
void MelloMario.Objects.BasePhysicalObject.ApplyGravity (float gravity = Const.ACCEL_G) [protected], [inherited]
Definition at line 38 of file BasePhysicalObject.cs.
References MelloMario.Objects.BasePhysicalObject.ApplyAccel().
Referenced by MelloMario.Objects.Enemies.Thwomp.OnSimulation(), MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), MelloMario.Objects.Items.SuperMushroom.OnSimulation(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            ApplyAccel(new Vector2(0, gravity));
        }
ApplyHorizontalFriction()
void MelloMario.Objects.BasePhysicalObject.ApplyHorizontalFriction (float friction) [protected], [inherited]
Definition at line 43 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Characters.Mario.OnCollision(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            if (frictionalAccel.X < friction)
            {
                frictionalAccel.X = friction;
            }
        }
ApplyVerticalFriction()
void MelloMario.Objects.BasePhysicalObject.ApplyVerticalFriction (float friction) [protected], [inherited]
Definition at line 51 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Items.Star.OnCollision(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            if (frictionalAccel.Y < friction)
            {
                frictionalAccel.Y = friction;
            }
        }
Bounce()
bool MelloMario.Objects.BasePhysicalObject.Bounce (CollisionMode mode, Vector2 refVelocity, float rate = 0) [protected], [inherited]
Definition at line 69 of file BasePhysicalObject.cs.
References MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Characters.Mario.OnCollideWorld(), MelloMario.Objects.Enemies.Thwomp.OnCollision(), MelloMario.Objects.Enemies.Goomba.OnCollision(), MelloMario.Objects.Items.OneUpMushroom.OnCollision(), MelloMario.Objects.Items.Star.OnCollision(), MelloMario.Objects.Enemies.Koopa.OnCollision(), MelloMario.Objects.Items.SuperMushroom.OnCollision(), and MelloMario.Objects.Characters.Mario.OnCollision().
        {
            switch (mode)
            {
                case CollisionMode.Left:
                case CollisionMode.InnerLeft:
                    if (velocity.X < refVelocity.X)
                    {
                        // movement.X = 0;
                        velocity.X = refVelocity.X + (refVelocity.X - velocity.X) * rate;
                        StopHorizontalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Right:
                case CollisionMode.InnerRight:
                    if (velocity.X > refVelocity.X)
                    {
                        // movement.X = 0;
                        velocity.X = refVelocity.X + (refVelocity.X - velocity.X) * rate;
                        StopHorizontalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Top:
                case CollisionMode.InnerTop:
                    if (velocity.Y < refVelocity.Y)
                    {
                        // movement.Y = 0;
                        velocity.Y = refVelocity.Y + (refVelocity.Y - velocity.Y) * rate;
                        StopVerticalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Bottom:
                case CollisionMode.InnerBottom:
                    if (velocity.Y > refVelocity.Y)
                    {
                        // movement.Y = 0;
                        velocity.Y = refVelocity.Y + (refVelocity.Y - velocity.Y) * rate;
                        StopVerticalMovement();
                        return true;
                    }
                    return false;
                default:
                    // never reach
                    return false;
            }
        }
ChangeFacing()
void MelloMario.Objects.Enemies.Koopa.ChangeFacing (FacingMode facing) [private]
Definition at line 61 of file Koopa.cs.
References MelloMario.Objects.BasePhysicalObject.Facing, and MelloMario.Objects.Enemies.Koopa.UpdateSprite().
Referenced by MelloMario.Objects.Enemies.Koopa.OnCollision().
        {
            Facing = facing;
            // Notice: The effect should be the same as changing state
            UpdateSprite();
        }
ChangeLives()
void MelloMario.Objects.BaseCollidableObject.ChangeLives () [protected], [inherited]
Definition at line 256 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.OneUpMushroom.Collect(), and MelloMario.Objects.Blocks.Flag.OnCollision().
        {
            HandlerLives?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = 1
                });
        }
Defeat()
void MelloMario.Objects.Enemies.Koopa.Defeat ()
Definition at line 219 of file Koopa.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Objects.BaseCollidableObject.RemoveSelf(), MelloMario.Theming.Const.SCORE_KOOPA, and MelloMario.Objects.BaseCollidableObject.ScorePoints().
Referenced by MelloMario.Objects.Enemies.Koopa.OnCollision().
        {
            ScorePoints(Const.SCORE_KOOPA);
            new PopingUpPoints(World, Boundary.Location, Const.SCORE_KOOPA);
            RemoveSelf();
        }
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected], [inherited]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
JumpOn()
void MelloMario.Objects.Enemies.Koopa.JumpOn ()
Definition at line 198 of file Koopa.cs.
References MelloMario.IKoopaState.JumpOn(), MelloMario.Theming.Const.SCORE_KOOPA, MelloMario.Objects.BaseCollidableObject.ScorePoints(), and MelloMario.Objects.Enemies.Koopa.State.
Referenced by MelloMario.Objects.Enemies.Koopa.OnCollision().
        {
            ScorePoints(Const.SCORE_KOOPA);
            State.JumpOn();
        }
LivesHandler()
delegate void MelloMario.Objects.BaseCollidableObject.LivesHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
Move()
void MelloMario.Objects.BaseCollidableObject.Move (Point delta) [protected], [inherited]
Definition at line 166 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Move().
Referenced by MelloMario.Objects.Blocks.Question.BumpMove(), MelloMario.Objects.Blocks.Brick.BumpMove(), MelloMario.Objects.BasePhysicalObject.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Items.FireFlower.UnveilMove(), MelloMario.Objects.Items.Coin.UnveilMove(), MelloMario.Objects.Items.OneUpMushroom.UnveilMove(), MelloMario.Objects.Items.Star.UnveilMove(), and MelloMario.Objects.Items.SuperMushroom.UnveilMove().
        {
            movement += delta;
            World.Move(this);
        }
OnCollideWorld()
override void MelloMario.Objects.Enemies.Koopa.OnCollideWorld (CollisionMode mode, CollisionMode modePassive) [protected], [virtual]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 190 of file Koopa.cs.
        {
        }
OnCollision()
override void MelloMario.Objects.Enemies.Koopa.OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive) [protected], [virtual]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 104 of file Koopa.cs.
References MelloMario.Objects.BasePhysicalObject.Bounce(), MelloMario.Objects.Enemies.Koopa.ChangeFacing(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Blocks.Question.State, and MelloMario.Objects.Blocks.Brick.State.
        {
            switch (target)
            {
                case Mario mario:
                    if (mode == CollisionMode.Top && corner == CornerMode.Top || mario.ProtectionState is
      Starred)
                    {
                        Defeat();
                    }
                    else if (state is KoopaStates.Normal || state is MovingShell)
                    {
                        if (mode == CollisionMode.Top)
                        {
                            JumpOn();
                        }
                        else
                        {
                            mario.Downgrade();
                        }
                    }
                    else if (state is Defeated)
                    {
                        if (mode == CollisionMode.Left)
                        {
                            ChangeFacing(FacingMode.right);
                            Pushed();
                        }
                        else if (mode == CollisionMode.Right)
                        {
                            ChangeFacing(FacingMode.left);
                            Pushed();
                        }
                        else if (mode == CollisionMode.Top && corner ==
      CornerMode.Left)
                        {
                            ChangeFacing(FacingMode.right);
                            Pushed();
                        }
                        else if (mode == CollisionMode.Top && corner ==
      CornerMode.Right)
                        {
                            ChangeFacing(FacingMode.left);
                            Pushed();
                        }
                    }
                    break;
                case Brick brick when brick.State is Hidden:
                    break;
                case Question question when question.State is Blocks.QuestionStates.Hidden:
                    break;
                case IGameObject obj when target is Brick
                || target is Question
                || target is Floor
                || target is Pipeline
                || target is Stair:
                    if (mode == CollisionMode.Left)
                    {
                        Bounce(mode, new Vector2(), 1);
                        ChangeFacing(FacingMode.right);
                    }
                    else if (mode == CollisionMode.Right)
                    {
                        Bounce(mode, new Vector2(), 1);
                        ChangeFacing(FacingMode.left);
                    }
                    else if (mode == CollisionMode.Bottom)
                    {
                        Bounce(mode, new Vector2());
                    }
                    break;
                case FireBall fire:
                    Defeat();
                    break;
            }
            if (target is Koopa koopa)
            {
                if (koopa.State is MovingShell)
                {
                    Defeat();
                }
            }
        }
OnDraw()
override void MelloMario.Objects.Enemies.Koopa.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 194 of file Koopa.cs.
        {
        }
OnSimulation()
override void MelloMario.Objects.Enemies.Koopa.OnSimulation (int time) [protected], [virtual]
Reimplemented from MelloMario.Objects.BasePhysicalObject .
Definition at line 74 of file Koopa.cs.
References MelloMario.Objects.BasePhysicalObject.ApplyGravity(), MelloMario.Objects.BasePhysicalObject.Facing, MelloMario.Objects.BasePhysicalObject.SetHorizontalVelocity(), MelloMario.Theming.Const.VELOCITY_KOOPA, and MelloMario.Theming.Const.VELOCITY_KOOPA_SHELL.
        {
            ApplyGravity();
            if (state is MovingShell)
            {
                if (Facing == FacingMode.left)
                {
                    SetHorizontalVelocity(-Const.VELOCITY_KOOPA_SHELL);
                }
                else
                {
                    SetHorizontalVelocity(Const.VELOCITY_KOOPA_SHELL);
                }
            }
            else
            {
                if (Facing == FacingMode.left)
                {
                    SetHorizontalVelocity(-Const.VELOCITY_KOOPA);
                }
                else
                {
                    SetHorizontalVelocity(Const.VELOCITY_KOOPA);
                }
            }
            base.OnSimulation(time);
        }
OnUpdate()
override void MelloMario.Objects.Enemies.Koopa.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 69 of file Koopa.cs.
References MelloMario.IState.Update().
        {
            state.Update(time);
        }
PointHandler()
delegate void MelloMario.Objects.BaseCollidableObject.PointHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
Pushed()
void MelloMario.Objects.Enemies.Koopa.Pushed ()
Definition at line 204 of file Koopa.cs.
References MelloMario.Objects.BasePhysicalObject.Facing, MelloMario.Objects.BaseCollidableObject.Move(), MelloMario.IKoopaState.Pushed(), and MelloMario.Objects.Enemies.Koopa.State.
Referenced by MelloMario.Objects.Enemies.Koopa.OnCollision().
        {
            // TODO: temporary fix
            if (Facing == FacingMode.right)
            {
                Move(new Point(1, 0));
            }
            else
            {
                Move(new Point(-1, 0));
            }
            State.Pushed();
        }
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected], [inherited]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
RemoveSelf()
void MelloMario.Objects.BaseCollidableObject.RemoveSelf () [protected], [inherited]
Definition at line 183 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Remove(), MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Items.Coin.Coin(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.OneUpMushroom.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Objects.Blocks.Brick.Remove(), MelloMario.Objects.Characters.MarioCharacter.Remove(), MelloMario.Objects.Items.Star.Star(), and MelloMario.Objects.Items.SuperMushroom.SuperMushroom().
        {
            StopHorizontalMovement();
            StopVerticalMovement();
            World.Remove(this);
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected], [inherited]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
ScorePoints()
void MelloMario.Objects.BaseCollidableObject.ScorePoints (int points) [protected], [inherited]
Definition at line 246 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Blocks.Flag.OnCollision(), and MelloMario.Objects.Blocks.Brick.OnDestroy().
        {
            HandlerPoints?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = points
                });
        }
SetHorizontalVelocity()
void MelloMario.Objects.BasePhysicalObject.SetHorizontalVelocity (float constVelocity) [protected], [inherited]
Definition at line 59 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), and MelloMario.Objects.Items.SuperMushroom.OnSimulation().
        {
            velocity.X = constVelocity;
        }
SetVerticalVelocity()
void MelloMario.Objects.BasePhysicalObject.SetVerticalVelocity (float constVelocity) [protected], [inherited]
Definition at line 64 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Characters.Mario.OnDeath(), MelloMario.Objects.Enemies.Piranha.OnSimulation(), and MelloMario.Objects.Enemies.Thwomp.OnSimulation().
        {
            velocity.Y = constVelocity;
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected], [inherited]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
StopHorizontalMovement()
void MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement () [protected], [inherited]
Definition at line 173 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.X = 0;
        }
StopVerticalMovement()
void MelloMario.Objects.BaseCollidableObject.StopVerticalMovement () [protected], [inherited]
Definition at line 178 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.Y = 0;
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
UpdateSprite()
void MelloMario.Objects.Enemies.Koopa.UpdateSprite () [private]
Definition at line 47 of file Koopa.cs.
References MelloMario.ISpriteFactory< T >.CreateKoopaSprite(), MelloMario.Objects.BasePhysicalObject.Facing, MelloMario.Factories.SpriteFactory.Instance, and MelloMario.Objects.BaseGameObject.ShowSprite().
Referenced by MelloMario.Objects.Enemies.Koopa.ChangeFacing(), and MelloMario.Objects.Enemies.Koopa.Koopa().
        {
            string facingString;
            if (Facing == FacingMode.left)
            {
                facingString = "Left";
            }
            else
            {
                facingString = "Right";
            }
            ShowSprite(SpriteFactory.Instance.CreateKoopaSprite(color, state.GetType().Name + facingString)
      );
        }
Member Data Documentation
color
readonly string MelloMario.Objects.Enemies.Koopa.color [private]
Definition at line 23 of file Koopa.cs.
Referenced by MelloMario.Objects.Enemies.Koopa.Koopa().
Facing
 FacingMode MelloMario.Objects.BasePhysicalObject.Facing [protected], [inherited]
Definition at line 15 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Enemies.Koopa.ChangeFacing(), MelloMario.Objects.Characters.Mario.ChangeFacing(), MelloMario.Objects.Enemies.Goomba.ChangeFacing(), MelloMario.Objects.Enemies.Thwomp.ChangeFacing(), MelloMario.Objects.Characters.MarioCharacter.Left(), MelloMario.Objects.Items.OneUpMushroom.OnCollision(), MelloMario.Objects.Items.Star.OnCollision(), MelloMario.Objects.Items.SuperMushroom.OnCollision(), MelloMario.Objects.Enemies.Thwomp.OnSimulation(), MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), MelloMario.Objects.Items.SuperMushroom.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Characters.MarioCharacter.Right(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
state
 IKoopaState MelloMario.Objects.Enemies.Koopa.state [private]
Definition at line 24 of file Koopa.cs.
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected], [inherited]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get], [inherited]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
State
 IKoopaState MelloMario.Objects.Enemies.Koopa.State [get], [set]
Definition at line 35 of file Koopa.cs.
Referenced by MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Enemies.Koopa.Koopa(), and MelloMario.Objects.Enemies.Koopa.Pushed().
Event Documentation
HandlerLives
 LivesHandler MelloMario.Objects.BaseCollidableObject.HandlerLives [inherited]
Definition at line 32 of file BaseCollidableObject.cs.
HandlerPoints
 PointHandler MelloMario.Objects.BaseCollidableObject.HandlerPoints [inherited]
Definition at line 31 of file BaseCollidableObject.cs.
Referenced by MelloMario.Theming.ScoreListener.Subscribe().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Enemies/ Koopa.cs