MelloMario.Controls.Scripts.StartScript Class Reference
Public Member Functions
void Bind (IEnumerable< IController > controllers, IModel model, ICharacter character)
Detailed Description
Definition at line 11 of file StartScript.cs.
Member Function Documentation
Bind()
void MelloMario.Controls.Scripts.StartScript.Bind (IEnumerable< IController > controllers, IModel model, ICharacter character)
Implements MelloMario.IScript .
Definition at line 13 of file StartScript.cs.
References MelloMario.IController.AddCommand(), MelloMario.Factories.CommandFactory.Instance, and MelloMario.IController.Reset().
Referenced by MelloMario.Theming.GameModel.Init().
        {
            ICommandFactory factory = CommandFactory.Instance;
            foreach (IController controller in controllers)
            {
                controller.Reset();
                // game character commands
                controller.AddCommand(Keys.A, factory.CreateModelCommand("Normal", model),
      KeyBehavior.press);
                controller.AddCommand(Keys.B, factory.CreateModelCommand("Infinite", model),
      KeyBehavior.press);
                controller.AddCommand(Keys.Q, factory.CreateModelCommand("Quit", model),
      KeyBehavior.press);
            }
        }
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Controls/Scripts/ StartScript.cs