MelloMario.Factories.SpriteFactory Class Reference
Public Member Functions
void BindLoader (ContentManager loader)
 ISprite CreateTextSprite (string text, float fontSize=18f)
 ISprite CreateSplashSprite ()
 ISprite CreateMarioSprite (string powerUpStatus, string movementStatus, string protectionStatus, string facing)
 ISprite CreateGoombaSprite (string status)
 ISprite CreateThwompSprite (string status)
 ISprite CreateKoopaSprite (string color, string status)
 ISprite CreatePiranhaSprite (string color)
 ISprite CreateFireSprite ()
 ISprite CreateStarSprite ()
 ISprite CreateCoinSprite (bool isHud=false)
 ISprite CreateSuperMushroomSprite ()
 ISprite CreateFireFlowerSprite ()
 ISprite CreateOneUpMushroomSprite ()
 ISprite CreateQuestionSprite (string status)
 ISprite CreateBrickSprite (string status)
 ISprite CreateFloorSprite ()
 ISprite CreateStairSprite ()
 ISprite CreatePipelineSprite (string type)
 ISprite CreateFlagSprite (bool isTop)
 ISprite CreateSceneSprite (string type, ZIndex zIndex)
 ISprite CreateTitle (ZIndex zIndex)
void BindLoader (T loader)
Properties
static ISpriteFactory< ContentManager > Instance [get]
Private Member Functions
 SpriteFactory ()
Texture2D GetTexture (string name)
Private Attributes
readonly IDictionary< string, Texture2D > textures
ContentManager content
Detailed Description
Definition at line 13 of file SpriteFactory.cs.
Constructor & Destructor Documentation
SpriteFactory()
MelloMario.Factories.SpriteFactory.SpriteFactory () [private]
Definition at line 18 of file SpriteFactory.cs.
        {
            textures = new Dictionary<string, Texture2D>();
        }
Member Function Documentation
BindLoader() [1/2]
void MelloMario.ISpriteFactory< T >.BindLoader (T loader) [inherited]
BindLoader() [2/2]
void MelloMario.Factories.SpriteFactory.BindLoader (ContentManager loader)
Definition at line 25 of file SpriteFactory.cs.
        {
            content = loader;
        }
CreateBrickSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateBrickSprite (string status)
Definition at line 207 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (status)
            {
                case "Bumped":
                    return new StaticSprite(GetTexture("BlockSheet"), 2, 0, zIndex :
      ZIndex.Level);
                case "Destroyed":
                    return new BrickPieceSprite(GetTexture("BrickPieces"));
                case "Normal":
                    return new StaticSprite(GetTexture("BlockSheet"), 2, 0, zIndex :
      ZIndex.Level);
                case "Used":
                    return new StaticSprite(GetTexture("BlockSheet"), 54, 0, zIndex :
      ZIndex.Level);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateCoinSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateCoinSprite (bool isHud = false)
Definition at line 166 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            if (isHud)
            {
                return new AnimatedSprite(GetTexture("Coin"), 4, 1, 0, 0, 1, 2, 100,
      ZIndex.Hud);
            }
            return new AnimatedSprite(GetTexture("Coin"), 4, 1, 0, 0, 1, 2);
        }
CreateFireFlowerSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateFireFlowerSprite ()
Definition at line 180 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new AnimatedSprite(GetTexture("FireFlower"), 8, 1);
        }
CreateFireSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateFireSprite ()
Definition at line 156 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new AnimatedSprite(GetTexture("Fire"), 2, 2, 0, 0, 1, 1);
        }
CreateFlagSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateFlagSprite (bool isTop)
Definition at line 262 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            if (isTop)
            {
                return new StaticSprite(GetTexture("BlockSheet"), 32, 16, zIndex :
      ZIndex.Level);
            }
            return new StaticSprite(GetTexture("BlockSheet"), 32, 18, zIndex :
      ZIndex.Level);
        }
CreateFloorSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateFloorSprite ()
Definition at line 226 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new StaticSprite(GetTexture("BlockSheet"), 0, 0, zIndex :
      ZIndex.Level);
        }
CreateGoombaSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateGoombaSprite (string status)
Definition at line 86 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (status)
            {
                case "Defeated":
                    return new StaticSprite(GetTexture("GoombaDead"));
                case "Normal":
                    return new AnimatedSprite(GetTexture("Goomba"), 2, 1);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateKoopaSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateKoopaSprite (string color, string status)
Definition at line 116 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (status)
            {
                case "DefeatedLeft":
                case "DefeatedRight":
                case "MovingShellLeft":
                case "MovingShellRight":
                    return new StaticSprite(GetTexture(color + "KoopaDead"), 0, 0, 2, 3);
                case "ShellLeft":
                case "ShellRight":
                    return new StaticSprite(GetTexture(color + "KoopaStepped"), 0, 0, 2, 3);
                case "NormalLeft":
                    return new AnimatedSprite(GetTexture(color + "KoopaLeft"), 2, 1, 0, 0, 2, 3);
                case "NormalRight":
                    return new AnimatedSprite(GetTexture(color + "KoopaRight"), 2, 1, 0, 0, 2, 3);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateMarioSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateMarioSprite (string powerUpStatus, string movementStatus, string protectionStatus, string facing)
Definition at line 40 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (protectionStatus)
            {
                case "Protected":
                    return new FlashingAnimatedSprite(
                        GetTexture(powerUpStatus + movementStatus + facing),
                        movementStatus == "Walking" ? 3 : 1,
                        1,
                        0,
                        0,
                        2,
                        powerUpStatus == "Standard" ? 2 : movementStatus == "Crouching" ? 3 : 4);
                case "Starred":
                    return new FlickingAnimatedSprite(
                        GetTexture(powerUpStatus + movementStatus + facing),
                        movementStatus == "Walking" ? 3 : 1,
                        1,
                        0,
                        0,
                        2,
                        powerUpStatus == "Standard" ? 2 : movementStatus == "Crouching" ? 3 : 4);
                case "Normal":
                    return new AnimatedSprite(
                        GetTexture(powerUpStatus + movementStatus + facing),
                        movementStatus == "Walking" ? 3 : 1,
                        1,
                        0,
                        0,
                        2,
                        powerUpStatus == "Standard" ? 2 : movementStatus == "Crouching" ? 3 : 4);
                case "Dead":
                    return new StaticSprite(GetTexture(protectionStatus), zIndex :
      ZIndex.Foreground);
                case "GameOver":
                    return new StaticSprite(GetTexture(powerUpStatus + movementStatus + facing), zIndex :
      ZIndex.Hud);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateOneUpMushroomSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateOneUpMushroomSprite ()
Definition at line 185 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new StaticSprite(GetTexture("OneUpMushroom"));
        }
CreatePipelineSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreatePipelineSprite (string type)
Definition at line 236 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (type)
            {
                case "LeftIn":
                    return new StaticSprite(GetTexture("BlockSheet"), 0, 16, zIndex :
      ZIndex.Foreground);
                case "RightIn":
                    return new StaticSprite(GetTexture("BlockSheet"), 2, 16, zIndex :
      ZIndex.Foreground);
                case "Left":
                    return new StaticSprite(GetTexture("BlockSheet"), 0, 18, zIndex :
      ZIndex.Foreground);
                case "Right":
                    return new StaticSprite(GetTexture("BlockSheet"), 2, 18, zIndex :
      ZIndex.Foreground);
                //TODO: Implement cases below
                case "TopLeftIn":
                case "BottomLeftIn":
                case "TopRightIn":
                case "BottomRightIn":
                case "Top":
                case "Bottom":
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreatePiranhaSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreatePiranhaSprite (string color)
Definition at line 139 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (color)
            {
                case "Green":
                    return new AnimatedSprite(GetTexture("Piranha"), 2, 1, 0, 0, 2, 3);
                case "Cyan":
                    return new AnimatedSprite(GetTexture("Piranha"), 2, 1, 0, 3, 2, 3);
                case "Red":
                    return new AnimatedSprite(GetTexture("Piranha"), 2, 1, 0, 6, 2, 3);
                case "Gray":
                    return new AnimatedSprite(GetTexture("Piranha"), 2, 1, 0, 9, 2, 3);
                default:
                    return null;
            }
        }
CreateQuestionSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateQuestionSprite (string status)
Definition at line 190 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (status)
            {
                case "Bumped":
                    return new AnimatedSprite(GetTexture("Question"), 3, 1, zIndex :
      ZIndex.Level);
                case "Normal":
                    return new AnimatedSprite(GetTexture("Question"), 3, 1, zIndex :
      ZIndex.Level);
                case "Used":
                    return new StaticSprite(GetTexture("BlockSheet"), 54, 0, zIndex :
      ZIndex.Level);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateSceneSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateSceneSprite (string type, ZIndex zIndex)
Definition at line 271 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (type)
            {
                case "ShortCloud":
                    return new StaticSprite(GetTexture("BlockSheet"), 0, 40, 6, 4, zIndex);
                case "ShortSmileCloud":
                    return new StaticSprite(GetTexture("BlockSheet"), 8, 42, 2, 2, zIndex);
                case "LongCloud":
                    return new StaticSprite(GetTexture("BlockSheet"), 16, 44, 8, 2, zIndex);
                case "LongSmileCloud":
                    return new StaticSprite(GetTexture("BlockSheet"), 10, 40, 6, 4, zIndex);
                case "CastleTop":
                    return new StaticSprite(GetTexture("BlockSheet"), 22, 0, 2, 2, zIndex);
                case "CastleTopSolid":
                    return new StaticSprite(GetTexture("BlockSheet"), 22, 2, 2, 2, zIndex);
                case "CastleBody":
                    return new StaticSprite(GetTexture("BlockSheet"), 26, 0, 2, 2, zIndex);
                case "CastleDoorLeft":
                    return new StaticSprite(GetTexture("BlockSheet"), 24, 0, 2, 2, zIndex);
                case "CastleDoorRight":
                    return new StaticSprite(GetTexture("BlockSheet"), 28, 0, 2, 2, zIndex);
                case "CastleDoorTop":
                    return new StaticSprite(GetTexture("BlockSheet"), 24, 2, 2, 2, zIndex);
                case "CastleDoor":
                    return new StaticSprite(GetTexture("BlockSheet"), 26, 2, 2, 2, zIndex);
                default:
                    return null;
            }
        }
CreateSplashSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateSplashSprite ()
Definition at line 35 of file SpriteFactory.cs.
        {
            return new SplashSprite();
        }
CreateStairSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateStairSprite ()
Definition at line 231 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new StaticSprite(GetTexture("BlockSheet"), 0, 2, zIndex :
      ZIndex.Level);
        }
CreateStarSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateStarSprite ()
Definition at line 161 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new AnimatedSprite(GetTexture("Star"), 4, 1);
        }
CreateSuperMushroomSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateSuperMushroomSprite ()
Definition at line 175 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new StaticSprite(GetTexture("SuperMushroom"));
        }
CreateTextSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateTextSprite (string text, float fontSize = 18f)
Definition at line 30 of file SpriteFactory.cs.
        {
            return new TextSprite(text, content.Load<SpriteFont>("Font\\text"), new Point(),
      ZIndex.Hud, fontSize);
        }
CreateThwompSprite()
 ISprite MelloMario.Factories.SpriteFactory.CreateThwompSprite (string status)
Definition at line 101 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            switch (status)
            {
                case "Defeated":
                    return new StaticSprite(GetTexture("GoombaDead"));
                case "Normal":
                    return new AnimatedSprite(GetTexture("Thwomp"), 2, 1);
                default:
                    //it should never hit this case, if it does there is an error somewhere
                    //else in the code
                    return null;
            }
        }
CreateTitle()
 ISprite MelloMario.Factories.SpriteFactory.CreateTitle (ZIndex zIndex)
Definition at line 302 of file SpriteFactory.cs.
References MelloMario.Factories.SpriteFactory.GetTexture().
        {
            return new StaticSprite(GetTexture("Title"), 0, 0, 22, 11, zIndex);
        }
GetTexture()
Texture2D MelloMario.Factories.SpriteFactory.GetTexture (string name) [private]
Definition at line 307 of file SpriteFactory.cs.
Referenced by MelloMario.Factories.SpriteFactory.CreateBrickSprite(), MelloMario.Factories.SpriteFactory.CreateCoinSprite(), MelloMario.Factories.SpriteFactory.CreateFireFlowerSprite(), MelloMario.Factories.SpriteFactory.CreateFireSprite(), MelloMario.Factories.SpriteFactory.CreateFlagSprite(), MelloMario.Factories.SpriteFactory.CreateFloorSprite(), MelloMario.Factories.SpriteFactory.CreateGoombaSprite(), MelloMario.Factories.SpriteFactory.CreateKoopaSprite(), MelloMario.Factories.SpriteFactory.CreateMarioSprite(), MelloMario.Factories.SpriteFactory.CreateOneUpMushroomSprite(), MelloMario.Factories.SpriteFactory.CreatePipelineSprite(), MelloMario.Factories.SpriteFactory.CreatePiranhaSprite(), MelloMario.Factories.SpriteFactory.CreateQuestionSprite(), MelloMario.Factories.SpriteFactory.CreateSceneSprite(), MelloMario.Factories.SpriteFactory.CreateStairSprite(), MelloMario.Factories.SpriteFactory.CreateStarSprite(), MelloMario.Factories.SpriteFactory.CreateSuperMushroomSprite(), MelloMario.Factories.SpriteFactory.CreateThwompSprite(), and MelloMario.Factories.SpriteFactory.CreateTitle().
        {
            if (!textures.ContainsKey(name))
            {
                textures.Add(name, content.Load<Texture2D>(name));
            }
            return textures[name];
        }
Member Data Documentation
content
ContentManager MelloMario.Factories.SpriteFactory.content [private]
Definition at line 16 of file SpriteFactory.cs.
textures
readonly IDictionary<string, Texture2D> MelloMario.Factories.SpriteFactory.textures [private]
Definition at line 15 of file SpriteFactory.cs.
Property Documentation
Instance
 ISpriteFactory<ContentManager> MelloMario.Factories.SpriteFactory.Instance [static], [get]
Definition at line 23 of file SpriteFactory.cs.
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.UserInterfaces.GameOver.GameOver(), MelloMario.Objects.UserInterfaces.GameStart.GameStart(), MelloMario.Objects.UserInterfaces.GameWon.GameWon(), MelloMario.Objects.UserInterfaces.HUD.HUD(), MelloMario.Game1.LoadContent(), MelloMario.Objects.UserInterfaces.GameOver.OnDraw(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Factories/ SpriteFactory.cs