MelloMario.Objects.UserInterfaces.GameOver Class Reference
Public Member Functions
 GameOver (IPlayer player)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Member Functions
override void OnUpdate (int time)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Offset (ref Rectangle rect)
void UpdateOrigin ()
Protected Attributes
 IPlayer Player
Point RelativeOrigin
Private Attributes
readonly ISprite coinSprite
readonly ISprite gameOverSprite
readonly ISprite marioSprite
readonly ISprite splashSprite
readonly ISprite textSprite
readonly ISprite textSprite2
 ISprite lifeSprite
Rectangle coinDestinationRect
Rectangle gameOverDestinationRect
Rectangle marioDestinationRect
Rectangle splashDestinationRect
Rectangle textDestinationRect
Rectangle text2DestinationRect
Rectangle lifeDestinationRect
Detailed Description
Definition at line 12 of file GameOver.cs.
Constructor & Destructor Documentation
GameOver()
MelloMario.Objects.UserInterfaces.GameOver.GameOver (IPlayer player)
Definition at line 29 of file GameOver.cs.
References MelloMario.Theming.Player.Coins, MelloMario.ISpriteFactory< T >.CreateCoinSprite(), MelloMario.ISpriteFactory< T >.CreateMarioSprite(), MelloMario.ISpriteFactory< T >.CreateSplashSprite(), MelloMario.ISpriteFactory< T >.CreateTextSprite(), MelloMario.Factories.SpriteFactory.Instance, MelloMario.Theming.Player.Score, MelloMario.Theming.Const.SCREEN_HEIGHT, and MelloMario.Theming.Const.SCREEN_WIDTH.
                                        : base(player)
        {
            splashSprite = SpriteFactory.Instance.CreateSplashSprite();
            coinSprite = SpriteFactory.Instance.CreateCoinSprite(true);
            marioSprite = SpriteFactory.Instance.CreateMarioSprite("Standard", "Standing", "GameOver", "
      Right");
            gameOverSprite = SpriteFactory.Instance.CreateTextSprite("GAME OVER");
            string text = "MARIO "
                + " WORLD TIME\n"
                + Player.Score.ToString().PadLeft(6, '0')
                + " *"
                + Player.Coins.ToString().PadLeft(2, '0')
                + " "
                + "1-1"
                + " ";
            textSprite = SpriteFactory.Instance.CreateTextSprite(text);
            textSprite2 = SpriteFactory.Instance.CreateTextSprite("WORLD");
            coinDestinationRect = new Rectangle(255, 74, 26, 30);
            gameOverDestinationRect = new Rectangle(250, 250, 80, 80);
            marioDestinationRect = new Rectangle(250, 250, 40, 40);
            splashDestinationRect = new Rectangle(0, 0, Const.SCREEN_WIDTH, Const.SCREEN_HEIGHT);
            textDestinationRect = new Rectangle(42, 42, 800, 200);
            text2DestinationRect = new Rectangle(300, 200, 80, 80);
            lifeDestinationRect = new Rectangle(350, 250, 80, 80);
            // OnUpdate(0);
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseUIObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 27 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnDraw().
        {
            OnDraw(time, spriteBatch);
        }
Offset()
void MelloMario.Objects.BaseUIObject.Offset (ref Rectangle rect) [protected], [inherited]
Definition at line 32 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            rect.Offset(Player.Camera.Viewport.Location - RelativeOrigin);
        }
OnDraw()
override void MelloMario.Objects.UserInterfaces.GameOver.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 68 of file GameOver.cs.
References MelloMario.ISpriteFactory< T >.CreateTextSprite(), MelloMario.ISprite.Draw(), MelloMario.Factories.SpriteFactory.Instance, and MelloMario.Theming.Player.Lifes.
        {
            splashSprite.Draw(time, spriteBatch, splashDestinationRect);
            textSprite.Draw(time, spriteBatch, textDestinationRect);
            coinSprite.Draw(time, spriteBatch, coinDestinationRect);
            if (Player.Lifes > 0)
            {
                textSprite2.Draw(time, spriteBatch, text2DestinationRect);
                marioSprite.Draw(time, spriteBatch, marioDestinationRect);
                lifeSprite = SpriteFactory.Instance.CreateTextSprite("* " +
      Player.Lifes);
                lifeSprite.Draw(time, spriteBatch, lifeDestinationRect);
            }
            else
            {
                gameOverSprite.Draw(time, spriteBatch, gameOverDestinationRect);
                //TODO:Move this into soundcontroller
                //SoundManager.GameOver.Play();
            }
        }
OnUpdate()
override void MelloMario.Objects.UserInterfaces.GameOver.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 56 of file GameOver.cs.
References MelloMario.Objects.BaseUIObject.Offset(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
        {
            Offset(ref textDestinationRect);
            Offset(ref text2DestinationRect);
            Offset(ref gameOverDestinationRect);
            Offset(ref splashDestinationRect);
            Offset(ref coinDestinationRect);
            Offset(ref lifeDestinationRect);
            Offset(ref marioDestinationRect);
            UpdateOrigin();
        }
Update()
void MelloMario.Objects.BaseUIObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 22 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnUpdate().
        {
            OnUpdate(time);
        }
UpdateOrigin()
void MelloMario.Objects.BaseUIObject.UpdateOrigin () [protected], [inherited]
Definition at line 37 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, MelloMario.Objects.BaseUIObject.OnDraw(), MelloMario.Objects.BaseUIObject.OnUpdate(), and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            RelativeOrigin = Player.Camera.Viewport.Location;
        }
Member Data Documentation
coinDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.coinDestinationRect [private]
Definition at line 21 of file GameOver.cs.
coinSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.coinSprite [private]
Definition at line 14 of file GameOver.cs.
gameOverDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.gameOverDestinationRect [private]
Definition at line 22 of file GameOver.cs.
gameOverSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.gameOverSprite [private]
Definition at line 15 of file GameOver.cs.
lifeDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.lifeDestinationRect [private]
Definition at line 27 of file GameOver.cs.
lifeSprite
 ISprite MelloMario.Objects.UserInterfaces.GameOver.lifeSprite [private]
Definition at line 20 of file GameOver.cs.
marioDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.marioDestinationRect [private]
Definition at line 23 of file GameOver.cs.
marioSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.marioSprite [private]
Definition at line 16 of file GameOver.cs.
Player
 IPlayer MelloMario.Objects.BaseUIObject.Player [protected], [inherited]
Definition at line 12 of file BaseUIObject.cs.
RelativeOrigin
Point MelloMario.Objects.BaseUIObject.RelativeOrigin [protected], [inherited]
Definition at line 13 of file BaseUIObject.cs.
splashDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.splashDestinationRect [private]
Definition at line 24 of file GameOver.cs.
splashSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.splashSprite [private]
Definition at line 17 of file GameOver.cs.
text2DestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.text2DestinationRect [private]
Definition at line 26 of file GameOver.cs.
textDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameOver.textDestinationRect [private]
Definition at line 25 of file GameOver.cs.
textSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.textSprite [private]
Definition at line 18 of file GameOver.cs.
textSprite2
readonly ISprite MelloMario.Objects.UserInterfaces.GameOver.textSprite2 [private]
Definition at line 19 of file GameOver.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/UserInterfaces/ GameOver.cs