MelloMario.Objects.Characters.MarioCharacter Class Reference
Public Member Functions
 MarioCharacter (IWorld world, IPlayer player, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
void Left ()
void LeftPress ()
void LeftRelease ()
void Right ()
void RightPress ()
void RightRelease ()
void Jump ()
void JumpPress ()
void JumpRelease ()
void Crouch ()
void CrouchPress ()
void CrouchRelease ()
void FireCreate ()
void SuperCreate ()
void NormalCreate ()
void Action ()
void Move (IWorld newWorld, Point newLocation)
void Remove ()
void FlagPole ()
delegate void GameOverHandler (Mario m, EventArgs e)
void OnDeath ()
void TransToGameOver ()
void UpgradeToSuper ()
void UpgradeToFire ()
void Downgrade ()
delegate void LivesHandler (BaseCollidableObject m, ScoreEventArgs e)
delegate void PointHandler (BaseCollidableObject m, ScoreEventArgs e)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum FacingMode { FacingMode.left,
 FacingMode.right
 }
enum CollisionMode {
 CollisionMode.Left,
 CollisionMode.Right,
 CollisionMode.Top,
 CollisionMode.Bottom,
 CollisionMode.InnerLeft,
 CollisionMode.InnerRight,
 CollisionMode.InnerTop,
 CollisionMode.InnerBottom
 }
enum CornerMode {
 CornerMode.Left,
 CornerMode.Right,
 CornerMode.Top,
 CornerMode.Bottom,
 CornerMode.Center
 }
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
void Teleport ()
void Reset ()
override void OnSimulation (int time)
override void OnUpdate (int time)
void RaiseSoundEvent ()
void ChangeFacing (FacingMode facing)
override void OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive)
override void OnCollideWorld (CollisionMode mode, CollisionMode modePassive)
override void OnDraw (int time, SpriteBatch spriteBatch)
void ApplyAccel (Vector2 delta)
void ApplyGravity (float gravity= Const.ACCEL_G)
void ApplyHorizontalFriction (float friction)
void ApplyVerticalFriction (float friction)
void SetHorizontalVelocity (float constVelocity)
void SetVerticalVelocity (float constVelocity)
bool Bounce (CollisionMode mode, Vector2 refVelocity, float rate=0)
void Move (Point delta)
void StopHorizontalMovement ()
void StopVerticalMovement ()
void RemoveSelf ()
void ScorePoints (int points)
void ChangeLives ()
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 FacingMode Facing
 IWorld World
Properties
bool Active [get]
 IWorld CurrentWorld [get]
 IPlayer Player [get]
Rectangle Sensing [get]
 ISoundArgs SoundEventArgs [get]
 IMarioMovementState MovementState [get, set]
 IMarioPowerUpState PowerUpState [get, set]
 IMarioProtectionState ProtectionState [get, set]
Rectangle Boundary [get]
Events
 SoundHandler SoundEvent
 GameOverHandler HandlerGameOver
 PointHandler HandlerPoints
 LivesHandler HandlerLives
Private Types
enum Animation { Animation.none,
 Animation.teleport,
 Animation.flagpole,
 Animation.dead
 }
Private Attributes
 Animation animation
int toBeTraveled
Vector2 userInput
readonly IListener< ISoundable > soundListener
Detailed Description
Definition at line 16 of file MarioCharacter.cs.
Member Enumeration Documentation
Animation
enum MelloMario.Objects.Characters.MarioCharacter.Animation [strong], [private]
Enumerator
none
teleport
flagpole
dead
Definition at line 299 of file MarioCharacter.cs.
        {
            none,
            teleport,
            flagpole,
            dead
        }
CollisionMode
enum MelloMario.Objects.BaseCollidableObject.CollisionMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
InnerLeft
InnerRight
InnerTop
InnerBottom
Definition at line 266 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            InnerLeft,
            InnerRight,
            InnerTop,
            InnerBottom
        }
CornerMode
enum MelloMario.Objects.BaseCollidableObject.CornerMode [strong], [protected], [inherited]
Enumerator
Left
Right
Top
Bottom
Center
Definition at line 278 of file BaseCollidableObject.cs.
        {
            Left,
            Right,
            Top,
            Bottom,
            Center
        }
FacingMode
enum MelloMario.Objects.BasePhysicalObject.FacingMode [strong], [protected], [inherited]
Enumerator
left
right
Definition at line 203 of file BasePhysicalObject.cs.
        {
            left,
            right
        }
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected], [inherited]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected], [inherited]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
MarioCharacter()
MelloMario.Objects.Characters.MarioCharacter.MarioCharacter (IWorld world, IPlayer player, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Definition at line 26 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Active, and MelloMario.Objects.Characters.MarioCharacter.soundListener.
                                                 : base(
            world,
            location,
            listener,
            soundListener)
        {
            this.soundListener = soundListener;
            Player = player;
        }
Member Function Documentation
Action()
void MelloMario.Objects.Characters.MarioCharacter.Action ()
Implements MelloMario.ICharacter .
Definition at line 223 of file MarioCharacter.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), and MelloMario.Objects.Characters.Mario.SoundEventArgs.
        {
            if (animation != Animation.none)
            {
                return;
            }
            if (PowerUpState is Fire)
            {
                SoundEventArgs.SetMethodCalled();
                new FireBall(World, Boundary.Location, null, soundListener);
            }
        }
ApplyAccel()
void MelloMario.Objects.BasePhysicalObject.ApplyAccel (Vector2 delta) [protected], [inherited]
Definition at line 33 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.ApplyGravity(), and MelloMario.Objects.Characters.MarioCharacter.OnUpdate().
        {
            accel += delta;
        }
ApplyGravity()
void MelloMario.Objects.BasePhysicalObject.ApplyGravity (float gravity = Const.ACCEL_G) [protected], [inherited]
Definition at line 38 of file BasePhysicalObject.cs.
References MelloMario.Objects.BasePhysicalObject.ApplyAccel().
Referenced by MelloMario.Objects.Enemies.Thwomp.OnSimulation(), MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), MelloMario.Objects.Items.SuperMushroom.OnSimulation(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            ApplyAccel(new Vector2(0, gravity));
        }
ApplyHorizontalFriction()
void MelloMario.Objects.BasePhysicalObject.ApplyHorizontalFriction (float friction) [protected], [inherited]
Definition at line 43 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Characters.Mario.OnCollision(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            if (frictionalAccel.X < friction)
            {
                frictionalAccel.X = friction;
            }
        }
ApplyVerticalFriction()
void MelloMario.Objects.BasePhysicalObject.ApplyVerticalFriction (float friction) [protected], [inherited]
Definition at line 51 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Items.Star.OnCollision(), and MelloMario.Objects.Characters.Mario.OnSimulation().
        {
            if (frictionalAccel.Y < friction)
            {
                frictionalAccel.Y = friction;
            }
        }
Bounce()
bool MelloMario.Objects.BasePhysicalObject.Bounce (CollisionMode mode, Vector2 refVelocity, float rate = 0) [protected], [inherited]
Definition at line 69 of file BasePhysicalObject.cs.
References MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Characters.Mario.OnCollideWorld(), MelloMario.Objects.Enemies.Thwomp.OnCollision(), MelloMario.Objects.Enemies.Goomba.OnCollision(), MelloMario.Objects.Items.OneUpMushroom.OnCollision(), MelloMario.Objects.Items.Star.OnCollision(), MelloMario.Objects.Enemies.Koopa.OnCollision(), MelloMario.Objects.Items.SuperMushroom.OnCollision(), and MelloMario.Objects.Characters.Mario.OnCollision().
        {
            switch (mode)
            {
                case CollisionMode.Left:
                case CollisionMode.InnerLeft:
                    if (velocity.X < refVelocity.X)
                    {
                        // movement.X = 0;
                        velocity.X = refVelocity.X + (refVelocity.X - velocity.X) * rate;
                        StopHorizontalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Right:
                case CollisionMode.InnerRight:
                    if (velocity.X > refVelocity.X)
                    {
                        // movement.X = 0;
                        velocity.X = refVelocity.X + (refVelocity.X - velocity.X) * rate;
                        StopHorizontalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Top:
                case CollisionMode.InnerTop:
                    if (velocity.Y < refVelocity.Y)
                    {
                        // movement.Y = 0;
                        velocity.Y = refVelocity.Y + (refVelocity.Y - velocity.Y) * rate;
                        StopVerticalMovement();
                        return true;
                    }
                    return false;
                case CollisionMode.Bottom:
                case CollisionMode.InnerBottom:
                    if (velocity.Y > refVelocity.Y)
                    {
                        // movement.Y = 0;
                        velocity.Y = refVelocity.Y + (refVelocity.Y - velocity.Y) * rate;
                        StopVerticalMovement();
                        return true;
                    }
                    return false;
                default:
                    // never reach
                    return false;
            }
        }
ChangeFacing()
void MelloMario.Objects.Characters.Mario.ChangeFacing (FacingMode facing) [protected], [inherited]
Definition at line 125 of file Mario.cs.
References MelloMario.Objects.BasePhysicalObject.Facing, and MelloMario.Objects.Characters.Mario.UpdateSprite().
Referenced by MelloMario.Objects.Characters.MarioCharacter.Left(), and MelloMario.Objects.Characters.MarioCharacter.Right().
        {
            Facing = facing;
            // Notice: The effect should be the same as changing state
            UpdateSprite();
        }
ChangeLives()
void MelloMario.Objects.BaseCollidableObject.ChangeLives () [protected], [inherited]
Definition at line 256 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.OneUpMushroom.Collect(), and MelloMario.Objects.Blocks.Flag.OnCollision().
        {
            HandlerLives?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = 1
                });
        }
Crouch()
void MelloMario.Objects.Characters.MarioCharacter.Crouch ()
Implements MelloMario.ICharacter .
Definition at line 173 of file MarioCharacter.cs.
References MelloMario.IMarioMovementState.Crouch(), and MelloMario.Objects.Characters.Mario.MovementState.
Referenced by MelloMario.Objects.Characters.MarioCharacter.CrouchPress().
        {
            if (animation == Animation.none)
            {
                MovementState.Crouch();
            }
        }
CrouchPress()
void MelloMario.Objects.Characters.MarioCharacter.CrouchPress ()
Implements MelloMario.ICharacter .
Definition at line 181 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Crouch().
        {
            if (animation == Animation.none)
            {
                Crouch();
            }
        }
CrouchRelease()
void MelloMario.Objects.Characters.MarioCharacter.CrouchRelease ()
Implements MelloMario.ICharacter .
Definition at line 189 of file MarioCharacter.cs.
References MelloMario.IMarioMovementState.Idle(), and MelloMario.Objects.Characters.Mario.MovementState.
        {
            if (animation == Animation.none)
            {
                MovementState.Idle();
            }
        }
Downgrade()
void MelloMario.Objects.Characters.Mario.Downgrade () [inherited]
Definition at line 396 of file Mario.cs.
References MelloMario.IMarioPowerUpState.Downgrade(), MelloMario.Objects.Characters.Mario.PowerUpState, and MelloMario.IMarioProtectionState.Protect().
Referenced by MelloMario.Objects.Characters.Mario.OnCollision().
        {
            if (protectionState is ProtectionStates.Normal)
            {
                PowerUpState.Downgrade();
            }
            if (protectionState is ProtectionStates.Normal)
            {
                protectionState.Protect();
            }
        }
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
FireCreate()
void MelloMario.Objects.Characters.MarioCharacter.FireCreate ()
Implements MelloMario.ICharacter .
Definition at line 197 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.Characters.Mario.SoundEventArgs, and MelloMario.IMarioPowerUpState.UpgradeToFire().
        {
            SoundEventArgs.SetMethodCalled();
            PowerUpState.UpgradeToFire();
        }
FlagPole()
void MelloMario.Objects.Characters.MarioCharacter.FlagPole ()
Definition at line 256 of file MarioCharacter.cs.
        {
            animation = Animation.flagpole;
        }
GameOverHandler()
delegate void MelloMario.Objects.Characters.Mario.GameOverHandler (Mario m, EventArgs e) [inherited]
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected], [inherited]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
Jump()
void MelloMario.Objects.Characters.MarioCharacter.Jump ()
Implements MelloMario.ICharacter .
Definition at line 140 of file MarioCharacter.cs.
References MelloMario.Theming.Const.ACCEL_G, MelloMario.Theming.Const.ACCEL_INPUT_Y, MelloMario.Objects.Characters.MovementStates.Jumping.Finished, MelloMario.IMarioMovementState.Jump(), MelloMario.Objects.Characters.Mario.MovementState, MelloMario.ISoundArgs.SetMethodCalled(), and MelloMario.Objects.Characters.Mario.SoundEventArgs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.JumpPress().
        {
            if (animation == Animation.none)
            {
                MovementState.Jump();
                if (MovementState is Jumping jumping && !jumping.Finished)
                {
                    SoundEventArgs.SetMethodCalled();
                    userInput.Y -= Const.ACCEL_INPUT_Y + Const.ACCEL_G;
                }
            }
        }
JumpPress()
void MelloMario.Objects.Characters.MarioCharacter.JumpPress ()
Implements MelloMario.ICharacter .
Definition at line 154 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Jump().
        {
            if (animation == Animation.none)
            {
                Jump();
            }
        }
JumpRelease()
void MelloMario.Objects.Characters.MarioCharacter.JumpRelease ()
Implements MelloMario.ICharacter .
Definition at line 162 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.Mario.MovementState.
        {
            if (animation == Animation.none)
            {
                if (MovementState is Jumping jumping)
                {
                    jumping.Finished = true;
                }
            }
        }
Left()
void MelloMario.Objects.Characters.MarioCharacter.Left ()
Implements MelloMario.ICharacter .
Definition at line 72 of file MarioCharacter.cs.
References MelloMario.Theming.Const.ACCEL_INPUT_X, MelloMario.Objects.Characters.Mario.ChangeFacing(), MelloMario.Objects.BasePhysicalObject.Facing, MelloMario.Objects.Characters.Mario.MovementState, and MelloMario.IMarioMovementState.Walk().
Referenced by MelloMario.Objects.Characters.MarioCharacter.LeftPress().
        {
            if (animation == Animation.none)
            {
                MovementState.Walk();
                if (Facing == FacingMode.right)
                {
                    ChangeFacing(FacingMode.left);
                }
                if (!(MovementState is Crouching))
                {
                    userInput.X -= Const.ACCEL_INPUT_X;
                }
            }
        }
LeftPress()
void MelloMario.Objects.Characters.MarioCharacter.LeftPress ()
Implements MelloMario.ICharacter .
Definition at line 90 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Left().
        {
            if (animation == Animation.none)
            {
                Left();
            }
        }
LeftRelease()
void MelloMario.Objects.Characters.MarioCharacter.LeftRelease ()
Implements MelloMario.ICharacter .
Definition at line 98 of file MarioCharacter.cs.
References MelloMario.IMarioMovementState.Idle(), and MelloMario.Objects.Characters.Mario.MovementState.
        {
            if (animation == Animation.none)
            {
                MovementState.Idle();
            }
        }
LivesHandler()
delegate void MelloMario.Objects.BaseCollidableObject.LivesHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
Move() [1/2]
void MelloMario.Objects.BaseCollidableObject.Move (Point delta) [protected], [inherited]
Definition at line 166 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Move().
Referenced by MelloMario.Objects.Blocks.Question.BumpMove(), MelloMario.Objects.Blocks.Brick.BumpMove(), MelloMario.Objects.BasePhysicalObject.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Items.FireFlower.UnveilMove(), MelloMario.Objects.Items.Coin.UnveilMove(), MelloMario.Objects.Items.OneUpMushroom.UnveilMove(), MelloMario.Objects.Items.Star.UnveilMove(), and MelloMario.Objects.Items.SuperMushroom.UnveilMove().
        {
            movement += delta;
            World.Move(this);
        }
Move() [2/2]
void MelloMario.Objects.Characters.MarioCharacter.Move (IWorld newWorld, Point newLocation)
Implements MelloMario.ICharacter .
Definition at line 236 of file MarioCharacter.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Add(), MelloMario.Objects.BaseGameObject.Relocate(), and MelloMario.Containers.BaseContainer< Key, Value >.Remove().
Referenced by MelloMario.Objects.Characters.MarioCharacter.OnSimulation().
        {
            World.Remove(this);
            World = newWorld;
            World.Add(this);
            Relocate(newLocation);
        }
NormalCreate()
void MelloMario.Objects.Characters.MarioCharacter.NormalCreate ()
Implements MelloMario.ICharacter .
Definition at line 209 of file MarioCharacter.cs.
References MelloMario.IMarioPowerUpState.Downgrade(), MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), and MelloMario.Objects.Characters.Mario.SoundEventArgs.
        {
            if (PowerUpState != null || PowerUpState is Standard)
            {
                return;
            }
            SoundEventArgs.SetMethodCalled();
            PowerUpState.Downgrade();
            if (PowerUpState is Fire)
            {
                PowerUpState.Downgrade();
            }
        }
OnCollideWorld()
override void MelloMario.Objects.Characters.Mario.OnCollideWorld (CollisionMode mode, CollisionMode modePassive) [protected], [virtual], [inherited]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 356 of file Mario.cs.
References MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.Characters.Mario.ProtectionState.
        {
            if (!(protectionState is Dead))
            {
                Bounce(mode, new Vector2());
                if (mode == CollisionMode.InnerBottom)
                {
                    ProtectionState = new Dead(this);
                }
            }
        }
OnCollision()
override void MelloMario.Objects.Characters.Mario.OnCollision (IGameObject target, CollisionMode mode, CollisionMode modePassive, CornerMode corner, CornerMode cornerPassive) [protected], [virtual], [inherited]
Implements MelloMario.Objects.BaseCollidableObject .
Definition at line 151 of file Mario.cs.
References MelloMario.Theming.Const.ACCEL_F_GROUND, MelloMario.Objects.BasePhysicalObject.ApplyHorizontalFriction(), MelloMario.Objects.BasePhysicalObject.Bounce(), MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Objects.Blocks.Question.Bump(), MelloMario.Objects.Blocks.Brick.Bump(), MelloMario.Objects.Characters.Mario.Downgrade(), MelloMario.Theming.Database.IsEntrance(), MelloMario.IMarioMovementState.Land(), MelloMario.Objects.Characters.Mario.MovementState, MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.Objects.Characters.Mario.ProtectionState, MelloMario.IMarioProtectionState.Star(), MelloMario.Objects.Blocks.Question.State, MelloMario.Objects.Blocks.Brick.State, MelloMario.Objects.Characters.Mario.UpgradeToFire(), and MelloMario.Objects.Characters.Mario.UpgradeToSuper().
        {
            if (ProtectionState is Dead)
            {
                return;
            }
            switch (target.GetType().Name)
            {
                //TODO: add cases when collision mode is OutLeftTop/OutRightTop that Mario will be squeezed
       to side of the brick
                //NOTE: if collision mode is OutLeftTop/OutRightTop, be careful that if there are blocks
       surronding the target, no squeeze will happen!!
                case "Brick":
                case "Question":
                    bool isHidden;
                    bool isBumping;
                    Brick brick = target as Brick;
                    Question question = target as Question;
                    if (brick != null)
                    {
                        if (brick.State is Destroyed)
                        {
                            break;
                        }
                        isHidden = brick.State is Hidden;
                        isBumping = brick.State is Bumped;
                    }
                    else if (question != null)
                    {
                        isHidden = question.State is Blocks.QuestionStates.Hidden;
                        isBumping = question.State is Blocks.QuestionStates.Bumped;
                    }
                    else
                    {
                        // never reach
                        isHidden = false;
                        isBumping = false;
                    }
                    if (mode == CollisionMode.Top)
                    {
                        bool bumped = Bounce(mode, new Vector2(), 1);
                        if (isBumping)
                        {
                            //Move(new Point(0, 1));
                        }
                        else if (bumped)
                        {
                            if (brick != null)
                            {
                                brick.Bump(this);
                            }
                            else if (question != null)
                            {
                                question.Bump(this);
                            }
                        }
                    }
                    else if (!isHidden)
                    {
                        goto case "Stair";
                    }
                    break;
                case "Pipeline":
                    if (MovementState is Crouching && Database.IsEntrance((Pipeline) target))
                    {
                        string type = (target as Pipeline).Type;
                        if (type == "LeftIn")
                        {
                            if (Boundary.Center.X > target.Boundary.Center.X)
                            {
                                Bounce(CollisionMode.Left, new Vector2());
                                Bounce(CollisionMode.Right, new Vector2());
                            }
                            else
                            {
                                goto case "Floor";
                            }
                        }
                        else if (type == "RightIn")
                        {
                            if (Boundary.Center.X < target.Boundary.Center.X)
                            {
                                Bounce(CollisionMode.Left, new Vector2());
                                Bounce(CollisionMode.Right, new Vector2());
                            }
                            else
                            {
                                goto case "Floor";
                            }
                        }
                    }
                    else
                    {
                        goto case "Floor";
                    }
                    break;
                case "CompressedBlock":
                case "Floor":
                case "Stair":
                case "Flag":
                    Bounce(mode, new Vector2());
                    if (mode == CollisionMode.Bottom)
                    {
                        ApplyHorizontalFriction(Const.ACCEL_F_GROUND);
                        MovementState.Land();
                    }
                    break;
                case "Goomba":
                    if (target is Goomba goomba && mode != CollisionMode.Bottom)
                    {
                        if (goomba.State is Enemies.GoombaStates.Normal && !(
      ProtectionState is Starred))
                        {
                            Downgrade();
                        }
                    }
                    else if (!(protectionState is Starred))
                    {
                        Bounce(mode, new Vector2(), 0.5f);
                    }
                    break;
                case "Koopa":
                    //if (target is Koopa koopa && mode != CollisionMode.Bottom)
                    //{
                    // if (koopa.State is Objects.Enemies.KoopaStates.Normal && !(ProtectionState is
       Starred))
                    // {
                    // Downgrade();
                    // }
                    // else if (koopa.State is Objects.Enemies.KoopaStates.MovingShell &&
       !(ProtectionState is Starred))
                    // {
                    // if(koopa.Facing is FacingMode.right && (mode is CollisionMode.InnerRight ||
       mode is CollisionMode.Left))
                    // Downgrade();
                    // if (koopa.Facing is FacingMode.left && (mode is CollisionMode.InnerLeft ||
       mode is CollisionMode.Right))
                    // Downgrade();
                    // }
                    //}
                    if (target is Koopa)
                    {
                        if (!(ProtectionState is Starred))
                        {
                            if (mode is CollisionMode.Bottom)
                            {
                                if (corner is CornerMode.Right)
                                {
                                    Bounce(mode, new Vector2(1f, -5f), 1f);
                                }
                                else if (corner is CornerMode.Left)
                                {
                                    Bounce(mode, new Vector2(-1f, -5f), 1f);
                                }
                                else
                                {
                                    Bounce(mode, new Vector2(0, -5f), 1f);
                                }
                            }
                            else if (mode is CollisionMode.Left || mode is
      CollisionMode.Right)
                            {
                                Bounce(mode, new Vector2(), -0.5f);
                            }
                        }
                    }
                    //else if (!(protectionState is Starred))
                    //{
                    // Bounce(mode, new Vector2(0, -5f), 1f);
                    //}
                    break;
                case "FireFlower":
                    if (((FireFlower) target).State is Items.FireFlowerStates.Normal)
                    {
                        UpgradeToFire();
                    }
                    break;
                case "Star":
                    if (((Star) target).State is Items.StarStates.Normal)
                    {
                        ProtectionState.Star();
                    }
                    break;
                case "SuperMushroom":
                    if (((SuperMushroom) target).State is Items.SuperMushroomStates.Normal &&
      PowerUpState is Standard)
                    {
                        UpgradeToSuper();
                    }
                    break;
                case "Piranha":
                    if (!(ProtectionState is Starred))
                    {
                        if (!(((Piranha) target).State is Enemies.PiranhaStates.Hidden))
                        {
                            Downgrade();
                        }
                    }
                    break;
            }
        }
OnDeath()
void MelloMario.Objects.Characters.Mario.OnDeath () [inherited]
Definition at line 368 of file Mario.cs.
References MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.BasePhysicalObject.SetVerticalVelocity(), and MelloMario.Objects.Characters.Mario.SoundEventArgs.
Referenced by MelloMario.Objects.Characters.ProtectionStates.Dead.Dead().
        {
            SoundEventArgs.SetMethodCalled();
            SetVerticalVelocity(-20);
        }
OnDraw()
override void MelloMario.Objects.Characters.Mario.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual], [inherited]
Implements MelloMario.Objects.BaseGameObject .
Definition at line 380 of file Mario.cs.
        {
        }
OnSimulation()
override void MelloMario.Objects.Characters.MarioCharacter.OnSimulation (int time) [protected], [virtual]
Reimplemented from MelloMario.Objects.Characters.Mario .
Definition at line 266 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Move().
        {
            if (animation == Animation.teleport)
            {
                Move(new Point(0, 2));
                toBeTraveled -= 2;
                if (toBeTraveled <= 0)
                {
                    animation = Animation.none;
                }
            }
            base.OnSimulation(time);
        }
OnUpdate()
override void MelloMario.Objects.Characters.MarioCharacter.OnUpdate (int time) [protected], [virtual]
Reimplemented from MelloMario.Objects.Characters.Mario .
Definition at line 281 of file MarioCharacter.cs.
References MelloMario.Objects.BasePhysicalObject.ApplyAccel(), and MelloMario.Objects.Characters.Mario.ProtectionState.
        {
            if (ProtectionState is Dead)
            {
                animation = Animation.dead;
            }
            if (animation == Animation.none)
            {
                ApplyAccel(userInput);
                userInput.X = 0;
                userInput.Y = 0;
            }
            base.OnUpdate(time);
        }
PointHandler()
delegate void MelloMario.Objects.BaseCollidableObject.PointHandler (BaseCollidableObject m, ScoreEventArgs e) [inherited]
RaiseSoundEvent()
void MelloMario.Objects.Characters.Mario.RaiseSoundEvent () [protected], [inherited]
Definition at line 34 of file Mario.cs.
References MelloMario.Objects.Characters.Mario.SoundEventArgs.
        {
            SoundEvent?.Invoke(this, SoundEventArgs);
        }
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected], [inherited]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
Remove()
void MelloMario.Objects.Characters.MarioCharacter.Remove ()
Implements MelloMario.ICharacter .
Definition at line 244 of file MarioCharacter.cs.
References MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            RemoveSelf();
        }
RemoveSelf()
void MelloMario.Objects.BaseCollidableObject.RemoveSelf () [protected], [inherited]
Definition at line 183 of file BaseCollidableObject.cs.
References MelloMario.Containers.BaseContainer< Key, Value >.Remove(), MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement(), and MelloMario.Objects.BaseCollidableObject.StopVerticalMovement().
Referenced by MelloMario.Objects.Items.Coin.Coin(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.OneUpMushroom.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Objects.Blocks.Brick.Remove(), MelloMario.Objects.Characters.MarioCharacter.Remove(), MelloMario.Objects.Items.Star.Star(), and MelloMario.Objects.Items.SuperMushroom.SuperMushroom().
        {
            StopHorizontalMovement();
            StopVerticalMovement();
            World.Remove(this);
        }
Reset()
void MelloMario.Objects.Characters.MarioCharacter.Reset () [protected]
Definition at line 261 of file MarioCharacter.cs.
        {
            animation = Animation.none;
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected], [inherited]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
Right()
void MelloMario.Objects.Characters.MarioCharacter.Right ()
Implements MelloMario.ICharacter .
Definition at line 106 of file MarioCharacter.cs.
References MelloMario.Theming.Const.ACCEL_INPUT_X, MelloMario.Objects.Characters.Mario.ChangeFacing(), MelloMario.Objects.BasePhysicalObject.Facing, MelloMario.Objects.Characters.Mario.MovementState, and MelloMario.IMarioMovementState.Walk().
Referenced by MelloMario.Objects.Characters.MarioCharacter.RightPress().
        {
            if (animation == Animation.none)
            {
                MovementState.Walk();
                if (Facing == FacingMode.left)
                {
                    ChangeFacing(FacingMode.right);
                }
                if (!(MovementState is Crouching))
                {
                    userInput.X += Const.ACCEL_INPUT_X;
                }
            }
        }
RightPress()
void MelloMario.Objects.Characters.MarioCharacter.RightPress ()
Implements MelloMario.ICharacter .
Definition at line 124 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.MarioCharacter.Right().
        {
            if (animation == Animation.none)
            {
                Right();
            }
        }
RightRelease()
void MelloMario.Objects.Characters.MarioCharacter.RightRelease ()
Implements MelloMario.ICharacter .
Definition at line 132 of file MarioCharacter.cs.
References MelloMario.IMarioMovementState.Idle(), and MelloMario.Objects.Characters.Mario.MovementState.
        {
            if (animation == Animation.none)
            {
                MovementState.Idle();
            }
        }
ScorePoints()
void MelloMario.Objects.BaseCollidableObject.ScorePoints (int points) [protected], [inherited]
Definition at line 246 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Koopa.JumpOn(), MelloMario.Objects.Blocks.Flag.OnCollision(), and MelloMario.Objects.Blocks.Brick.OnDestroy().
        {
            HandlerPoints?.Invoke(
                this,
                new ScoreEventArgs
                {
                    Points = points
                });
        }
SetHorizontalVelocity()
void MelloMario.Objects.BasePhysicalObject.SetHorizontalVelocity (float constVelocity) [protected], [inherited]
Definition at line 59 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), and MelloMario.Objects.Items.SuperMushroom.OnSimulation().
        {
            velocity.X = constVelocity;
        }
SetVerticalVelocity()
void MelloMario.Objects.BasePhysicalObject.SetVerticalVelocity (float constVelocity) [protected], [inherited]
Definition at line 64 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Characters.Mario.OnDeath(), MelloMario.Objects.Enemies.Piranha.OnSimulation(), and MelloMario.Objects.Enemies.Thwomp.OnSimulation().
        {
            velocity.Y = constVelocity;
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected], [inherited]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
StopHorizontalMovement()
void MelloMario.Objects.BaseCollidableObject.StopHorizontalMovement () [protected], [inherited]
Definition at line 173 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.X = 0;
        }
StopVerticalMovement()
void MelloMario.Objects.BaseCollidableObject.StopVerticalMovement () [protected], [inherited]
Definition at line 178 of file BaseCollidableObject.cs.
Referenced by MelloMario.Objects.BasePhysicalObject.Bounce(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            movement.Y = 0;
        }
SuperCreate()
void MelloMario.Objects.Characters.MarioCharacter.SuperCreate ()
Implements MelloMario.ICharacter .
Definition at line 203 of file MarioCharacter.cs.
References MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.Characters.Mario.SoundEventArgs, and MelloMario.IMarioPowerUpState.UpgradeToSuper().
        {
            SoundEventArgs.SetMethodCalled();
            PowerUpState.UpgradeToSuper();
        }
Teleport()
void MelloMario.Objects.Characters.MarioCharacter.Teleport () [protected]
Definition at line 249 of file MarioCharacter.cs.
References MelloMario.Objects.BaseGameObject.Boundary.
        {
            animation = Animation.teleport;
            toBeTraveled = Boundary.Height;
            // TODO: initialize
        }
TransToGameOver()
void MelloMario.Objects.Characters.Mario.TransToGameOver () [inherited]
Definition at line 374 of file Mario.cs.
        {
            eventInfo = null;
            HandlerGameOver?.Invoke(this, eventInfo);
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
UpgradeToFire()
void MelloMario.Objects.Characters.Mario.UpgradeToFire () [inherited]
Definition at line 390 of file Mario.cs.
References MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.Characters.Mario.SoundEventArgs, and MelloMario.IMarioPowerUpState.UpgradeToFire().
Referenced by MelloMario.Objects.Characters.Mario.OnCollision().
        {
            SoundEventArgs.SetMethodCalled();
            PowerUpState.UpgradeToFire();
        }
UpgradeToSuper()
void MelloMario.Objects.Characters.Mario.UpgradeToSuper () [inherited]
Definition at line 384 of file Mario.cs.
References MelloMario.Objects.Characters.Mario.PowerUpState, MelloMario.ISoundArgs.SetMethodCalled(), MelloMario.Objects.Characters.Mario.SoundEventArgs, and MelloMario.IMarioPowerUpState.UpgradeToSuper().
Referenced by MelloMario.Objects.Characters.Mario.OnCollision().
        {
            SoundEventArgs.SetMethodCalled();
            PowerUpState.UpgradeToSuper();
        }
Member Data Documentation
animation
 Animation MelloMario.Objects.Characters.MarioCharacter.animation [private]
Definition at line 18 of file MarioCharacter.cs.
Facing
 FacingMode MelloMario.Objects.BasePhysicalObject.Facing [protected], [inherited]
Definition at line 15 of file BasePhysicalObject.cs.
Referenced by MelloMario.Objects.Enemies.Koopa.ChangeFacing(), MelloMario.Objects.Characters.Mario.ChangeFacing(), MelloMario.Objects.Enemies.Goomba.ChangeFacing(), MelloMario.Objects.Enemies.Thwomp.ChangeFacing(), MelloMario.Objects.Characters.MarioCharacter.Left(), MelloMario.Objects.Items.OneUpMushroom.OnCollision(), MelloMario.Objects.Items.Star.OnCollision(), MelloMario.Objects.Items.SuperMushroom.OnCollision(), MelloMario.Objects.Enemies.Thwomp.OnSimulation(), MelloMario.Objects.Enemies.Goomba.OnSimulation(), MelloMario.Objects.Items.OneUpMushroom.OnSimulation(), MelloMario.Objects.Items.Star.OnSimulation(), MelloMario.Objects.Enemies.Koopa.OnSimulation(), MelloMario.Objects.Items.SuperMushroom.OnSimulation(), MelloMario.Objects.Enemies.Koopa.Pushed(), MelloMario.Objects.Characters.MarioCharacter.Right(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
soundListener
readonly IListener< ISoundable> MelloMario.Objects.Characters.MarioCharacter.soundListener [private]
Definition at line 24 of file MarioCharacter.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.MarioCharacter().
toBeTraveled
int MelloMario.Objects.Characters.MarioCharacter.toBeTraveled [private]
Definition at line 20 of file MarioCharacter.cs.
userInput
Vector2 MelloMario.Objects.Characters.MarioCharacter.userInput [private]
Definition at line 22 of file MarioCharacter.cs.
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected], [inherited]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Active
bool MelloMario.Objects.Characters.MarioCharacter.Active [get]
Definition at line 42 of file MarioCharacter.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.MarioCharacter().
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get], [inherited]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
CurrentWorld
 IWorld MelloMario.Objects.Characters.MarioCharacter.CurrentWorld [get]
Definition at line 50 of file MarioCharacter.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdateBGM().
MovementState
 IMarioMovementState MelloMario.Objects.Characters.Mario.MovementState [get], [set], [inherited]
Definition at line 60 of file Mario.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Crouch(), MelloMario.Objects.Characters.MarioCharacter.CrouchRelease(), MelloMario.Objects.Characters.MarioCharacter.Jump(), MelloMario.Objects.Characters.MovementStates.Jumping.Jumping(), MelloMario.Objects.Characters.MarioCharacter.JumpRelease(), MelloMario.Objects.Characters.MarioCharacter.Left(), MelloMario.Objects.Characters.MarioCharacter.LeftRelease(), MelloMario.Objects.Characters.Mario.Mario(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.Characters.MarioCharacter.Right(), and MelloMario.Objects.Characters.MarioCharacter.RightRelease().
Player
 IPlayer MelloMario.Objects.Characters.MarioCharacter.Player [get]
Definition at line 57 of file MarioCharacter.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdateBGM().
PowerUpState
 IMarioPowerUpState MelloMario.Objects.Characters.Mario.PowerUpState [get], [set], [inherited]
Definition at line 73 of file Mario.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.Blocks.BrickStates.Normal.Bump(), MelloMario.Objects.Blocks.BrickStates.Hidden.Bump(), MelloMario.Objects.Characters.Mario.Downgrade(), MelloMario.Objects.Characters.MarioCharacter.FireCreate(), MelloMario.Sounds.SoundEffectListener.MarioSoundEffect(), MelloMario.Objects.Characters.MarioCharacter.NormalCreate(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.Characters.MarioCharacter.SuperCreate(), MelloMario.Objects.Characters.Mario.UpgradeToFire(), and MelloMario.Objects.Characters.Mario.UpgradeToSuper().
ProtectionState
 IMarioProtectionState MelloMario.Objects.Characters.Mario.ProtectionState [get], [set], [inherited]
Definition at line 86 of file Mario.cs.
Referenced by MelloMario.Objects.Characters.Mario.OnCollideWorld(), MelloMario.Objects.Enemies.Thwomp.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.Characters.MarioCharacter.OnUpdate(), and MelloMario.Sounds.BGMManager.UpdateBGM().
Sensing
Rectangle MelloMario.Objects.Characters.MarioCharacter.Sensing [get]
Definition at line 60 of file MarioCharacter.cs.
SoundEventArgs
 ISoundArgs MelloMario.Objects.Characters.Mario.SoundEventArgs [get], [inherited]
Definition at line 31 of file Mario.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.Characters.MarioCharacter.FireCreate(), MelloMario.Objects.Characters.MarioCharacter.Jump(), MelloMario.Objects.Characters.Mario.Mario(), MelloMario.Objects.Characters.MarioCharacter.NormalCreate(), MelloMario.Objects.Characters.Mario.OnDeath(), MelloMario.Objects.Characters.Mario.OnSimulation(), MelloMario.Objects.Characters.Mario.RaiseSoundEvent(), MelloMario.Objects.Characters.MarioCharacter.SuperCreate(), MelloMario.Objects.Characters.Mario.UpgradeToFire(), and MelloMario.Objects.Characters.Mario.UpgradeToSuper().
Event Documentation
HandlerGameOver
 GameOverHandler MelloMario.Objects.Characters.Mario.HandlerGameOver [inherited]
Definition at line 98 of file Mario.cs.
Referenced by MelloMario.Theming.ScoreListener.Subscribe().
HandlerLives
 LivesHandler MelloMario.Objects.BaseCollidableObject.HandlerLives [inherited]
Definition at line 32 of file BaseCollidableObject.cs.
HandlerPoints
 PointHandler MelloMario.Objects.BaseCollidableObject.HandlerPoints [inherited]
Definition at line 31 of file BaseCollidableObject.cs.
Referenced by MelloMario.Theming.ScoreListener.Subscribe().
SoundEvent
 SoundHandler MelloMario.Objects.Characters.Mario.SoundEvent [inherited]
Definition at line 32 of file Mario.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Characters/ MarioCharacter.cs