MelloMario.Graphics.Sprites.AnimatedSprite Class Reference
Public Member Functions
 AnimatedSprite (Texture2D texture, int columns, int rows, int x=0, int y=0, int width=2, int height=2, int interval= Const.ANIMATION_INTERVAL, ZIndex zIndex= ZIndex.Item)
void Draw (int time, SpriteBatch spriteBatch, Rectangle destination)
Protected Member Functions
override void OnAnimate (int time)
virtual void OnFrame ()
void ChangeSource (Point location)
void ChangeColor (Color newColor)
override void OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination)
void Toggle ()
Properties
float LayerDepth [get]
Point PixelSize [get]
Private Member Functions
void UpdateSourceRectangle ()
Private Attributes
readonly int columns
readonly int interval
readonly int rows
int elapsed
int frames
Rectangle refSource
Detailed Description
Definition at line 13 of file AnimatedSprite.cs.
Constructor & Destructor Documentation
AnimatedSprite()
MelloMario.Graphics.Sprites.AnimatedSprite.AnimatedSprite (Texture2D texture, int columns, int rows, int x = 0, int y = 0, int width = 2, int height = 2, int interval = Const.ANIMATION_INTERVAL, ZIndex zIndex = ZIndex.Item)
Definition at line 23 of file AnimatedSprite.cs.
References MelloMario.Graphics.Sprites.AnimatedSprite.columns, MelloMario.Graphics.Sprites.AnimatedSprite.interval, MelloMario.Graphics.Sprites.AnimatedSprite.rows, and MelloMario.Theming.Const.TEXTURE_GRID.
                                         : base(
            texture,
            new Rectangle(
                x * Const.TEXTURE_GRID,
                y * Const.TEXTURE_GRID,
                width * Const.TEXTURE_GRID,
                height * Const.TEXTURE_GRID),
            zIndex)
        {
            this.columns = columns;
            this.rows = rows;
            this.interval = interval;
            // note: copied from base constructor
            refSource = new Rectangle(
                x * Const.TEXTURE_GRID,
                y * Const.TEXTURE_GRID,
                width * Const.TEXTURE_GRID,
                height * Const.TEXTURE_GRID);
            frames = 0;
            elapsed = 0;
        }
Member Function Documentation
ChangeColor()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeColor (Color newColor) [protected], [inherited]
Definition at line 32 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.FlickingAnimatedSprite.OnFrame().
        {
            color = newColor;
        }
ChangeSource()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeSource (Point location) [protected], [inherited]
Definition at line 27 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
        {
            source.Location = location;
        }
Draw()
void MelloMario.Graphics.Sprites.BaseSprite.Draw (int time, SpriteBatch spriteBatch, Rectangle destination) [inherited]
Implements MelloMario.ISprite .
Definition at line 56 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.OnDraw().
        {
            if (visible)
            {
                OnDraw(time, spriteBatch, destination);
            }
        }
OnAnimate()
override void MelloMario.Graphics.Sprites.AnimatedSprite.OnAnimate (int time) [protected], [virtual]
Implements MelloMario.Graphics.Sprites.BaseTextureSprite .
Definition at line 64 of file AnimatedSprite.cs.
References MelloMario.Graphics.Sprites.AnimatedSprite.interval, MelloMario.Graphics.Sprites.AnimatedSprite.OnFrame(), and MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
        {
            elapsed += time;
            if (elapsed >= interval)
            {
                UpdateSourceRectangle();
                OnFrame();
                frames += 1;
                if (frames == rows * columns)
                {
                    frames = 0;
                }
                elapsed -= interval;
            }
        }
OnDraw()
override void MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination) [protected], [virtual], [inherited]
Implements MelloMario.Graphics.Sprites.BaseSprite .
Definition at line 37 of file BaseTextureSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.LayerDepth, and MelloMario.Graphics.Sprites.BaseTextureSprite.OnAnimate().
        {
            OnAnimate(time);
            spriteBatch.Draw(
                texture,
                destination,
                source,
                color,
                0f, //rotation
                new Vector2(), //origin
                SpriteEffects.None,
                LayerDepth);
        }
OnFrame()
virtual void MelloMario.Graphics.Sprites.AnimatedSprite.OnFrame () [protected], [virtual]
Reimplemented in MelloMario.Graphics.Sprites.FlickingAnimatedSprite , and MelloMario.Graphics.Sprites.FlashingAnimatedSprite .
Definition at line 83 of file AnimatedSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.OnAnimate().
        {
            // nothing by default
        }
Toggle()
void MelloMario.Graphics.Sprites.BaseSprite.Toggle () [protected], [inherited]
Definition at line 66 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.visible.
Referenced by MelloMario.Graphics.Sprites.FlashingAnimatedSprite.OnFrame().
        {
            visible = !visible;
        }
UpdateSourceRectangle()
void MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle () [private]
Definition at line 56 of file AnimatedSprite.cs.
References MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeSource(), and MelloMario.Graphics.Sprites.AnimatedSprite.columns.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.OnAnimate().
        {
            int x = frames % columns;
            int y = frames / columns;
            ChangeSource(new Point(refSource.X + x * refSource.Width, refSource.Y + y *
      refSource.Height));
        }
Member Data Documentation
columns
readonly int MelloMario.Graphics.Sprites.AnimatedSprite.columns [private]
Definition at line 15 of file AnimatedSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.AnimatedSprite(), and MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
elapsed
int MelloMario.Graphics.Sprites.AnimatedSprite.elapsed [private]
Definition at line 18 of file AnimatedSprite.cs.
frames
int MelloMario.Graphics.Sprites.AnimatedSprite.frames [private]
Definition at line 20 of file AnimatedSprite.cs.
interval
readonly int MelloMario.Graphics.Sprites.AnimatedSprite.interval [private]
Definition at line 16 of file AnimatedSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.AnimatedSprite(), and MelloMario.Graphics.Sprites.AnimatedSprite.OnAnimate().
refSource
Rectangle MelloMario.Graphics.Sprites.AnimatedSprite.refSource [private]
Definition at line 21 of file AnimatedSprite.cs.
rows
readonly int MelloMario.Graphics.Sprites.AnimatedSprite.rows [private]
Definition at line 17 of file AnimatedSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.AnimatedSprite().
Property Documentation
LayerDepth
float MelloMario.Graphics.Sprites.BaseSprite.LayerDepth [get], [protected], [inherited]
Definition at line 25 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite(), MelloMario.Graphics.Sprites.SplashSprite.OnDraw(), MelloMario.Graphics.Sprites.BrickPieceSprite.OnDraw(), MelloMario.Graphics.Sprites.TextSprite.OnDraw(), and MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw().
PixelSize
Point MelloMario.Graphics.Sprites.BaseSprite.PixelSize [get], [inherited]
Definition at line 54 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Graphics/Sprites/ AnimatedSprite.cs