MelloMario.Objects.UserInterfaces.GameWon Class Reference
Public Member Functions
 GameWon (IPlayer player)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Member Functions
override void OnUpdate (int time)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Offset (ref Rectangle rect)
void UpdateOrigin ()
Protected Attributes
 IPlayer Player
Point RelativeOrigin
Private Attributes
readonly ISprite splashSprite
readonly ISprite textSprite
readonly ISprite textSprite2
Rectangle splashDestinationRect
Rectangle textDestinationRect
Rectangle text2DestinationRect
Detailed Description
Definition at line 12 of file GameWon.cs.
Constructor & Destructor Documentation
GameWon()
MelloMario.Objects.UserInterfaces.GameWon.GameWon (IPlayer player)
Definition at line 21 of file GameWon.cs.
References MelloMario.Theming.Player.Coins, MelloMario.ISpriteFactory< T >.CreateSplashSprite(), MelloMario.ISpriteFactory< T >.CreateTextSprite(), MelloMario.Factories.SpriteFactory.Instance, MelloMario.Theming.Player.Score, MelloMario.Theming.Const.SCREEN_HEIGHT, and MelloMario.Theming.Const.SCREEN_WIDTH.
                                       : base(player)
        {
            splashSprite = SpriteFactory.Instance.CreateSplashSprite();
            string text = "MARIO "
                + " WORLD TIME\n"
                + Player.Score.ToString().PadLeft(6, '0')
                + " *"
                + Player.Coins.ToString().PadLeft(2, '0')
                + " "
                + "1-1"
                + " ";
            textSprite = SpriteFactory.Instance.CreateTextSprite(text);
            textSprite2 = SpriteFactory.Instance.CreateTextSprite("You won!\n\nPress R to restart\n\nPress
       Q to quit");
            splashDestinationRect = new Rectangle(0, 0, Const.SCREEN_WIDTH, Const.SCREEN_HEIGHT);
            textDestinationRect = new Rectangle(10, 10, 80, 80);
            text2DestinationRect = new Rectangle(200, 200, 200, 80);
            //TODO:Move this into soundcontroller
            //SoundManager.GameWon.Play();
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseUIObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 27 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnDraw().
        {
            OnDraw(time, spriteBatch);
        }
Offset()
void MelloMario.Objects.BaseUIObject.Offset (ref Rectangle rect) [protected], [inherited]
Definition at line 32 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            rect.Offset(Player.Camera.Viewport.Location - RelativeOrigin);
        }
OnDraw()
override void MelloMario.Objects.UserInterfaces.GameWon.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 51 of file GameWon.cs.
        {
            splashSprite.Draw(time, spriteBatch, splashDestinationRect);
            textSprite.Draw(time, spriteBatch, textDestinationRect);
            textSprite2.Draw(time, spriteBatch, text2DestinationRect);
        }
OnUpdate()
override void MelloMario.Objects.UserInterfaces.GameWon.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 43 of file GameWon.cs.
References MelloMario.Objects.BaseUIObject.Offset(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
        {
            Offset(ref textDestinationRect);
            Offset(ref text2DestinationRect);
            Offset(ref splashDestinationRect);
            UpdateOrigin();
        }
Update()
void MelloMario.Objects.BaseUIObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 22 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnUpdate().
        {
            OnUpdate(time);
        }
UpdateOrigin()
void MelloMario.Objects.BaseUIObject.UpdateOrigin () [protected], [inherited]
Definition at line 37 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, MelloMario.Objects.BaseUIObject.OnDraw(), MelloMario.Objects.BaseUIObject.OnUpdate(), and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            RelativeOrigin = Player.Camera.Viewport.Location;
        }
Member Data Documentation
Player
 IPlayer MelloMario.Objects.BaseUIObject.Player [protected], [inherited]
Definition at line 12 of file BaseUIObject.cs.
RelativeOrigin
Point MelloMario.Objects.BaseUIObject.RelativeOrigin [protected], [inherited]
Definition at line 13 of file BaseUIObject.cs.
splashDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameWon.splashDestinationRect [private]
Definition at line 17 of file GameWon.cs.
splashSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameWon.splashSprite [private]
Definition at line 14 of file GameWon.cs.
text2DestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameWon.text2DestinationRect [private]
Definition at line 19 of file GameWon.cs.
textDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameWon.textDestinationRect [private]
Definition at line 18 of file GameWon.cs.
textSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameWon.textSprite [private]
Definition at line 15 of file GameWon.cs.
textSprite2
readonly ISprite MelloMario.Objects.UserInterfaces.GameWon.textSprite2 [private]
Definition at line 16 of file GameWon.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/UserInterfaces/ GameWon.cs