MelloMario.LevelGen.JsonConverters.Util Class Reference
Static Public Member Functions
static void Initilalize ()
static bool TryGet< T > (out T obj, JToken token, params string[] p)
static Tuple< bool, string[]> GetPropertyPair (JToken token)
static void BatchRecCreate< T > (Func< Point, T > func, Point startPoint, Point quantity, Point objSize, ICollection< Point > ignoredSet, IDictionary< Point, T > propertiesDict=null, Action< Point, T > applyProperty=null)
static void BatchTriCreate< T > (Func< Point, T > createFunc, Point startPoint, Point triangleSize, Point objSize, ICollection< Point > ignoredSet)
static void BatchCreateWithProperties< T1, T2 > (Func< Point, T1 > createFunc, Point startPoint, Point quantity, Point objSize, ICollection< Point > ignoredSet, IDictionary< Point, T2 > properties, Action< IGameObject, T2 > applyProperties)
static List< IGameObject > CreateSinglePipeline (IWorld world, IListener< IGameObject > listener, IListener< ISoundable > soundListener, string pipelineType, int pipelineLength, Point pipelineLoc)
static IList< IGameObject > CreateItemList (IWorld world, Point point, IListener< IGameObject > listener, IListener< ISoundable > soundListener, params string[] s)
static bool TryReadIgnoreSet (JToken token, out ISet< Point > toBeIgnored)
Static Private Attributes
static readonly JsonSerializer serializers = new JsonSerializer()
Detailed Description
Definition at line 43 of file Util.cs.
Member Function Documentation
BatchCreateWithProperties< T1, T2 >()
static void MelloMario.LevelGen.JsonConverters.Util.BatchCreateWithProperties< T1, T2 > (Func< Point, T1 > createFunc, Point startPoint, Point quantity, Point objSize, ICollection< Point > ignoredSet, IDictionary< Point, T2 > properties, Action< IGameObject, T2 > applyProperties) [static]
Definition at line 154 of file Util.cs.
        {
            Contract.Assume(!((properties == null) ^ (applyProperties == null)));
            for (int x = 0; x < quantity.X; x++)
            {
                for (int y = 0; y < quantity.Y; y++)
                {
                    Point createLocation = new Point(startPoint.X + x * objSize.X, startPoint.Y + y *
      objSize.Y);
                    Point createIndex = new Point(x + 1, y + 1);
                    if (ignoredSet == null || !ignoredSet.Contains(createIndex))
                    {
                        if (typeof(T1).IsAssignableFrom(typeof(IEnumerable<IGameObject>)))
                        {
                            foreach (IGameObject obj in (IEnumerable<IGameObject>) createFunc(
      createLocation))
                            {
                                Point index = new Point(x, y);
                                if (properties != null && properties.ContainsKey(index))
                                {
                                    applyProperties(obj, properties[index]);
                                }
                            }
                        }
                        else
                        {
                            IGameObject newObject = (IGameObject) createFunc(createLocation);
                            Point index = new Point(x, y);
                            if (properties != null && properties.ContainsKey(index))
                            {
                                applyProperties(newObject, properties[index]);
                            }
                        }
                    }
                }
            }
        }
BatchRecCreate< T >()
static void MelloMario.LevelGen.JsonConverters.Util.BatchRecCreate< T > (Func< Point, T > func, Point startPoint, Point quantity, Point objSize, ICollection< Point > ignoredSet, IDictionary< Point, T > propertiesDict = null, Action< Point, T > applyProperty = null) [static]
Definition at line 95 of file Util.cs.
        {
            for (int x = 0; x < quantity.X; x++)
            {
                for (int y = 0; y < quantity.Y; y++)
                {
                    Point createLocation = new Point(startPoint.X + x * objSize.X, startPoint.Y + y *
      objSize.Y);
                    Point createIndex = new Point(x + 1, y + 1);
                    if (ignoredSet == null || !ignoredSet.Contains(createIndex))
                    {
                        func(createLocation);
                    }
                }
            }
        }
BatchTriCreate< T >()
static void MelloMario.LevelGen.JsonConverters.Util.BatchTriCreate< T > (Func< Point, T > createFunc, Point startPoint, Point triangleSize, Point objSize, ICollection< Point > ignoredSet) [static]
Definition at line 118 of file Util.cs.
        {
            int X = triangleSize.X;
            int Y = triangleSize.Y;
            bool directionToRight = X > 0;
            bool directionToDown = Y > 0;
            X = Math.Abs(X);
            Y = Math.Abs(Y);
            for (int y = 0; y < Y; y++)
            {
                for (int x = 0; x <= y; x++)
                {
                    Point createLocation = new Point(
                        startPoint.X + (directionToRight ? x : -x) * objSize.X,
                        startPoint.Y + (directionToDown ? y : -y) * objSize.Y);
                    Point createIndex = new Point(x + 1, y + 1);
                    if (ignoredSet == null || !ignoredSet.Contains(createIndex))
                    {
                        if (typeof(T).IsAssignableFrom(typeof(IEnumerable<IGameObject>)))
                        {
                            createFunc(createLocation);
                        }
                        else
                        {
                            createFunc(createLocation);
                        }
                    }
                }
            }
        }
CreateItemList()
static IList< IGameObject> MelloMario.LevelGen.JsonConverters.Util.CreateItemList (IWorld world, Point point, IListener< IGameObject > listener, IListener< ISoundable > soundListener, params string [] s) [static]
Definition at line 265 of file Util.cs.
References MelloMario.IGameObjectFactory.CreateGameObject(), and MelloMario.Factories.GameObjectFactory.Instance.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateBrickOrQuestion().
        {
            return s?.Select(t => GameObjectFactory.Instance.CreateGameObject(t, world, point, listener,
      soundListener))
                .ToList();
        }
CreateSinglePipeline()
static List< IGameObject> MelloMario.LevelGen.JsonConverters.Util.CreateSinglePipeline (IWorld world, IListener< IGameObject > listener, IListener< ISoundable > soundListener, string pipelineType, int pipelineLength, Point pipelineLoc) [static]
Definition at line 197 of file Util.cs.
References MelloMario.Theming.Const.GRID.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreatePipeline().
        {
            int grid = Const.GRID;
            List<IGameObject> listOfPipelineComponents = new List<IGameObject>();
            Pipeline in1 = null;
            Pipeline in2 = null;
            switch (pipelineType)
            {
                //TODO: this is sloppy, this should use the game object factory.
                case "V":
                    in1 = new Pipeline(world, pipelineLoc, listener, soundListener, "LeftIn");
                    in2 = new Pipeline(
                        world,
                        new Point(pipelineLoc.X + grid, pipelineLoc.Y),
                        listener,
                        soundListener,
                        "RightIn");
                    pipelineLoc = new Point(pipelineLoc.X, pipelineLoc.Y + grid);
                    goto case "NV";
                case "HL":
                    in1 = new Pipeline(world, pipelineLoc, listener, soundListener, "TopLeftIn");
                    in2 = new Pipeline(world, new Point(pipelineLoc.X, pipelineLoc.Y + grid), listener,
      soundListener, "BottomLeftIn");
                    pipelineLoc = new Point(pipelineLoc.X + Const.GRID, pipelineLoc.Y);
                    goto case "NH";
                case "HR":
                    in1 = new Pipeline(world, pipelineLoc, listener, soundListener, "TopRightIn");
                    in2 = new Pipeline(
                        world,
                        new Point(pipelineLoc.X, pipelineLoc.Y + grid),
                        listener,
                        soundListener,
                        "BottomRightIn");
                    pipelineLoc = new Point(pipelineLoc.X - pipelineLength * grid, pipelineLoc.Y);
                    goto case "NH";
                case "NV":
                    for (int y = 0; y < pipelineLength; y++)
                    {
                        Point loc1 = new Point(pipelineLoc.X, pipelineLoc.Y + grid * y);
                        Point loc2 = new Point(pipelineLoc.X + grid, pipelineLoc.Y + grid * y);
                        listOfPipelineComponents.Add(new Pipeline(world, loc1, listener, soundListener, "
      Left"));
                        listOfPipelineComponents.Add(new Pipeline(world, loc2, listener, soundListener, "
      Right"));
                    }
                    break;
                case "NH":
                    for (int x = 0; x < pipelineLength; x++)
                    {
                        Point loc1 = new Point(pipelineLoc.X + grid * x, pipelineLoc.Y);
                        Point loc2 = new Point(pipelineLoc.X + grid * x, pipelineLoc.Y + grid);
                        listOfPipelineComponents.Add(new Pipeline(world, loc1, listener, soundListener, "
      Top"));
                        listOfPipelineComponents.Add(new Pipeline(world, loc2, listener, soundListener, "
      Bottom"));
                    }
                    break;
                default:
                    //DO NOTHING
                    break;
                    ;
            }
            listOfPipelineComponents.Insert(0, in1);
            listOfPipelineComponents.Insert(1, in2);
            return listOfPipelineComponents;
        }
GetPropertyPair()
static Tuple<bool, string[]> MelloMario.LevelGen.JsonConverters.Util.GetPropertyPair (JToken token) [static]
Definition at line 88 of file Util.cs.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateBrickOrQuestion().
        {
            return new Tuple<bool, string[]>(
                TryGet(out bool isHidden, token, "Property", "IsHidden") && isHidden,
                TryGet(out string[] itemValues, token, "Property", "ItemValues") ? itemValues : null);
        }
Initilalize()
static void MelloMario.LevelGen.JsonConverters.Util.Initilalize () [static]
Definition at line 47 of file Util.cs.
Referenced by MelloMario.LevelGen.JsonConverters.LevelIOJson.LevelIOJson().
        {
            serializers.Converters.Add(new VectorConverter());
        }
TryGet< T >()
static bool MelloMario.LevelGen.JsonConverters.Util.TryGet< T > (out T obj, JToken token, params string [] p) [static]
Definition at line 52 of file Util.cs.
        {
            obj = default(T);
            if (token.Type is JTokenType.Array)
            {
                return false;
            }
            JToken tempToken = token;
            for (int i = 0; i < p.Length - 1; i++)
            {
                if (tempToken[p[i]] != null)
                {
                    if (tempToken.Type is JTokenType.Array)
                    {
                        return false;
                    }
                    tempToken = tempToken[p[i]];
                }
                else
                {
                    return false;
                }
            }
            string str = p[p.Length - 1];
            if (tempToken.Type is JTokenType.Array)
            {
                return false;
            }
            if (tempToken[str] == null)
            {
                return false;
            }
            obj = tempToken[p[p.Length - 1]].ToObject<T>(serializers);
            return true;
        }
TryReadIgnoreSet()
static bool MelloMario.LevelGen.JsonConverters.Util.TryReadIgnoreSet (JToken token, out ISet< Point > toBeIgnored) [static]
Definition at line 276 of file Util.cs.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.ReadJson().
        {
            toBeIgnored = new HashSet<Point>();
            if (token["Ignored"] == null)
            {
                return false;
            }
            List<JToken> ignoredToken = token["Ignored"].ToList();
            foreach (JToken t in ignoredToken)
            {
                toBeIgnored.Add(t.ToObject<Point>());
            }
            return true;
        }
Member Data Documentation
serializers
readonly JsonSerializer MelloMario.LevelGen.JsonConverters.Util.serializers = new JsonSerializer() [static], [private]
Definition at line 45 of file Util.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/LevelGen/JsonConverters/ Util.cs