MelloMario.LevelGen.JsonConverters.GameEntityConverter Class Reference
Public Types
enum ProduceMode { ProduceMode.One,
 ProduceMode.Rectangle,
 ProduceMode.Triangle
 }
Public Member Functions
 GameEntityConverter (IWorld parentWorld, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
override bool CanConvert (Type objectType)
override object ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
override void WriteJson (JsonWriter writer, object value, JsonSerializer serializer)
Properties
override bool CanWrite [get]
Private Member Functions
bool ItemConverter ()
bool EnemyConverter ()
void CreateBrickOrQuestion ()
void CreateSimpleBlock ()
void CreatePipeline ()
void CreateFlag ()
bool BlockConverter ()
bool BackgroundConverter ()
Private Attributes
readonly IListener< IGameObject > listener
readonly IListener< ISoundable > soundListener
readonly IWorld world
string backgroundType
Func< Point, IGameObject > createFunc
string direction
string entrance
ISet< Point > ignoredSet
int length
IList< IGameObject > list
Stack< IGameObject > objectStackToBeEncapsulated
Point objFullSize
Point objPoint
JToken token
Vector2 objVector
 ProduceMode produceMode
Tuple< bool, string[]> propertyPair
Point quantity
Type type
Point triangleSize
Static Private Attributes
static readonly IEnumerable< Type > AssemblyTypes
Detailed Description
Definition at line 33 of file GameEntityConverter.cs.
Member Enumeration Documentation
ProduceMode
enum MelloMario.LevelGen.JsonConverters.GameEntityConverter.ProduceMode [strong]
Enumerator
One
Rectangle
Triangle
Definition at line 186 of file GameEntityConverter.cs.
        {
            One,
            Rectangle,
            Triangle
        }
Constructor & Destructor Documentation
GameEntityConverter()
MelloMario.LevelGen.JsonConverters.GameEntityConverter.GameEntityConverter (IWorld parentWorld, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Definition at line 62 of file GameEntityConverter.cs.
        {
            this.listener = listener;
            this.soundListener = soundListener;
            world = parentWorld;
        }
Member Function Documentation
BackgroundConverter()
bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.BackgroundConverter () [private]
Definition at line 445 of file GameEntityConverter.cs.
        {
            if (Util.TryGet(out backgroundType, token, "Property", "Type"))
            {
                Debug.WriteLine("Deserialize fail: Type of background is not given!");
            }
            ZIndex zIndex = Util.TryGet(out string s, token, "Property", "ZIndex")
                ? (ZIndex) Enum.Parse(typeof(ZIndex), s)
                : ZIndex.Background0;
            createFunc = point => (IGameObject) Activator.CreateInstance(type,
      world, point, backgroundType, zIndex);
            objFullSize = createFunc(new Point()).Boundary.Size;
            if (produceMode is ProduceMode.One)
            {
                createFunc(objPoint);
            }
            else
            {
                Util.BatchRecCreate(createFunc, objPoint, quantity, objFullSize,
      ignoredSet);
            }
            return true;
        }
BlockConverter()
bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.BlockConverter () [private]
Definition at line 421 of file GameEntityConverter.cs.
        {
            switch (type)
            {
                case Type t when t.Name == "Brick" || t.Name == "Question":
                    CreateBrickOrQuestion();
                    return true;
                case Type t when t.Name == "Flag":
                    CreateFlag();
                    break;
                case Type t when !t.IsAssignableFrom(typeof(Pipeline)):
                    CreateSimpleBlock();
                    break;
                case Type t when t.Name == "Pipeline":
                    CreatePipeline();
                    break;
            }
            return true;
        }
CanConvert()
override bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.CanConvert (Type objectType)
Definition at line 81 of file GameEntityConverter.cs.
        {
            return typeof(EncapsulatedObject<IGameObject>).IsAssignableFrom(objectType);
        }
CreateBrickOrQuestion()
void MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateBrickOrQuestion () [private]
Definition at line 261 of file GameEntityConverter.cs.
References MelloMario.LevelGen.JsonConverters.Util.CreateItemList(), MelloMario.LevelGen.JsonConverters.Util.GetPropertyPair(), MelloMario.Theming.Const.GRID, and MelloMario.Theming.Database.SetEnclosedItem().
        {
            createFunc = point =>
            {
                IGameObject gameObj = Activator.CreateInstance(type, world, point,
      listener, soundListener, false) as IGameObject;
                (gameObj as Question)?.Initialize(propertyPair.Item1);
                (gameObj as Brick)?.Initialize(propertyPair.Item1);
                return gameObj;
            };
            switch (produceMode)
            {
                case ProduceMode.One:
                    propertyPair = Util.GetPropertyPair(token);
                    list = Util.CreateItemList(world, objPoint, listener,
      soundListener, propertyPair.Item2);
                    IGameObject gameObj = createFunc(objPoint);
                    if (list != null && list.Count != 0)
                    {
                        Database.SetEnclosedItem(gameObj, list);
                    }
                    (gameObj as Question)?.Initialize(propertyPair.Item1);
                    (gameObj as Brick)?.Initialize(propertyPair.Item1);
                    break;
                default:
                    #region GetProperties
                    //TOOD:Finish it
                    Dictionary<Point, Tuple<bool, string[]>> propertiesDict = new Dictionary<Point,
       Tuple<bool, string[]>>(new PointCompare());
                    if (Util.TryGet(out JToken propertiesToken, token, "Properties"))
                    {
                        foreach (JToken propertyToken in propertiesToken)
                        {
                            Util.TryGet(out Point index, propertyToken, "Index");
                            Tuple<bool, string[]> newPair = Util.GetPropertyPair(propertyToken);
                            propertiesDict.Add(index, newPair);
                        }
                    }
                    #endregion
                    break;
                case ProduceMode.Rectangle:
                    Util.BatchRecCreate(createFunc, objPoint, quantity, new Point(Const.GRID, Const.GRID),
      ignoredSet);
                    break;
                case ProduceMode.Triangle:
                    Util.BatchTriCreate(createFunc, objPoint, triangleSize, new Point(Const.GRID, Const.
      GRID), ignoredSet);
                    break;
            }
        }
CreateFlag()
void MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateFlag () [private]
Definition at line 410 of file GameEntityConverter.cs.
References MelloMario.IGameObjectFactory.CreateGameObjectGroup(), and MelloMario.Factories.GameObjectFactory.Instance.
        {
            bool hasHeight = Util.TryGet(out int Height, token, "Property", "Height");
            GameObjectFactory.Instance.CreateGameObjectGroup(
                "FlagPole",
                world,
                objPoint,
                hasHeight ? Height : 7,
                listener);
        }
CreatePipeline()
void MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreatePipeline () [private]
Definition at line 342 of file GameEntityConverter.cs.
References MelloMario.Theming.Database.AddPipelineIndex(), MelloMario.Theming.Database.AddPortal(), MelloMario.LevelGen.JsonConverters.Util.CreateSinglePipeline(), MelloMario.Theming.Const.GRID, and MelloMario.Theming.Database.SetEntranceIndex().
        {
            if (!Util.TryGet(out length, token, "Property", "Length"))
            {
                Debug.WriteLine("Deserialize fail: Length of Pipeline is missing.");
                return;
            }
            if (!Util.TryGet(out direction, token, "Property", "Direction"))
            {
                Debug.WriteLine("Deserialize fail: Direction of Pipeline is missing.");
                return;
            }
            bool hasIndex = Util.TryGet(out string pipelineIndex, token, "Property", "Index");
            bool isPortalTo = Util.TryGet(out string portalTo, token, "Property", "PortalTo");
            if (produceMode is ProduceMode.One)
            {
                list = Util.CreateSinglePipeline(world, listener, soundListener, direction, length,
      objPoint);
                if (Util.TryGet(out JToken piranhaToken, token, "Property", "Piranha"))
                {
                    if (Util.TryGet(out string color, piranhaToken, "Color")
                        && Util.TryGet(out float hiddenTime, piranhaToken, "HiddenTime")
                        && Util.TryGet(out float showTime, piranhaToken, "ShowTime"))
                    {
                        new Piranha(
                            world,
                            new Point(objPoint.X + 16, objPoint.Y),
                            listener,
                            new Point(32, 48),
                            (int) (hiddenTime * 1000),
                            (int) (showTime * 1000),
                            32,
                            color);
                    }
                }
                if (direction != "NV" && direction != "NH")
                {
                    if (Util.TryGet(out entrance, token, "Property", "Entrance"))
                    {
                        Database.SetEntranceIndex(list[0] as Pipeline, entrance);
                        Database.SetEntranceIndex(list[1] as Pipeline, entrance);
                    }
                    if (hasIndex)
                    {
                        Database.AddPipelineIndex(
                            pipelineIndex,
                            new Tuple<Pipeline, Pipeline>(list[0] as Pipeline,
      list[1] as Pipeline));
                    }
                    if (isPortalTo)
                    {
                        Database.AddPortal(list[0] as Pipeline, portalTo);
                        Database.AddPortal(list[1] as Pipeline, portalTo);
                    }
                }
            }
            else
            {
                objFullSize = direction.Contains("V")
                    ? new Point(Const.GRID * 2, Const.GRID + Const.GRID * length)
                    : new Point(Const.GRID + Const.GRID * length, Const.GRID * 2);
                Util.BatchRecCreate(
                    point => Util.CreateSinglePipeline(world, listener,
      soundListener, direction, length, point),
                    objPoint,
                    quantity,
                    objFullSize,
                    ignoredSet);
            }
        }
CreateSimpleBlock()
void MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateSimpleBlock () [private]
Definition at line 311 of file GameEntityConverter.cs.
References MelloMario.Theming.Const.GRID.
        {
            switch (produceMode)
            {
                case ProduceMode.One:
                    Activator.CreateInstance(type, world, objPoint, listener, false);
                    break;
                case ProduceMode.Rectangle:
                {
                    Util.BatchRecCreate(
                        point => (IGameObject) Activator.CreateInstance(type,
      world, point, listener, false),
                        objPoint,
                        quantity,
                        new Point(Const.GRID, Const.GRID),
                        ignoredSet);
                    break;
                }
                case ProduceMode.Triangle:
                {
                    Util.BatchTriCreate(
                        point => (IGameObject) Activator.CreateInstance(type,
      world, point, listener, false),
                        objPoint,
                        triangleSize,
                        new Point(Const.GRID, Const.GRID),
                        ignoredSet);
                    break;
                }
            }
        }
EnemyConverter()
bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.EnemyConverter () [private]
Definition at line 221 of file GameEntityConverter.cs.
References MelloMario.Theming.Const.GRID.
        {
            if (type.Name == "Piranha")
            {
                float hideTime = Util.TryGet(out hideTime, token, "Property", "HideTime") ? hideTime : 3;
                Activator.CreateInstance(type, world, objPoint, hideTime);
            }
            else
            {
                if (type.Name == "Koopa")
                {
                    Util.TryGet(out string color, token, "Property", "Color");
                    createFunc = point => (IGameObject) Activator.CreateInstance(
                        type,
                        world,
                        point,
                        listener,
                        color);
                }
                if (produceMode is ProduceMode.One)
                {
                    createFunc(objPoint);
                }
                else if (produceMode is ProduceMode.Rectangle)
                {
                    Util.BatchRecCreate(
                        createFunc,
                        objPoint,
                        quantity,
                        new Point(Const.GRID, Const.GRID),
                        ignoredSet);
                }
            }
            return true;
        }
ItemConverter()
bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.ItemConverter () [private]
Definition at line 197 of file GameEntityConverter.cs.
References MelloMario.Theming.Const.GRID.
        {
            createFunc = point => (IGameObject) Activator.CreateInstance(type,
      world, point, listener, soundListener, false);
            switch (produceMode)
            {
                case ProduceMode.One:
                    createFunc(objPoint);
                    break;
                case ProduceMode.Rectangle:
                    Util.BatchRecCreate(createFunc, objPoint, quantity, new Point(Const.GRID, Const.GRID),
      ignoredSet);
                    break;
                case ProduceMode.Triangle:
                    Util.BatchTriCreate(createFunc, objPoint, triangleSize, new Point(Const.GRID, Const.
      GRID), ignoredSet);
                    break;
                default:
                    goto case ProduceMode.One;
            }
            return true;
        }
ReadJson()
override object MelloMario.LevelGen.JsonConverters.GameEntityConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
Definition at line 86 of file GameEntityConverter.cs.
References MelloMario.Theming.Const.GRID, and MelloMario.LevelGen.JsonConverters.Util.TryReadIgnoreSet().
        {
            token = JToken.Load(reader);
            if (!Util.TryGet(out objVector, token, "Point"))
            {
                Debug.WriteLine("Deserialize fail: No start point provided!");
                return null;
            }
            objPoint = new Point((int) (objVector.X * Const.GRID), (int) (objVector.Y * Const.GRID));
            objectStackToBeEncapsulated = new Stack<IGameObject>();
            if (!Util.TryGet(out string typeStr, token, "Type"))
            {
                Debug.Print("Deserialize fail: Object token does not contain property \"Type\"");
                return null;
            }
            type = null;
            foreach (Type t in AssemblyTypes)
            {
                type = t.Name == typeStr ? t : null;
                if (type != null)
                {
                    break;
                }
            }
            if (type == null)
            {
                Debug.Print("Deserialize fail: " + typeStr + " not found!");
                return null;
            }
            createFunc = point => (type.Name == "Brick" || type.Name == "Question"
                    ? Activator.CreateInstance(type, world, point, listener,
      soundListener, false)
                    : Activator.CreateInstance(type, world, point, listener))
                as IGameObject;
            produceMode = ProduceMode.One;
            if (Util.TryGet(out quantity, token, "Quantity"))
            {
                if (quantity.X * quantity.Y > 1)
                {
                    produceMode = ProduceMode.Rectangle;
                }
            }
            if (Util.TryGet(out triangleSize, token, "Triangle"))
            {
                if (Math.Abs(triangleSize.X) > 1 && Math.Abs(triangleSize.Y) > 1)
                {
                    produceMode = ProduceMode.Triangle;
                }
            }
            ignoredSet = !(produceMode is ProduceMode.One) && Util.TryReadIgnoreSet(
      token, out ignoredSet)
                ? ignoredSet
                : null;
            switch (type.Namespace)
            {
                case "MelloMario.Objects.Blocks":
                    if (BlockConverter())
                    {
                        Debug.WriteLine("Deserialize " + type.Name + " success!");
                    }
                    break;
                case "MelloMario.Objects.Enemies":
                    if (EnemyConverter())
                    {
                        Debug.WriteLine("Deserialize " + type.Name + " success!");
                    }
                    break;
                case "MelloMario.Objects.Items":
                    if (ItemConverter())
                    {
                        Debug.WriteLine("Deserialize " + type.Name + " success!");
                    }
                    break;
                case "MelloMario.Objects.Miscs":
                    if (BackgroundConverter())
                    {
                        Debug.WriteLine("Deserialize " + type.Name + " success!");
                    }
                    break;
                default:
                    objectStackToBeEncapsulated.Push(createFunc(objPoint));
                    break;
            }
            return new EncapsulatedObject<IGameObject>(
      objectStackToBeEncapsulated);
        }
WriteJson()
override void MelloMario.LevelGen.JsonConverters.GameEntityConverter.WriteJson (JsonWriter writer, object value, JsonSerializer serializer)
Definition at line 181 of file GameEntityConverter.cs.
        {
            //TODO: Implement serializer
        }
Member Data Documentation
AssemblyTypes
readonly IEnumerable<Type> MelloMario.LevelGen.JsonConverters.GameEntityConverter.AssemblyTypes [static], [private]
Initial value:
=
            from type in Assembly.GetExecutingAssembly().GetTypes()
            where typeof(IGameObject).IsAssignableFrom(type)
            select type
Definition at line 35 of file GameEntityConverter.cs.
backgroundType
string MelloMario.LevelGen.JsonConverters.GameEntityConverter.backgroundType [private]
Definition at line 43 of file GameEntityConverter.cs.
createFunc
Func<Point, IGameObject> MelloMario.LevelGen.JsonConverters.GameEntityConverter.createFunc [private]
Definition at line 44 of file GameEntityConverter.cs.
direction
string MelloMario.LevelGen.JsonConverters.GameEntityConverter.direction [private]
Definition at line 45 of file GameEntityConverter.cs.
entrance
string MelloMario.LevelGen.JsonConverters.GameEntityConverter.entrance [private]
Definition at line 46 of file GameEntityConverter.cs.
ignoredSet
ISet<Point> MelloMario.LevelGen.JsonConverters.GameEntityConverter.ignoredSet [private]
Definition at line 47 of file GameEntityConverter.cs.
length
int MelloMario.LevelGen.JsonConverters.GameEntityConverter.length [private]
Definition at line 48 of file GameEntityConverter.cs.
list
IList< IGameObject> MelloMario.LevelGen.JsonConverters.GameEntityConverter.list [private]
Definition at line 49 of file GameEntityConverter.cs.
listener
readonly IListener< IGameObject> MelloMario.LevelGen.JsonConverters.GameEntityConverter.listener [private]
Definition at line 40 of file GameEntityConverter.cs.
objectStackToBeEncapsulated
Stack< IGameObject> MelloMario.LevelGen.JsonConverters.GameEntityConverter.objectStackToBeEncapsulated [private]
Definition at line 50 of file GameEntityConverter.cs.
objFullSize
Point MelloMario.LevelGen.JsonConverters.GameEntityConverter.objFullSize [private]
Definition at line 51 of file GameEntityConverter.cs.
objPoint
Point MelloMario.LevelGen.JsonConverters.GameEntityConverter.objPoint [private]
Definition at line 52 of file GameEntityConverter.cs.
objVector
Vector2 MelloMario.LevelGen.JsonConverters.GameEntityConverter.objVector [private]
Definition at line 54 of file GameEntityConverter.cs.
produceMode
 ProduceMode MelloMario.LevelGen.JsonConverters.GameEntityConverter.produceMode [private]
Definition at line 56 of file GameEntityConverter.cs.
propertyPair
Tuple<bool, string[]> MelloMario.LevelGen.JsonConverters.GameEntityConverter.propertyPair [private]
Definition at line 57 of file GameEntityConverter.cs.
quantity
Point MelloMario.LevelGen.JsonConverters.GameEntityConverter.quantity [private]
Definition at line 58 of file GameEntityConverter.cs.
soundListener
readonly IListener< ISoundable> MelloMario.LevelGen.JsonConverters.GameEntityConverter.soundListener [private]
Definition at line 41 of file GameEntityConverter.cs.
token
JToken MelloMario.LevelGen.JsonConverters.GameEntityConverter.token [private]
Definition at line 53 of file GameEntityConverter.cs.
triangleSize
Point MelloMario.LevelGen.JsonConverters.GameEntityConverter.triangleSize [private]
Definition at line 60 of file GameEntityConverter.cs.
type
Type MelloMario.LevelGen.JsonConverters.GameEntityConverter.type [private]
Definition at line 59 of file GameEntityConverter.cs.
world
readonly IWorld MelloMario.LevelGen.JsonConverters.GameEntityConverter.world [private]
Definition at line 42 of file GameEntityConverter.cs.
Property Documentation
CanWrite
override bool MelloMario.LevelGen.JsonConverters.GameEntityConverter.CanWrite [get]
Definition at line 74 of file GameEntityConverter.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/LevelGen/JsonConverters/ GameEntityConverter.cs