MelloMario.Theming.Database Class Reference
Static Public Member Functions
static void Initialize (ISession newSession)
static void AddPipelineIndex (string index, Tuple< Pipeline, Pipeline > pipeline)
static void AddPortal (Pipeline pipeline, string portalTo)
static bool IsPortal (Pipeline pipeline)
static Pipeline GetPortal (Pipeline pipeline)
static Point GetCharacterLocation ()
static bool HasItemEnclosed (IGameObject obj)
static IGameObject GetNextItem (IGameObject obj)
static void SetEnclosedItem (IGameObject obj, IList< IGameObject > itemList)
static bool IsEntrance (Pipeline pipeline)
static string GetEntranceIndex (Pipeline pipeline)
static void SetEntranceIndex (Pipeline pipeline, string index)
static void Update ()
Static Private Attributes
static readonly IDictionary< IGameObject, IList< IGameObject > > ItemEnclosedDb
static readonly IDictionary< Pipeline, string > PipelineEntranceDb = new Dictionary< Pipeline, string>()
static readonly IDictionary< Pipeline, string > PipelinePortalDb = new Dictionary< Pipeline, string>()
static readonly IDictionary< string, Tuple< Pipeline, Pipeline > > PipelineIndex
static readonly ConcurrentDictionary< ICharacter, Point > CharacterLocations
static ISession Session
Detailed Description
Definition at line 18 of file Database.cs.
Member Function Documentation
AddPipelineIndex()
static void MelloMario.Theming.Database.AddPipelineIndex (string index, Tuple< Pipeline, Pipeline > pipeline) [static]
Definition at line 39 of file Database.cs.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreatePipeline().
        {
            if (!PipelineIndex.ContainsKey(index))
            {
                PipelineIndex.Add(index, pipeline);
            }
        }
AddPortal()
static void MelloMario.Theming.Database.AddPortal (Pipeline pipeline, string portalTo) [static]
Definition at line 47 of file Database.cs.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreatePipeline().
        {
            if (!PipelinePortalDb.ContainsKey(pipeline))
            {
                PipelinePortalDb.Add(pipeline, portalTo);
            }
        }
GetCharacterLocation()
static Point MelloMario.Theming.Database.GetCharacterLocation () [static]
Definition at line 67 of file Database.cs.
        {
            // TODO: use viewport collision
            return CharacterLocations.Count != 0 ? CharacterLocations.Values.ToList()[0] : new Point();
        }
GetEntranceIndex()
static string MelloMario.Theming.Database.GetEntranceIndex (Pipeline pipeline) [static]
Definition at line 117 of file Database.cs.
References MelloMario.Theming.Database.IsEntrance().
Referenced by MelloMario.Objects.Blocks.Pipeline.OnUpdate().
        {
            return IsEntrance(pipeline) ? PipelineEntranceDb[pipeline] : null;
        }
GetNextItem()
static IGameObject MelloMario.Theming.Database.GetNextItem (IGameObject obj) [static]
Definition at line 78 of file Database.cs.
References MelloMario.Theming.Database.HasItemEnclosed(), and MelloMario.ISession.ScanPlayers().
Referenced by MelloMario.Objects.Blocks.Question.ReleaseNextItem(), and MelloMario.Objects.Blocks.Brick.ReleaseNextItem().
        {
            if (!HasItemEnclosed(obj))
            {
                return null;
            }
            if (ItemEnclosedDb[obj][0] is SuperMushroom mushroom)
            {
                if (Session.ScanPlayers()
                    .Any(
                        c => c.Character is MarioCharacter mario
                            && (mario.PowerUpState is Super || mario.PowerUpState is Fire)))
                {
                    ItemEnclosedDb[obj].RemoveAt(0);
                    return mushroom.GetFireFlower();
                }
            }
            IGameObject toBeRemoved = ItemEnclosedDb[obj][0];
            ItemEnclosedDb[obj].RemoveAt(0);
            return toBeRemoved;
        }
GetPortal()
static Pipeline MelloMario.Theming.Database.GetPortal (Pipeline pipeline) [static]
Definition at line 60 of file Database.cs.
Referenced by MelloMario.Objects.Blocks.Pipeline.OnUpdate().
        {
            return PipelinePortalDb.ContainsKey(pipeline) && PipelineIndex.ContainsKey(
      PipelinePortalDb[pipeline])
                ? PipelineIndex[PipelinePortalDb[pipeline]].Item1
                : null;
        }
HasItemEnclosed()
static bool MelloMario.Theming.Database.HasItemEnclosed (IGameObject obj) [static]
Definition at line 73 of file Database.cs.
Referenced by MelloMario.Objects.Blocks.BrickStates.Hidden.Bump(), MelloMario.Theming.Database.GetNextItem(), MelloMario.Objects.Blocks.Brick.Initialize(), MelloMario.Objects.Blocks.Question.ReleaseNextItem(), MelloMario.Objects.Blocks.Brick.ReleaseNextItem(), MelloMario.Objects.Blocks.BrickStates.Bumped.Show(), and MelloMario.Objects.Blocks.QuestionStates.Bumped.Show().
        {
            return ItemEnclosedDb.ContainsKey(obj) && ItemEnclosedDb[obj]?.Count != 0;
        }
Initialize()
static void MelloMario.Theming.Database.Initialize (ISession newSession) [static]
Definition at line 34 of file Database.cs.
Referenced by MelloMario.Theming.GameModel.GameModel().
        {
            Session = newSession;
        }
IsEntrance()
static bool MelloMario.Theming.Database.IsEntrance (Pipeline pipeline) [static]
Definition at line 112 of file Database.cs.
Referenced by MelloMario.Theming.Database.GetEntranceIndex(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), and MelloMario.Theming.Database.SetEntranceIndex().
        {
            return PipelineEntranceDb.ContainsKey(pipeline);
        }
IsPortal()
static bool MelloMario.Theming.Database.IsPortal (Pipeline pipeline) [static]
Definition at line 55 of file Database.cs.
Referenced by MelloMario.Objects.Blocks.Pipeline.OnUpdate().
        {
            return PipelinePortalDb.ContainsKey(pipeline);
        }
SetEnclosedItem()
static void MelloMario.Theming.Database.SetEnclosedItem (IGameObject obj, IList< IGameObject > itemList) [static]
Definition at line 100 of file Database.cs.
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateBrickOrQuestion().
        {
            if (ItemEnclosedDb.ContainsKey(obj))
            {
                ItemEnclosedDb[obj] = itemList;
            }
            else
            {
                ItemEnclosedDb.Add(obj, itemList);
            }
        }
SetEntranceIndex()
static void MelloMario.Theming.Database.SetEntranceIndex (Pipeline pipeline, string index) [static]
Definition at line 122 of file Database.cs.
References MelloMario.Theming.Database.IsEntrance().
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreatePipeline().
        {
            if (IsEntrance(pipeline))
            {
                PipelineEntranceDb[pipeline] = index;
            }
            else
            {
                PipelineEntranceDb.Add(pipeline, index);
            }
        }
Update()
static void MelloMario.Theming.Database.Update () [static]
Definition at line 134 of file Database.cs.
References MelloMario.IPlayer.Character, and MelloMario.ISession.ScanPlayers().
Referenced by MelloMario.Theming.GameModel.Update().
        {
            foreach (IPlayer player in Session.ScanPlayers())
            {
                CharacterLocations.AddOrUpdate(
                    player.Character,
                    ((IGameObject) player.Character).Boundary.Location,
                    (p, loc) => ((IGameObject) p).Boundary.Location);
            }
        }
Member Data Documentation
CharacterLocations
readonly ConcurrentDictionary< ICharacter, Point> MelloMario.Theming.Database.CharacterLocations [static], [private]
Initial value:
=
            new ConcurrentDictionary<ICharacter, Point>()
Definition at line 29 of file Database.cs.
ItemEnclosedDb
readonly IDictionary< IGameObject, IList< IGameObject> > MelloMario.Theming.Database.ItemEnclosedDb [static], [private]
Initial value:
=
            new Dictionary<IGameObject, IList<IGameObject>>()
Definition at line 20 of file Database.cs.
PipelineEntranceDb
readonly IDictionary< Pipeline, string> MelloMario.Theming.Database.PipelineEntranceDb = new Dictionary< Pipeline, string>() [static], [private]
Definition at line 23 of file Database.cs.
PipelineIndex
readonly IDictionary<string, Tuple< Pipeline, Pipeline> > MelloMario.Theming.Database.PipelineIndex [static], [private]
Initial value:
=
            new Dictionary<string, Tuple<Pipeline, Pipeline>>()
Definition at line 26 of file Database.cs.
PipelinePortalDb
readonly IDictionary< Pipeline, string> MelloMario.Theming.Database.PipelinePortalDb = new Dictionary< Pipeline, string>() [static], [private]
Definition at line 24 of file Database.cs.
Session
 ISession MelloMario.Theming.Database.Session [static], [private]
Definition at line 32 of file Database.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Theming/ Database.cs