MelloMario.Graphics.Sprites.FlashingAnimatedSprite Class Reference
Public Member Functions
 FlashingAnimatedSprite (Texture2D texture, int columns, int rows, int x=0, int y=0, int width=2, int height=2, int interval= Const.ANIMATION_INTERVAL, ZIndex zIndex= ZIndex.Item)
void Draw (int time, SpriteBatch spriteBatch, Rectangle destination)
Protected Member Functions
override void OnFrame ()
override void OnAnimate (int time)
void ChangeSource (Point location)
void ChangeColor (Color newColor)
override void OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination)
void Toggle ()
Properties
float LayerDepth [get]
Point PixelSize [get]
Detailed Description
Definition at line 12 of file FlashingAnimatedSprite.cs.
Constructor & Destructor Documentation
FlashingAnimatedSprite()
MelloMario.Graphics.Sprites.FlashingAnimatedSprite.FlashingAnimatedSprite (Texture2D texture, int columns, int rows, int x = 0, int y = 0, int width = 2, int height = 2, int interval = Const.ANIMATION_INTERVAL, ZIndex zIndex = ZIndex.Item)
Definition at line 14 of file FlashingAnimatedSprite.cs.
                                         : base(texture, columns, rows, x, y, width, height,
      interval, zIndex)
        {
        }
Member Function Documentation
ChangeColor()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeColor (Color newColor) [protected], [inherited]
Definition at line 32 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.FlickingAnimatedSprite.OnFrame().
        {
            color = newColor;
        }
ChangeSource()
void MelloMario.Graphics.Sprites.BaseTextureSprite.ChangeSource (Point location) [protected], [inherited]
Definition at line 27 of file BaseTextureSprite.cs.
Referenced by MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
        {
            source.Location = location;
        }
Draw()
void MelloMario.Graphics.Sprites.BaseSprite.Draw (int time, SpriteBatch spriteBatch, Rectangle destination) [inherited]
Implements MelloMario.ISprite .
Definition at line 56 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.OnDraw().
        {
            if (visible)
            {
                OnDraw(time, spriteBatch, destination);
            }
        }
OnAnimate()
override void MelloMario.Graphics.Sprites.AnimatedSprite.OnAnimate (int time) [protected], [virtual], [inherited]
Implements MelloMario.Graphics.Sprites.BaseTextureSprite .
Definition at line 64 of file AnimatedSprite.cs.
References MelloMario.Graphics.Sprites.AnimatedSprite.interval, MelloMario.Graphics.Sprites.AnimatedSprite.OnFrame(), and MelloMario.Graphics.Sprites.AnimatedSprite.UpdateSourceRectangle().
        {
            elapsed += time;
            if (elapsed >= interval)
            {
                UpdateSourceRectangle();
                OnFrame();
                frames += 1;
                if (frames == rows * columns)
                {
                    frames = 0;
                }
                elapsed -= interval;
            }
        }
OnDraw()
override void MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw (int time, SpriteBatch spriteBatch, Rectangle destination) [protected], [virtual], [inherited]
Implements MelloMario.Graphics.Sprites.BaseSprite .
Definition at line 37 of file BaseTextureSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.LayerDepth, and MelloMario.Graphics.Sprites.BaseTextureSprite.OnAnimate().
        {
            OnAnimate(time);
            spriteBatch.Draw(
                texture,
                destination,
                source,
                color,
                0f, //rotation
                new Vector2(), //origin
                SpriteEffects.None,
                LayerDepth);
        }
OnFrame()
override void MelloMario.Graphics.Sprites.FlashingAnimatedSprite.OnFrame () [protected], [virtual]
Reimplemented from MelloMario.Graphics.Sprites.AnimatedSprite .
Definition at line 27 of file FlashingAnimatedSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.Toggle().
        {
            Toggle();
        }
Toggle()
void MelloMario.Graphics.Sprites.BaseSprite.Toggle () [protected], [inherited]
Definition at line 66 of file BaseSprite.cs.
References MelloMario.Graphics.Sprites.BaseSprite.visible.
Referenced by MelloMario.Graphics.Sprites.FlashingAnimatedSprite.OnFrame().
        {
            visible = !visible;
        }
Property Documentation
LayerDepth
float MelloMario.Graphics.Sprites.BaseSprite.LayerDepth [get], [protected], [inherited]
Definition at line 25 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite(), MelloMario.Graphics.Sprites.SplashSprite.OnDraw(), MelloMario.Graphics.Sprites.BrickPieceSprite.OnDraw(), MelloMario.Graphics.Sprites.TextSprite.OnDraw(), and MelloMario.Graphics.Sprites.BaseTextureSprite.OnDraw().
PixelSize
Point MelloMario.Graphics.Sprites.BaseSprite.PixelSize [get], [inherited]
Definition at line 54 of file BaseSprite.cs.
Referenced by MelloMario.Graphics.Sprites.BaseSprite.BaseSprite().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Graphics/Sprites/ FlashingAnimatedSprite.cs