MelloMario.LevelGen.JsonConverters.LevelIOJson Class Reference
Public Member Functions
 LevelIOJson (string jsonPath, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
 IWorld Load (string id)
void Save (string path)
Private Attributes
readonly IListener< IGameObject > listener
readonly IListener< ISoundable > soundListener
readonly string path
 GameConverter gameConverter
string levelString
Detailed Description
Definition at line 10 of file LevelIOJson.cs.
Constructor & Destructor Documentation
LevelIOJson()
MelloMario.LevelGen.JsonConverters.LevelIOJson.LevelIOJson (string jsonPath, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Definition at line 22 of file LevelIOJson.cs.
References MelloMario.LevelGen.JsonConverters.Util.Initilalize(), MelloMario.LevelGen.JsonConverters.LevelIOJson.listener, and MelloMario.LevelGen.JsonConverters.LevelIOJson.soundListener.
        {
            this.listener = listener;
            this.soundListener = soundListener;
            path = jsonPath;
            Util.Initilalize();
        }
Member Function Documentation
Load()
 IWorld MelloMario.LevelGen.JsonConverters.LevelIOJson.Load (string id)
Definition at line 30 of file LevelIOJson.cs.
References MelloMario.LevelGen.JsonConverters.LevelIOJson.gameConverter, and MelloMario.LevelGen.JsonConverters.LevelIOJson.levelString.
Referenced by MelloMario.LevelGen.JsonGenerator.GetObjs(), and MelloMario.Theming.GameModel.LoadLevel().
        {
            levelString = File.ReadAllText(path);
            gameConverter = new GameConverter(listener, soundListener, id);
            return JsonConvert.DeserializeObject<IWorld>(levelString,
      gameConverter);
        }
Save()
void MelloMario.LevelGen.JsonConverters.LevelIOJson.Save (string path)
Definition at line 38 of file LevelIOJson.cs.
        {
        }
Member Data Documentation
gameConverter
 GameConverter MelloMario.LevelGen.JsonConverters.LevelIOJson.gameConverter [private]
Definition at line 19 of file LevelIOJson.cs.
Referenced by MelloMario.LevelGen.JsonConverters.LevelIOJson.Load().
levelString
string MelloMario.LevelGen.JsonConverters.LevelIOJson.levelString [private]
Definition at line 20 of file LevelIOJson.cs.
Referenced by MelloMario.LevelGen.JsonConverters.LevelIOJson.Load().
listener
readonly IListener< IGameObject> MelloMario.LevelGen.JsonConverters.LevelIOJson.listener [private]
Definition at line 12 of file LevelIOJson.cs.
Referenced by MelloMario.LevelGen.JsonConverters.LevelIOJson.LevelIOJson().
path
readonly string MelloMario.LevelGen.JsonConverters.LevelIOJson.path [private]
Definition at line 18 of file LevelIOJson.cs.
soundListener
readonly IListener< ISoundable> MelloMario.LevelGen.JsonConverters.LevelIOJson.soundListener [private]
Definition at line 14 of file LevelIOJson.cs.
Referenced by MelloMario.LevelGen.JsonConverters.LevelIOJson.LevelIOJson().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/LevelGen/JsonConverters/ LevelIOJson.cs