MelloMario.Objects.Enemies.PiranhaStates.Show Class Reference
Public Member Functions
 Show (Piranha owner)
void Defeat ()
override void Update (int time)
void Update (int time)
Protected Member Functions
override void OnTimer (int time)
Properties
float Progress [get]
Detailed Description
Definition at line 11 of file Show.cs.
Constructor & Destructor Documentation
Show()
MelloMario.Objects.Enemies.PiranhaStates.Show.Show (Piranha owner)
Definition at line 13 of file Show.cs.
                                   : base(owner, owner.ShowTime)
        {
        }
Member Function Documentation
Defeat()
void MelloMario.Objects.Enemies.PiranhaStates.Show.Defeat ()
Implements MelloMario.Interfaces.Objects.States.IPiranhaState .
Definition at line 17 of file Show.cs.
        {
            Owner.State = new Defeated(Owner);
        }
OnTimer()
override void MelloMario.Objects.Enemies.PiranhaStates.Show.OnTimer (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseTimedState< Piranha > .
Definition at line 22 of file Show.cs.
        {
            Owner.State = new MovingDown(Owner);
        }
Update() [1/2]
void MelloMario.IState.Update (int time) [inherited]
Implemented in MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Characters.PowerUpStates.Standard , MelloMario.Objects.Characters.MovementStates.Standing , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , MelloMario.Objects.Characters.PowerUpStates.Fire , MelloMario.Objects.Characters.PowerUpStates.Super , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Enemies.KoopaStates.Defeated , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Normal , MelloMario.Objects.Blocks.QuestionStates.Used , MelloMario.Objects.Enemies.KoopaStates.MovingShell , MelloMario.Objects.BaseTimedState< T > , MelloMario.Objects.Enemies.KoopaStates.Normal , MelloMario.Objects.Items.CoinStates.Unveil , MelloMario.Objects.Items.FireFlowerStates.Unveil , MelloMario.Objects.Items.OneUpMushroomStates.Unveil , MelloMario.Objects.Items.StarStates.Unveil , MelloMario.Objects.Items.SuperMushroomStates.Unveil , MelloMario.Objects.Enemies.GoombaStates.Defeated , MelloMario.Objects.Characters.ProtectionStates.Normal , MelloMario.Objects.Enemies.GoombaStates.Normal , MelloMario.Objects.Enemies.ThwompStates.Defeated , MelloMario.Objects.Enemies.ThwompStates.Normal , MelloMario.Objects.Items.CoinStates.Normal , MelloMario.Objects.Items.FireFlowerStates.Normal , MelloMario.Objects.Items.OneUpMushroomStates.Normal , MelloMario.Objects.Items.StarStates.Normal , MelloMario.Objects.Items.SuperMushroomStates.Normal , MelloMario.Objects.Enemies.PiranhaStates.Defeated , MelloMario.Objects.Enemies.PiranhaStates.MovingDown , MelloMario.Objects.Enemies.PiranhaStates.MovingUp , and MelloMario.Objects.BaseState< T > .
Referenced by MelloMario.Objects.Enemies.Thwomp.OnUpdate(), MelloMario.Objects.Enemies.Goomba.OnUpdate(), MelloMario.Objects.Items.OneUpMushroom.OnUpdate(), MelloMario.Objects.Enemies.Piranha.OnUpdate(), MelloMario.Objects.Items.Star.OnUpdate(), MelloMario.Objects.Items.FireFlower.OnUpdate(), MelloMario.Objects.Enemies.Koopa.OnUpdate(), MelloMario.Objects.Items.Coin.OnUpdate(), MelloMario.Objects.Blocks.Question.OnUpdate(), MelloMario.Objects.Items.SuperMushroom.OnUpdate(), MelloMario.Objects.Blocks.Brick.OnUpdate(), and MelloMario.Objects.Characters.Mario.OnUpdate().
Update() [2/2]
override void MelloMario.Objects.BaseTimedState< T >.Update (int time) [inherited]
Definition at line 30 of file BaseTimedState.cs.
        {
            // Note: if we will support recording/replaying, use a constant number here
            elapsed += time;
            if (elapsed >= interval)
            {
                OnTimer(time);
                elapsed -= interval;
            }
        }
Property Documentation
Progress
float MelloMario.Objects.BaseTimedState< T >.Progress [get], [protected], [inherited]
Definition at line 21 of file BaseTimedState.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/Enemies/PiranhaStates/ Show.cs