MelloMario.Objects.BaseGameObject Class Reference
Public Member Functions
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Types
enum ResizeModeX { ResizeModeX.Left,
 ResizeModeX.Center,
 ResizeModeX.Right
 }
enum ResizeModeY { ResizeModeY.Top,
 ResizeModeY.Center,
 ResizeModeY.Bottom
 }
Protected Member Functions
 BaseGameObject (IWorld world, Point location, Point size)
abstract void OnUpdate (int time)
abstract void OnSimulation (int time)
abstract void OnDraw (int time, SpriteBatch spriteBatch)
void Relocate (Point newLocation)
void Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY)
void ShowSprite (ISprite newSprite, ResizeModeX modeX= ResizeModeX.Center, ResizeModeY modeY= ResizeModeY.Bottom)
void HideSprite ()
Protected Attributes
 IWorld World
Properties
Rectangle Boundary [get]
Private Attributes
Point location
Point size
 ISprite sprite
Detailed Description
Definition at line 12 of file BaseGameObject.cs.
Member Enumeration Documentation
ResizeModeX
enum MelloMario.Objects.BaseGameObject.ResizeModeX [strong], [protected]
Enumerator
Left
Center
Right
Definition at line 113 of file BaseGameObject.cs.
        {
            Left,
            Center,
            Right
        }
ResizeModeY
enum MelloMario.Objects.BaseGameObject.ResizeModeY [strong], [protected]
Enumerator
Top
Center
Bottom
Definition at line 120 of file BaseGameObject.cs.
        {
            Top,
            Center,
            Bottom
        }
Constructor & Destructor Documentation
BaseGameObject()
MelloMario.Objects.BaseGameObject.BaseGameObject (IWorld world, Point location, Point size) [protected]
Definition at line 21 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Add(), MelloMario.Objects.BaseGameObject.Boundary, MelloMario.Objects.BaseGameObject.location, and MelloMario.Objects.BaseGameObject.size.
        {
            this.location = location;
            this.size = size;
            World = world;
            World.Add(this);
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseGameObject.Draw (int time, SpriteBatch spriteBatch)
Implements MelloMario.IObject .
Definition at line 45 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.Boundary, MelloMario.ISprite.Draw(), MelloMario.Objects.BaseGameObject.OnDraw(), MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            if (sprite != null)
            {
                OnDraw(time, spriteBatch);
                sprite.Draw(time, spriteBatch, new Rectangle(Boundary.Location,
      Boundary.Size));
            }
        }
HideSprite()
void MelloMario.Objects.BaseGameObject.HideSprite () [protected]
Definition at line 108 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Blocks.Floor.Floor(), MelloMario.Objects.Blocks.Stair.Stair(), MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
        {
            sprite = null;
        }
OnDraw()
abstract void MelloMario.Objects.BaseGameObject.OnDraw (int time, SpriteBatch spriteBatch) [protected], [pure virtual]
Implemented in MelloMario.Objects.Characters.Mario , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Items.Star , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Blocks.Floor , MelloMario.Objects.Blocks.Stair , MelloMario.Objects.Miscs.Background , MelloMario.Objects.UserInterfaces.PopingUpPoints , and MelloMario.Objects.Items.FireBall .
Referenced by MelloMario.Objects.BaseGameObject.Draw().
OnSimulation()
abstract void MelloMario.Objects.BaseGameObject.OnSimulation (int time) [protected], [pure virtual]
Implemented in MelloMario.Objects.Characters.MarioCharacter , MelloMario.Objects.BaseCollidableObject , MelloMario.Objects.Characters.Mario , MelloMario.Objects.BasePhysicalObject , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.Star , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Miscs.Background , MelloMario.Objects.UserInterfaces.PopingUpPoints , and MelloMario.Objects.Items.FireBall .
Referenced by MelloMario.Objects.BaseGameObject.Draw(), and MelloMario.Objects.BaseGameObject.Update().
OnUpdate()
abstract void MelloMario.Objects.BaseGameObject.OnUpdate (int time) [protected], [pure virtual]
Implemented in MelloMario.Objects.Characters.MarioCharacter , MelloMario.Objects.Characters.Mario , MelloMario.Objects.Blocks.Brick , MelloMario.Objects.Items.SuperMushroom , MelloMario.Objects.Blocks.Question , MelloMario.Objects.Items.Coin , MelloMario.Objects.Enemies.Koopa , MelloMario.Objects.Items.FireFlower , MelloMario.Objects.Items.Star , MelloMario.Objects.Enemies.Piranha , MelloMario.Objects.Items.OneUpMushroom , MelloMario.Objects.Enemies.Goomba , MelloMario.Objects.Enemies.Thwomp , MelloMario.Objects.Blocks.Pipeline , MelloMario.Objects.Blocks.Flag , MelloMario.Objects.Blocks.Floor , MelloMario.Objects.Blocks.Stair , MelloMario.Objects.Miscs.Background , MelloMario.Objects.Items.FireBall , and MelloMario.Objects.UserInterfaces.PopingUpPoints .
Referenced by MelloMario.Objects.BaseGameObject.Draw(), and MelloMario.Objects.BaseGameObject.Update().
Relocate()
void MelloMario.Objects.BaseGameObject.Relocate (Point newLocation) [protected]
Definition at line 59 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseGameObject.Resize().
        {
            location = newLocation;
        }
Resize()
void MelloMario.Objects.BaseGameObject.Resize (Point newSize, ResizeModeX modeX, ResizeModeY modeY) [protected]
Definition at line 64 of file BaseGameObject.cs.
References MelloMario.IContainer< T >.Move(), and MelloMario.Objects.BaseGameObject.Relocate().
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
        {
            Point delta = new Point();
            switch (modeX)
            {
                case ResizeModeX.Left:
                    delta.X = 0;
                    break;
                case ResizeModeX.Center:
                    delta.X = (size.X - newSize.X) / 2;
                    break;
                case ResizeModeX.Right:
                    delta.X = size.X - newSize.X;
                    break;
            }
            switch (modeY)
            {
                case ResizeModeY.Top:
                    delta.Y = 0;
                    break;
                case ResizeModeY.Center:
                    delta.Y = (size.Y - newSize.Y) / 2;
                    break;
                case ResizeModeY.Bottom:
                    delta.Y = size.Y - newSize.Y;
                    break;
            }
            Relocate(location + delta);
            size = newSize;
            World.Move(this);
        }
ShowSprite()
void MelloMario.Objects.BaseGameObject.ShowSprite (ISprite newSprite, ResizeModeX modeX = ResizeModeX.Center, ResizeModeY modeY = ResizeModeY.Bottom) [protected]
Definition at line 99 of file BaseGameObject.cs.
References MelloMario.ISprite.PixelSize, and MelloMario.Objects.BaseGameObject.Resize().
Referenced by MelloMario.Objects.Items.FireBall.FireBall(), MelloMario.Objects.Enemies.Piranha.Piranha(), MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints(), MelloMario.Objects.Miscs.Background.UpdateSprite(), MelloMario.Objects.Blocks.Floor.UpdateSprite(), MelloMario.Objects.Blocks.Stair.UpdateSprite(), MelloMario.Objects.Blocks.Flag.UpdateSprite(), MelloMario.Objects.Blocks.Pipeline.UpdateSprite(), MelloMario.Objects.Enemies.Koopa.UpdateSprite(), MelloMario.Objects.Enemies.Thwomp.UpdateSprite(), MelloMario.Objects.Enemies.Goomba.UpdateSprite(), MelloMario.Objects.Items.OneUpMushroom.UpdateSprite(), MelloMario.Objects.Blocks.Question.UpdateSprite(), MelloMario.Objects.Items.Star.UpdateSprite(), MelloMario.Objects.Items.FireFlower.UpdateSprite(), MelloMario.Objects.Blocks.Brick.UpdateSprite(), MelloMario.Objects.Items.Coin.UpdateSprite(), MelloMario.Objects.Items.SuperMushroom.UpdateSprite(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
        {
            sprite = newSprite;
            Resize(sprite.PixelSize, modeX, modeY);
        }
Update()
void MelloMario.Objects.BaseGameObject.Update (int time)
Implements MelloMario.IObject .
Definition at line 37 of file BaseGameObject.cs.
References MelloMario.Objects.BaseGameObject.OnSimulation(), and MelloMario.Objects.BaseGameObject.OnUpdate().
        {
            // override OnUpdate for states etc.
            OnUpdate(time);
            // override OnSimulation for movement and collision
            OnSimulation(time);
        }
Member Data Documentation
location
Point MelloMario.Objects.BaseGameObject.location [private]
Definition at line 14 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.BaseGameObject.BaseGameObject(), and MelloMario.Objects.BaseCollidableObject.OnSimulation().
size
Point MelloMario.Objects.BaseGameObject.size [private]
Definition at line 15 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.BaseGameObject.BaseGameObject().
sprite
 ISprite MelloMario.Objects.BaseGameObject.sprite [private]
Definition at line 16 of file BaseGameObject.cs.
World
 IWorld MelloMario.Objects.BaseGameObject.World [protected]
Definition at line 19 of file BaseGameObject.cs.
Property Documentation
Boundary
Rectangle MelloMario.Objects.BaseGameObject.Boundary [get]
Definition at line 30 of file BaseGameObject.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.BaseGameObject.BaseGameObject(), MelloMario.Objects.Items.FireFlower.Collect(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Items.Star.Collect(), MelloMario.Objects.Items.SuperMushroom.Collect(), MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Objects.Enemies.Piranha.Defeat(), MelloMario.Objects.Enemies.Goomba.Defeat(), MelloMario.Objects.Enemies.Thwomp.Defeat(), MelloMario.Objects.Enemies.Koopa.Defeat(), MelloMario.Objects.Enemies.Piranha.DetectMario(), MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.Items.SuperMushroom.GetFireFlower(), MelloMario.Objects.Enemies.PiranhaStates.MovingDown.MovingDown(), MelloMario.Objects.Enemies.PiranhaStates.MovingUp.MovingUp(), MelloMario.Objects.Blocks.Flag.OnCollision(), MelloMario.Objects.Blocks.Pipeline.OnCollision(), MelloMario.Objects.Characters.Mario.OnCollision(), MelloMario.Objects.BaseCollidableObject.OnSimulation(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), MelloMario.Objects.Blocks.Pipeline.OnUpdate(), MelloMario.Objects.BaseCollidableObject.ScanCollideModes(), and MelloMario.Objects.Characters.MarioCharacter.Teleport().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/BaseClasses/Objects/ BaseGameObject.cs