MelloMario.Containers.BaseContainer< Key, Value > Class Template Reference
Public Member Functions
void Add (Value value)
void Move (Value value)
void Remove (Value value)
void Update ()
Protected Member Functions
 BaseContainer ()
abstract Key GetKey (Value value)
IEnumerable< Value > Scan (Key key)
IEnumerable< Key > ScanKeys ()
IEnumerable< Value > ScanValues ()
Private Member Functions
void DoAdd (Value value)
void DoRemove (Value value)
Private Attributes
readonly IDictionary< Value, Key > keys
readonly IDictionary< Key, ISet< Value > > values
readonly ISet< Value > toAdd
readonly ISet< Value > toMove
readonly ISet< Value > toRemove
Detailed Description
Definition at line 12 of file BaseContainer.cs.
Constructor & Destructor Documentation
BaseContainer()
 MelloMario.Containers.BaseContainer< Key, Value >. BaseContainer () [protected]
Definition at line 21 of file BaseContainer.cs.
        {
            keys = new Dictionary<Value, Key>();
            values = new Dictionary<Key, ISet<Value>>();
            toAdd = new HashSet<Value>();
            toMove = new HashSet<Value>();
            toRemove = new HashSet<Value>();
        }
Member Function Documentation
Add()
void MelloMario.Containers.BaseContainer< Key, Value >.Add (Value value)
Definition at line 78 of file BaseContainer.cs.
Referenced by MelloMario.Theming.Player.Init(), MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.Blocks.Question.ReleaseNextItem(), and MelloMario.Objects.Blocks.Brick.ReleaseNextItem().
        {
            toAdd.Add(value);
        }
DoAdd()
void MelloMario.Containers.BaseContainer< Key, Value >.DoAdd (Value value) [private]
Definition at line 30 of file BaseContainer.cs.
Referenced by MelloMario.Containers.BaseContainer< IWorld, IPlayer >.Update().
        {
            Key key = GetKey(value);
            if (!values.ContainsKey(key))
            {
                values.Add(key, new HashSet<Value>());
            }
            keys.Add(value, key);
            values[key].Add(value);
        }
DoRemove()
void MelloMario.Containers.BaseContainer< Key, Value >.DoRemove (Value value) [private]
Definition at line 43 of file BaseContainer.cs.
Referenced by MelloMario.Containers.BaseContainer< IWorld, IPlayer >.Update().
        {
            Key key = keys[value];
            keys.Remove(value);
            values[key].Remove(value);
        }
GetKey()
abstract Key MelloMario.Containers.BaseContainer< Key, Value >.GetKey (Value value) [protected], [pure virtual]
Referenced by MelloMario.Containers.BaseContainer< IWorld, IPlayer >.DoAdd(), and MelloMario.Containers.BaseContainer< IWorld, IPlayer >.DoRemove().
Move()
void MelloMario.Containers.BaseContainer< Key, Value >.Move (Value value)
Definition at line 83 of file BaseContainer.cs.
Referenced by MelloMario.Objects.BaseCollidableObject.Move(), and MelloMario.Theming.Player.Spawn().
        {
            toMove.Add(value);
        }
Remove()
void MelloMario.Containers.BaseContainer< Key, Value >.Remove (Value value)
Definition at line 88 of file BaseContainer.cs.
Referenced by MelloMario.Objects.Characters.MarioCharacter.Move(), MelloMario.Objects.UserInterfaces.PopingUpPoints.OnUpdate(), and MelloMario.Objects.BaseCollidableObject.RemoveSelf().
        {
            toRemove.Add(value);
        }
Scan()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.Scan (Key key) [protected]
Definition at line 53 of file BaseContainer.cs.
        {
            if (values.ContainsKey(key))
            {
                return values[key];
            }
            return Enumerable.Empty<Value>();
        }
ScanKeys()
IEnumerable<Key> MelloMario.Containers.BaseContainer< Key, Value >.ScanKeys () [protected]
Definition at line 62 of file BaseContainer.cs.
        {
            return values.Keys;
        }
ScanValues()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.ScanValues () [protected]
Definition at line 67 of file BaseContainer.cs.
        {
            foreach (ISet<Value> value in values.Values)
            {
                foreach (Value item in value)
                {
                    yield return item;
                }
            }
        }
Update()
void MelloMario.Containers.BaseContainer< Key, Value >.Update ()
Definition at line 93 of file BaseContainer.cs.
Referenced by MelloMario.Objects.Blocks.Question.ReleaseNextItem(), and MelloMario.Objects.Blocks.Brick.ReleaseNextItem().
        {
            foreach (Value value in toAdd)
            {
                if (!keys.ContainsKey(value))
                {
                    DoAdd(value);
                }
            }
            toAdd.Clear();
            foreach (Value value in toMove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                    DoAdd(value);
                }
            }
            toMove.Clear();
            foreach (Value value in toRemove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                }
            }
            toRemove.Clear();
        }
Member Data Documentation
keys
readonly IDictionary<Value, Key> MelloMario.Containers.BaseContainer< Key, Value >.keys [private]
Definition at line 14 of file BaseContainer.cs.
toAdd
readonly ISet<Value> MelloMario.Containers.BaseContainer< Key, Value >.toAdd [private]
Definition at line 17 of file BaseContainer.cs.
toMove
readonly ISet<Value> MelloMario.Containers.BaseContainer< Key, Value >.toMove [private]
Definition at line 18 of file BaseContainer.cs.
toRemove
readonly ISet<Value> MelloMario.Containers.BaseContainer< Key, Value >.toRemove [private]
Definition at line 19 of file BaseContainer.cs.
values
readonly IDictionary<Key, ISet<Value> > MelloMario.Containers.BaseContainer< Key, Value >.values [private]
Definition at line 15 of file BaseContainer.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/BaseClasses/Containers/ BaseContainer.cs