MelloMario.Containers.World Class Reference
Public Member Functions
 World (string id, WorldType type, Point size, IEnumerable< Point > respawn)
void Extend (int left, int right, int top, int bottom)
IEnumerable< IGameObject > ScanNearby (Rectangle range)
Point GetRespawnPoint (Point location)
void Add (Value value)
void Move (Value value)
void Remove (Value value)
void Update ()
void Add (T value)
void Move (T value)
void Remove (T value)
void Update ()
Protected Member Functions
override Point GetKey (IGameObject value)
abstract Key GetKey (Value value)
IEnumerable< Value > Scan (Key key)
IEnumerable< Key > ScanKeys ()
IEnumerable< Value > ScanValues ()
Properties
string ID [get]
 WorldType Type [get]
Rectangle Boundary [get, private set]
Private Attributes
readonly ISet< Point > respawnPoints
Detailed Description
Definition at line 13 of file World.cs.
Constructor & Destructor Documentation
World()
MelloMario.Containers.World.World (string id, WorldType type, Point size, IEnumerable< Point > respawn)
Definition at line 17 of file World.cs.
References MelloMario.Containers.World.Boundary, MelloMario.Theming.Const.GRID, MelloMario.Containers.World.ID, and MelloMario.Containers.World.Type.
        {
            ID = id;
            Type = type;
            Boundary = new Rectangle(0, 0, size.X * Const.GRID, size.Y * Const.GRID);
            respawnPoints = new HashSet<Point>();
            foreach (Point p in respawn)
            {
                respawnPoints.Add(new Point(p.X * Const.GRID, p.Y * Const.GRID));
            }
        }
Member Function Documentation
Add() [1/2]
void MelloMario.IContainer< T >.Add (T value) [inherited]
Add() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Add (Value value) [inherited]
Definition at line 78 of file BaseContainer.cs.
        {
            toAdd.Add(value);
        }
Extend()
void MelloMario.Containers.World.Extend (int left, int right, int top, int bottom)
Implements MelloMario.IWorld .
Definition at line 34 of file World.cs.
References MelloMario.Containers.World.Boundary.
        {
            Boundary = new Rectangle(Boundary.Left - left, Boundary.Top - top,
      Boundary.Width + left + right, Boundary.Height + top + bottom);
        }
GetKey() [1/2]
abstract Key MelloMario.Containers.BaseContainer< Key, Value >.GetKey (Value value) [protected], [pure virtual], [inherited]
GetKey() [2/2]
override Point MelloMario.Containers.World.GetKey (IGameObject value) [protected]
Definition at line 73 of file World.cs.
References MelloMario.IGameObject.Boundary, and MelloMario.Theming.Const.GRID.
        {
            Point center = value.Boundary.Center;
            return new Point(center.X / Const.GRID, center.Y / Const.GRID);
        }
GetRespawnPoint()
Point MelloMario.Containers.World.GetRespawnPoint (Point location)
Implements MelloMario.IWorld .
Definition at line 58 of file World.cs.
        {
            Point target = location;
            foreach (Point p in respawnPoints)
            {
                if (p.X <= location.X && p.X > target.X)
                {
                    target = p;
                }
            }
            return target;
        }
Move() [1/2]
void MelloMario.IContainer< T >.Move (T value) [inherited]
Move() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Move (Value value) [inherited]
Definition at line 83 of file BaseContainer.cs.
        {
            toMove.Add(value);
        }
Remove() [1/2]
void MelloMario.IContainer< T >.Remove (T value) [inherited]
Remove() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Remove (Value value) [inherited]
Definition at line 88 of file BaseContainer.cs.
        {
            toRemove.Add(value);
        }
Scan()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.Scan (Key key) [protected], [inherited]
Definition at line 53 of file BaseContainer.cs.
Referenced by MelloMario.Containers.World::ScanNearby().
        {
            if (values.ContainsKey(key))
            {
                return values[key];
            }
            return Enumerable.Empty<Value>();
        }
ScanKeys()
IEnumerable<Key> MelloMario.Containers.BaseContainer< Key, Value >.ScanKeys () [protected], [inherited]
Definition at line 62 of file BaseContainer.cs.
        {
            return values.Keys;
        }
ScanNearby()
IEnumerable< IGameObject> MelloMario.Containers.World.ScanNearby (Rectangle range)
Implements MelloMario.IWorld .
Definition at line 39 of file World.cs.
References MelloMario.Theming.Const.GRID, MelloMario.Containers.BaseContainer< Point, IGameObject >.Scan(), and MelloMario.Theming.Const.SCANRANGE.
Referenced by MelloMario.Objects.BaseCollidableObject.CollideAll(), and MelloMario.Objects.Enemies.Piranha.DetectMario().
        {
            int left = (range.Left - Const.SCANRANGE) / Const.GRID;
            int right = (range.Right + Const.SCANRANGE) / Const.GRID;
            int top = (range.Top - Const.SCANRANGE) / Const.GRID;
            int bottom = (range.Bottom + Const.SCANRANGE) / Const.GRID;
            for (int i = left; i <= right; ++i)
            {
                for (int j = top; j <= bottom; ++j)
                {
                    foreach (IGameObject obj in Scan(new Point(i, j)))
                    {
                        yield return obj;
                    }
                }
            }
        }
ScanValues()
IEnumerable<Value> MelloMario.Containers.BaseContainer< Key, Value >.ScanValues () [protected], [inherited]
Definition at line 67 of file BaseContainer.cs.
        {
            foreach (ISet<Value> value in values.Values)
            {
                foreach (Value item in value)
                {
                    yield return item;
                }
            }
        }
Update() [1/2]
void MelloMario.IContainer< T >.Update () [inherited]
Update() [2/2]
void MelloMario.Containers.BaseContainer< Key, Value >.Update () [inherited]
Definition at line 93 of file BaseContainer.cs.
        {
            foreach (Value value in toAdd)
            {
                if (!keys.ContainsKey(value))
                {
                    DoAdd(value);
                }
            }
            toAdd.Clear();
            foreach (Value value in toMove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                    DoAdd(value);
                }
            }
            toMove.Clear();
            foreach (Value value in toRemove)
            {
                if (keys.ContainsKey(value))
                {
                    DoRemove(value);
                }
            }
            toRemove.Clear();
        }
Member Data Documentation
respawnPoints
readonly ISet<Point> MelloMario.Containers.World.respawnPoints [private]
Definition at line 15 of file World.cs.
Property Documentation
Boundary
Rectangle MelloMario.Containers.World.Boundary [get], [private set]
Definition at line 32 of file World.cs.
Referenced by MelloMario.Objects.BaseCollidableObject.CollideAll(), MelloMario.Containers.World.Extend(), and MelloMario.Containers.World.World().
ID
string MelloMario.Containers.World.ID [get]
Definition at line 30 of file World.cs.
Referenced by MelloMario.Containers.World.World().
Type
 WorldType MelloMario.Containers.World.Type [get]
Definition at line 31 of file World.cs.
Referenced by MelloMario.Containers.World.World().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Containers/ World.cs