MelloMario.Sounds.BGMManager Class Reference
Public Member Functions
 BGMManager (IModel model)
void ToggleMute ()
void Update ()
Private Member Functions
void PlayMusic (ISoundTrack track)
void UpdatePausing ()
void UpdateBGM ()
Static Private Member Functions
static void Pause ()
static void Resume ()
Private Attributes
readonly IModel model
 ISoundTrack currentTrack
Static Private Attributes
static readonly ISoundTrack Normal = SoundFactory.Instance.CreateSoundTrack(`Normal`)
static readonly ISoundTrack Hurry = SoundFactory.Instance.CreateSoundTrack(`Hurry`)
static readonly ISoundTrack BelowGround = SoundFactory.Instance.CreateSoundTrack(`BelowGround`)
static readonly ISoundTrack Star = SoundFactory.Instance.CreateSoundTrack(`Star`)
Detailed Description
Definition at line 12 of file BGMManager.cs.
Constructor & Destructor Documentation
BGMManager()
MelloMario.Sounds.BGMManager.BGMManager (IModel model)
Definition at line 23 of file BGMManager.cs.
References MelloMario.Sounds.BGMManager.model.
        {
            this.model = model;
        }
Member Function Documentation
Pause()
static void MelloMario.Sounds.BGMManager.Pause () [static], [private]
Definition at line 45 of file BGMManager.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdatePausing().
        {
            MediaPlayer.Pause();
        }
PlayMusic()
void MelloMario.Sounds.BGMManager.PlayMusic (ISoundTrack track) [private]
Definition at line 28 of file BGMManager.cs.
References MelloMario.ISoundTrack.Play().
Referenced by MelloMario.Sounds.BGMManager.UpdateBGM().
        {
            if (track == currentTrack && MediaPlayer.State != MediaState.Stopped)
            {
                return;
            }
            MediaPlayer.Stop();
            track?.Play();
            MediaPlayer.IsRepeating = true;
            currentTrack = track;
        }
Resume()
static void MelloMario.Sounds.BGMManager.Resume () [static], [private]
Definition at line 50 of file BGMManager.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdatePausing().
        {
            MediaPlayer.Resume();
        }
ToggleMute()
void MelloMario.Sounds.BGMManager.ToggleMute ()
Definition at line 40 of file BGMManager.cs.
Referenced by MelloMario.Game1.ToggleMute().
        {
            MediaPlayer.IsMuted = !MediaPlayer.IsMuted;
        }
Update()
void MelloMario.Sounds.BGMManager.Update ()
Definition at line 98 of file BGMManager.cs.
References MelloMario.Sounds.BGMManager.UpdateBGM(), and MelloMario.Sounds.BGMManager.UpdatePausing().
Referenced by MelloMario.Game1.Update().
        {
            UpdatePausing();
            UpdateBGM();
        }
UpdateBGM()
void MelloMario.Sounds.BGMManager.UpdateBGM () [private]
Definition at line 72 of file BGMManager.cs.
References MelloMario.Objects.Characters.MarioCharacter.CurrentWorld, MelloMario.Objects.Characters.MarioCharacter.Player, MelloMario.Sounds.BGMManager.PlayMusic(), MelloMario.Objects.Characters.Mario.ProtectionState, MelloMario.IPlayer.TimeRemain, and MelloMario.IWorld.Type.
Referenced by MelloMario.Sounds.BGMManager.Update().
        {
            //BGM Updater
            switch (model.ActivePlayer.Character)
            {
                case MarioCharacter mario when mario.ProtectionState is Dead:
                    MediaPlayer.Stop();
                    break;
                case MarioCharacter mario when mario.ProtectionState is Starred:
                    PlayMusic(Star);
                    break;
                case MarioCharacter mario when mario.Player.TimeRemain <= 90000:
                    PlayMusic(Hurry);
                    break;
                case MarioCharacter mario when mario.CurrentWorld.Type ==
      WorldType.normal:
                    PlayMusic(Normal);
                    break;
                case MarioCharacter mario when mario.CurrentWorld.Type ==
      WorldType.underground:
                    PlayMusic(BelowGround);
                    break;
                default:
                    PlayMusic(Normal);
                    break;
            }
        }
UpdatePausing()
void MelloMario.Sounds.BGMManager.UpdatePausing () [private]
Definition at line 55 of file BGMManager.cs.
References MelloMario.Sounds.BGMManager.Pause(), and MelloMario.Sounds.BGMManager.Resume().
Referenced by MelloMario.Sounds.BGMManager.Update().
        {
            //Pausing state detector
            if (model.IsPaused)
            {
                //Avoid repeat pausing
                if (MediaPlayer.State != MediaState.Paused)
                {
                    Pause();
                }
            }
            else if (MediaPlayer.State == MediaState.Paused)
            {
                Resume();
            }
        }
Member Data Documentation
BelowGround
readonly ISoundTrack MelloMario.Sounds.BGMManager.BelowGround = SoundFactory.Instance.CreateSoundTrack(`BelowGround`) [static], [private]
Definition at line 18 of file BGMManager.cs.
currentTrack
 ISoundTrack MelloMario.Sounds.BGMManager.currentTrack [private]
Definition at line 21 of file BGMManager.cs.
Hurry
readonly ISoundTrack MelloMario.Sounds.BGMManager.Hurry = SoundFactory.Instance.CreateSoundTrack(`Hurry`) [static], [private]
Definition at line 17 of file BGMManager.cs.
model
readonly IModel MelloMario.Sounds.BGMManager.model [private]
Definition at line 14 of file BGMManager.cs.
Referenced by MelloMario.Sounds.BGMManager.BGMManager().
Normal
readonly ISoundTrack MelloMario.Sounds.BGMManager.Normal = SoundFactory.Instance.CreateSoundTrack(`Normal`) [static], [private]
Definition at line 16 of file BGMManager.cs.
Star
readonly ISoundTrack MelloMario.Sounds.BGMManager.Star = SoundFactory.Instance.CreateSoundTrack(`Star`) [static], [private]
Definition at line 19 of file BGMManager.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Sounds/ BGMManager.cs