MelloMario.LevelGen.JsonGenerator Class Reference
Public Member Functions
 JsonGenerator (string jsonPath, string id, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
void Request (Rectangle range, IWorld world)
Static Private Member Functions
static IEnumerable< IGameObject > GetObjs (string jsonPath, string id, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Detailed Description
Definition at line 12 of file JsonGenerator.cs.
Constructor & Destructor Documentation
JsonGenerator()
MelloMario.LevelGen.JsonGenerator.JsonGenerator (string jsonPath, string id, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Definition at line 25 of file JsonGenerator.cs.
                                                                                                           
                          :
            base(GetObjs(jsonPath, id, listener, soundListener))
        {
        }
Member Function Documentation
GetObjs()
static IEnumerable< IGameObject> MelloMario.LevelGen.JsonGenerator.GetObjs (string jsonPath, string id, IListener< IGameObject > listener, IListener< ISoundable > soundListener) [static], [private]
Definition at line 14 of file JsonGenerator.cs.
References MelloMario.IWorld.Boundary, MelloMario.LevelGen.JsonConverters.LevelIOJson.Load(), and MelloMario.IWorld.ScanNearby().
        {
            LevelIOJson reader = new LevelIOJson(jsonPath, listener, soundListener);
            IWorld world = reader.Load(id);
            return world.ScanNearby(world.Boundary);
        }
Request()
void MelloMario.LevelGen.StaticGenerator.Request (Rectangle range, IWorld world) [inherited]
Implements MelloMario.ILevelGenerator .
Definition at line 20 of file StaticGenerator.cs.
References MelloMario.IContainer< T >.Add(), MelloMario.IGameObject.Boundary, MelloMario.IWorld.Boundary, and MelloMario.IWorld.Extend().
        {
            if (objects != null)
            {
                foreach (IGameObject obj in objects)
                {
                    world.Extend(
                        Math.Max(world.Boundary.Left - obj.Boundary.Left, 0),
                        Math.Max(obj.Boundary.Right - world.Boundary.Right, 0),
                        Math.Max(world.Boundary.Top - obj.Boundary.Top, 0),
                        Math.Max(obj.Boundary.Bottom - world.Boundary.Bottom, 0));
                    world.Add(obj);
                }
                objects = null;
            }
        }
The documentation for this class was generated from the following file:
MelloMario/MelloMario/LevelGen/ JsonGenerator.cs