MelloMario.Theming.GameModel Class Reference
Public Member Functions
 GameModel (Game1 game)
void ToggleFullScreen ()
void Pause ()
void Init ()
void Resume ()
void Reset ()
void Quit ()
void Infinite ()
void Normal ()
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
void ToggleMute ()
void LoadControllers (IEnumerable< IController > newControllers)
 IWorld LoadLevel (string id)
void Transist ()
void TransistGameWon ()
Public Attributes
 IObject Splash
Properties
bool IsPaused [get, private set]
Matrix GetActiveViewMatrix [get]
 IPlayer ActivePlayer [get]
Private Member Functions
void UpdateController ()
void UpdateGameObjects (int time)
void UpdateContainers ()
Private Attributes
readonly Game1 game
readonly IListener< IGameObject > listener
readonly IListener< ISoundable > soundListener
readonly Session session
IEnumerable< IController > controllers
string mapPath = `Content/Level1.json`
int splashElapsed
Detailed Description
Definition at line 18 of file GameModel.cs.
Constructor & Destructor Documentation
GameModel()
MelloMario.Theming.GameModel.GameModel (Game1 game)
Definition at line 34 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Theming.GameModel.game, MelloMario.Theming.GameModel.GetActiveViewMatrix, and MelloMario.Theming.Database.Initialize().
        {
            this.game = game;
            session = new Session();
            ActivePlayer = new Player(session);
            listener = new ScoreListener(this, ActivePlayer);
            soundListener = new SoundEffectListener();
            Database.Initialize(session);
        }
Member Function Documentation
Draw()
void MelloMario.Theming.GameModel.Draw (int time, SpriteBatch spriteBatch)
Implements MelloMario.IModel .
Definition at line 138 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.IObject.Draw(), and MelloMario.Theming.GameModel.IsPaused.
Referenced by MelloMario.Game1.Draw().
        {
            IPlayer player = ActivePlayer;
            foreach (IGameObject obj in player.Character.CurrentWorld.ScanNearby(player.Camera.Viewport))
            {
                obj.Draw(IsPaused ? 0 : time, spriteBatch);
            }
            Splash.Draw(time, spriteBatch);
        }
Infinite()
void MelloMario.Theming.GameModel.Infinite ()
Implements MelloMario.IModel .
Definition at line 97 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.IPlayer.Init(), MelloMario.Theming.GameModel.IsPaused, MelloMario.Theming.GameModel.LoadLevel(), and MelloMario.Theming.GameModel.Resume().
        {
            mapPath = "Content/Infinite.json";
            splashElapsed = 0;
            ActivePlayer.Init("Mario", LoadLevel("Main"), listener,
      soundListener);
            IsPaused = false;
            Resume();
        }
Init()
void MelloMario.Theming.GameModel.Init ()
Implements MelloMario.IModel .
Definition at line 68 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Controls.Scripts.StartScript.Bind(), MelloMario.IPlayer.Character, and MelloMario.Theming.GameModel.IsPaused.
Referenced by MelloMario.Game1.Reset().
        {
            IsPaused = true;
            new StartScript().Bind(controllers, this, ActivePlayer.Character);
            Splash = new GameStart(ActivePlayer); // TODO: move these constructors to the factory
            splashElapsed = -1;
        }
LoadControllers()
void MelloMario.Theming.GameModel.LoadControllers (IEnumerable< IController > newControllers)
Definition at line 156 of file GameModel.cs.
Referenced by MelloMario.Game1.Reset().
        {
            controllers = newControllers;
        }
LoadLevel()
 IWorld MelloMario.Theming.GameModel.LoadLevel (string id)
Implements MelloMario.IModel .
Definition at line 161 of file GameModel.cs.
References MelloMario.IWorld.ID, and MelloMario.LevelGen.JsonConverters.LevelIOJson.Load().
Referenced by MelloMario.Theming.GameModel.Infinite(), and MelloMario.Theming.GameModel.Normal().
        {
            foreach (IWorld world in session.ScanWorlds())
            {
                if (world.ID == id)
                {
                    return world;
                }
            }
            // IWorld newWorld = new GameWorld(id, new Point(50, 20), new Point(1, 1), new List<Point>());
            LevelIOJson reader = new LevelIOJson(mapPath, listener,
      soundListener);
            IWorld newWorld = reader.Load(id);
            // generator = new JsonGenerator(mapPath, id, listener, soundListener);
            //infiniteGenerator = new InfiniteGenerator(newWorld, listener);
            return newWorld;
        }
Normal()
void MelloMario.Theming.GameModel.Normal ()
Implements MelloMario.IModel .
Definition at line 106 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.IPlayer.Init(), MelloMario.Theming.GameModel.IsPaused, MelloMario.Theming.GameModel.LoadLevel(), and MelloMario.Theming.GameModel.Resume().
        {
            mapPath = "Content/Level1.json";
            splashElapsed = 0;
            ActivePlayer.Init("Mario", LoadLevel("Main"), listener,
      soundListener);
            IsPaused = false;
            Resume();
        }
Pause()
void MelloMario.Theming.GameModel.Pause ()
Implements MelloMario.IModel .
Definition at line 60 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Controls.Scripts.PausedScript.Bind(), MelloMario.IPlayer.Character, and MelloMario.Theming.GameModel.IsPaused.
        {
            IsPaused = true;
            new PausedScript().Bind(controllers, this, ActivePlayer.Character);
            splashElapsed = -1;
        }
Quit()
void MelloMario.Theming.GameModel.Quit ()
Implements MelloMario.IModel .
Definition at line 92 of file GameModel.cs.
        {
            game.Exit();
        }
Reset()
void MelloMario.Theming.GameModel.Reset ()
Implements MelloMario.IModel .
Definition at line 85 of file GameModel.cs.
References MelloMario.Theming.GameModel.Resume().
        {
            // TODO: "forced" version of LoadLevel()
            game.Reset();
            Resume();
        }
Resume()
void MelloMario.Theming.GameModel.Resume ()
Implements MelloMario.IModel .
Definition at line 77 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Controls.Scripts.PlayingScript.Bind(), MelloMario.IPlayer.Character, and MelloMario.Theming.GameModel.IsPaused.
Referenced by MelloMario.Theming.GameModel.Infinite(), MelloMario.Theming.GameModel.Normal(), MelloMario.Theming.GameModel.Reset(), and MelloMario.Theming.GameModel.Update().
        {
            IsPaused = false;
            new PlayingScript().Bind(controllers, this, ActivePlayer.Character);
            Splash = new HUD(ActivePlayer);
        }
ToggleFullScreen()
void MelloMario.Theming.GameModel.ToggleFullScreen ()
Implements MelloMario.IModel .
Definition at line 55 of file GameModel.cs.
        {
            game.ToggleFullScreen();
        }
ToggleMute()
void MelloMario.Theming.GameModel.ToggleMute ()
Implements MelloMario.IModel .
Definition at line 150 of file GameModel.cs.
        {
            (soundListener as SoundEffectListener)?.ToggleMute();
            game.ToggleMute();
        }
Transist()
void MelloMario.Theming.GameModel.Transist ()
Implements MelloMario.IModel .
Definition at line 181 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Controls.Scripts.TransistScript.Bind(), MelloMario.IPlayer.Character, MelloMario.Theming.GameModel.IsPaused, and MelloMario.IPlayer.Reset().
        {
            ActivePlayer.Reset("Mario", listener, soundListener);
            IsPaused = true;
            new TransistScript().Bind(controllers, this, ActivePlayer.Character);
            Splash = new GameOver(ActivePlayer);
            splashElapsed = 0;
        }
TransistGameWon()
void MelloMario.Theming.GameModel.TransistGameWon ()
Implements MelloMario.IModel .
Definition at line 192 of file GameModel.cs.
References MelloMario.Theming.GameModel.ActivePlayer, MelloMario.Controls.Scripts.TransistScript.Bind(), MelloMario.IPlayer.Character, MelloMario.Theming.GameModel.IsPaused, and MelloMario.IPlayer.Win().
        {
            ActivePlayer.Win();
            IsPaused = true;
            new TransistScript().Bind(controllers, this, ActivePlayer.Character);
            Splash = new GameWon(ActivePlayer);
            splashElapsed = -1;
        }
Update()
void MelloMario.Theming.GameModel.Update (int time)
Implements MelloMario.IModel .
Definition at line 115 of file GameModel.cs.
References MelloMario.Theming.GameModel.IsPaused, MelloMario.Theming.GameModel.Resume(), MelloMario.Theming.Database.Update(), MelloMario.Theming.GameModel.UpdateContainers(), MelloMario.Theming.GameModel.UpdateController(), and MelloMario.Theming.GameModel.UpdateGameObjects().
Referenced by MelloMario.Game1.Update().
        {
            UpdateController();
            Database.Update();
            if (IsPaused)
            {
                if (splashElapsed < 0)
                {
                    return;
                }
                splashElapsed += time;
                if (splashElapsed >= 1000 * 2)
                {
                    Resume();
                }
                return;
            }
            //TODO: Pause state should not stop updating camera
            UpdateGameObjects(time);
            UpdateContainers();
        }
UpdateContainers()
void MelloMario.Theming.GameModel.UpdateContainers () [private]
Definition at line 233 of file GameModel.cs.
References MelloMario.IContainer< T >.Update().
Referenced by MelloMario.Theming.GameModel.Update().
        {
            session.Update();
            foreach (IWorld world in session.ScanWorlds())
            {
                world.Update();
            }
        }
UpdateController()
void MelloMario.Theming.GameModel.UpdateController () [private]
Definition at line 203 of file GameModel.cs.
References MelloMario.IController.Update().
Referenced by MelloMario.Theming.GameModel.Update().
        {
            foreach (IController controller in controllers)
            {
                controller.Update();
            }
        }
UpdateGameObjects()
void MelloMario.Theming.GameModel.UpdateGameObjects (int time) [private]
Definition at line 211 of file GameModel.cs.
References MelloMario.IPlayer.Character, MelloMario.ICharacter.CurrentWorld, MelloMario.IWorld.ScanNearby(), MelloMario.ICharacter.Sensing, MelloMario.IObject.Update(), and MelloMario.IPlayer.Update().
Referenced by MelloMario.Theming.GameModel.Update().
        {
            // reserved for multiplayer
            ISet<IObject> updating = new HashSet<IObject>();
            foreach (IPlayer player in session.ScanPlayers())
            {
                player.Update(time);
                foreach (IGameObject obj in player.Character.CurrentWorld.ScanNearby(player.Character.
      Sensing))
                {
                    updating.Add(obj);
                }
            }
            updating.Add(Splash);
            foreach (IObject obj in updating)
            {
                obj.Update(time);
            }
        }
Member Data Documentation
controllers
IEnumerable< IController> MelloMario.Theming.GameModel.controllers [private]
Definition at line 24 of file GameModel.cs.
game
readonly Game1 MelloMario.Theming.GameModel.game [private]
Definition at line 20 of file GameModel.cs.
Referenced by MelloMario.Theming.GameModel.GameModel().
listener
readonly IListener< IGameObject> MelloMario.Theming.GameModel.listener [private]
Definition at line 21 of file GameModel.cs.
mapPath
string MelloMario.Theming.GameModel.mapPath = `Content/Level1.json` [private]
Definition at line 25 of file GameModel.cs.
session
readonly Session MelloMario.Theming.GameModel.session [private]
Definition at line 23 of file GameModel.cs.
soundListener
readonly IListener< ISoundable> MelloMario.Theming.GameModel.soundListener [private]
Definition at line 22 of file GameModel.cs.
Splash
 IObject MelloMario.Theming.GameModel.Splash
Definition at line 30 of file GameModel.cs.
splashElapsed
int MelloMario.Theming.GameModel.splashElapsed [private]
Definition at line 32 of file GameModel.cs.
Property Documentation
ActivePlayer
 IPlayer MelloMario.Theming.GameModel.ActivePlayer [get]
Definition at line 53 of file GameModel.cs.
Referenced by MelloMario.Theming.GameModel.Draw(), MelloMario.Theming.GameModel.GameModel(), MelloMario.Theming.GameModel.Infinite(), MelloMario.Theming.GameModel.Init(), MelloMario.Theming.GameModel.Normal(), MelloMario.Theming.GameModel.Pause(), MelloMario.Theming.GameModel.Resume(), MelloMario.Theming.GameModel.Transist(), and MelloMario.Theming.GameModel.TransistGameWon().
GetActiveViewMatrix
Matrix MelloMario.Theming.GameModel.GetActiveViewMatrix [get]
Definition at line 45 of file GameModel.cs.
Referenced by MelloMario.Game1.Draw(), and MelloMario.Theming.GameModel.GameModel().
IsPaused
bool MelloMario.Theming.GameModel.IsPaused [get], [private set]
Definition at line 26 of file GameModel.cs.
Referenced by MelloMario.Theming.GameModel.Draw(), MelloMario.Theming.GameModel.Infinite(), MelloMario.Theming.GameModel.Init(), MelloMario.Theming.GameModel.Normal(), MelloMario.Theming.GameModel.Pause(), MelloMario.Theming.GameModel.Resume(), MelloMario.Theming.GameModel.Transist(), MelloMario.Theming.GameModel.TransistGameWon(), and MelloMario.Theming.GameModel.Update().
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Theming/ GameModel.cs