MelloMario.Objects.UserInterfaces.GameStart Class Reference
Public Member Functions
 GameStart (IPlayer player)
void Update (int time)
void Draw (int time, SpriteBatch spriteBatch)
Protected Member Functions
override void OnUpdate (int time)
override void OnDraw (int time, SpriteBatch spriteBatch)
void Offset (ref Rectangle rect)
void UpdateOrigin ()
Protected Attributes
 IPlayer Player
Point RelativeOrigin
Private Attributes
readonly ISprite startSprite
readonly ISprite textSprite
Rectangle startDestinationRect
Rectangle textDestinationRect
Detailed Description
Definition at line 11 of file GameStart.cs.
Constructor & Destructor Documentation
GameStart()
MelloMario.Objects.UserInterfaces.GameStart.GameStart (IPlayer player)
Definition at line 18 of file GameStart.cs.
References MelloMario.ISpriteFactory< T >.CreateTextSprite(), MelloMario.ISpriteFactory< T >.CreateTitle(), and MelloMario.Factories.SpriteFactory.Instance.
                                         : base(player)
        {
            startSprite = SpriteFactory.Instance.CreateTitle(ZIndex.Hud);
            textSprite = SpriteFactory.Instance.CreateTextSprite(
                "Mellop\n" + "Press A to play normal mode.\n" + "Press B to play infinite mode.");
            startDestinationRect = new Rectangle(100, 100, 352, 176);
            textDestinationRect = new Rectangle(0, 400, 200, 200);
        }
Member Function Documentation
Draw()
void MelloMario.Objects.BaseUIObject.Draw (int time, SpriteBatch spriteBatch) [inherited]
Implements MelloMario.IObject .
Definition at line 27 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnDraw().
        {
            OnDraw(time, spriteBatch);
        }
Offset()
void MelloMario.Objects.BaseUIObject.Offset (ref Rectangle rect) [protected], [inherited]
Definition at line 32 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            rect.Offset(Player.Camera.Viewport.Location - RelativeOrigin);
        }
OnDraw()
override void MelloMario.Objects.UserInterfaces.GameStart.OnDraw (int time, SpriteBatch spriteBatch) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 34 of file GameStart.cs.
        {
            startSprite.Draw(time, spriteBatch, startDestinationRect);
            textSprite.Draw(time, spriteBatch, textDestinationRect);
        }
OnUpdate()
override void MelloMario.Objects.UserInterfaces.GameStart.OnUpdate (int time) [protected], [virtual]
Implements MelloMario.Objects.BaseUIObject .
Definition at line 27 of file GameStart.cs.
References MelloMario.Objects.BaseUIObject.Offset(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
        {
            Offset(ref startDestinationRect);
            Offset(ref textDestinationRect);
            UpdateOrigin();
        }
Update()
void MelloMario.Objects.BaseUIObject.Update (int time) [inherited]
Implements MelloMario.IObject .
Definition at line 22 of file BaseUIObject.cs.
References MelloMario.Objects.BaseUIObject.OnUpdate().
        {
            OnUpdate(time);
        }
UpdateOrigin()
void MelloMario.Objects.BaseUIObject.UpdateOrigin () [protected], [inherited]
Definition at line 37 of file BaseUIObject.cs.
References MelloMario.IPlayer.Camera, MelloMario.Objects.BaseUIObject.OnDraw(), MelloMario.Objects.BaseUIObject.OnUpdate(), and MelloMario.ICamera.Viewport.
Referenced by MelloMario.Objects.UserInterfaces.GameStart.OnUpdate(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), MelloMario.Objects.UserInterfaces.GameWon.OnUpdate(), and MelloMario.Objects.UserInterfaces.GameOver.OnUpdate().
        {
            RelativeOrigin = Player.Camera.Viewport.Location;
        }
Member Data Documentation
Player
 IPlayer MelloMario.Objects.BaseUIObject.Player [protected], [inherited]
Definition at line 12 of file BaseUIObject.cs.
RelativeOrigin
Point MelloMario.Objects.BaseUIObject.RelativeOrigin [protected], [inherited]
Definition at line 13 of file BaseUIObject.cs.
startDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameStart.startDestinationRect [private]
Definition at line 15 of file GameStart.cs.
startSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameStart.startSprite [private]
Definition at line 13 of file GameStart.cs.
textDestinationRect
Rectangle MelloMario.Objects.UserInterfaces.GameStart.textDestinationRect [private]
Definition at line 16 of file GameStart.cs.
textSprite
readonly ISprite MelloMario.Objects.UserInterfaces.GameStart.textSprite [private]
Definition at line 14 of file GameStart.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/Objects/UserInterfaces/ GameStart.cs