MelloMario.Game1 Class Reference
This is the main type for Mello Mario game.
Public Member Functions
 Game1 ()
void ToggleFullScreen ()
void ToggleMute ()
void Reset ()
Protected Member Functions
override void Initialize ()
Allows the game to perform any initialization it needs to before starting to run. This is where it can query for any required services and load any non-graphic related content. Calling base.Initialize will enumerate through any components and initialize them as well.
override void LoadContent ()
LoadContent will be called once per game and is the place to load all of your content.
override void UnloadContent ()
UnloadContent will be called once per game and is the place to unload game-specific content.
override void Update (GameTime time)
Allows the game to run logic such as updating the World, checking for collisions, gathering input, and playing audio.
override void Draw (GameTime time)
This is called when the game should draw itself.
Private Attributes
readonly GraphicsDeviceManager graphics
 GameModel model
SpriteBatch spriteBatch
 BGMManager sounds
Detailed Description
This is the main type for Mello Mario game.
Definition at line 18 of file Game1.cs.
Constructor & Destructor Documentation
Game1()
MelloMario.Game1.Game1 ()
Definition at line 25 of file Game1.cs.
References MelloMario.Theming.Const.SCREEN_HEIGHT, and MelloMario.Theming.Const.SCREEN_WIDTH.
        {
            graphics = new GraphicsDeviceManager(this)
            {
                PreferredBackBufferWidth = Const.SCREEN_WIDTH,
                PreferredBackBufferHeight = Const.SCREEN_HEIGHT
            };
        }
Member Function Documentation
Draw()
override void MelloMario.Game1.Draw (GameTime time) [protected]
This is called when the game should draw itself.
Parameters
time Provides a snapshot of timing values.
Definition at line 112 of file Game1.cs.
References MelloMario.Theming.GameModel.Draw(), and MelloMario.Theming.GameModel.GetActiveViewMatrix.
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            base.Draw(time);
#if DEBUGSPRITE //Debug Code
            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.Opaque);
            RasterizerState state = new RasterizerState();
            state.FillMode = FillMode.WireFrame;
            spriteBatch.GraphicsDevice.RasterizerState = state;
#else
            spriteBatch.Begin(SpriteSortMode.BackToFront, null, null, null, null, null,
      model.GetActiveViewMatrix);
            //spriteBatch.Begin(SpriteSortMode.BackToFront);
#endif
            model.Draw(time.ElapsedGameTime.Milliseconds, spriteBatch);
            spriteBatch.End();
        }
Initialize()
override void MelloMario.Game1.Initialize () [protected]
Allows the game to perform any initialization it needs to before starting to run. This is where it can query for any required services and load any non-graphic related content. Calling base.Initialize will enumerate through any components and initialize them as well.
Definition at line 65 of file Game1.cs.
References MelloMario.Game1.Reset().
        {
            base.Initialize();
            //soundControl = new SoundManager(this);
            Reset();
        }
LoadContent()
override void MelloMario.Game1.LoadContent () [protected]
LoadContent will be called once per game and is the place to load all of your content.
Definition at line 77 of file Game1.cs.
References MelloMario.ISpriteFactory< T >.BindLoader(), MelloMario.ISoundFactory< T >.BindLoader(), MelloMario.Factories.SpriteFactory.Instance, and MelloMario.Factories.SoundFactory.Instance.
        {
            Content.RootDirectory = "Content";
            base.LoadContent();
            SpriteFactory.Instance.BindLoader(Content);
            SoundFactory.Instance.BindLoader(Content);
            spriteBatch = new SpriteBatch(GraphicsDevice);
        }
Reset()
void MelloMario.Game1.Reset ()
Definition at line 45 of file Game1.cs.
References MelloMario.Theming.GameModel.Init(), and MelloMario.Theming.GameModel.LoadControllers().
Referenced by MelloMario.Game1.Initialize().
        {
            model = new GameModel(this);
            IEnumerable<IController> controllers = new List<IController>
            {
                new GamepadController(),
                new KeyboardController()
            };
            model.LoadControllers(controllers);
            model.Init();
            sounds = new BGMManager(model);
        }
ToggleFullScreen()
void MelloMario.Game1.ToggleFullScreen ()
Definition at line 35 of file Game1.cs.
        {
            graphics.ToggleFullScreen();
        }
ToggleMute()
void MelloMario.Game1.ToggleMute ()
Definition at line 40 of file Game1.cs.
References MelloMario.Sounds.BGMManager.ToggleMute().
        {
            sounds.ToggleMute();
        }
UnloadContent()
override void MelloMario.Game1.UnloadContent () [protected]
UnloadContent will be called once per game and is the place to unload game-specific content.
Definition at line 91 of file Game1.cs.
        {
            base.UnloadContent();
        }
Update()
override void MelloMario.Game1.Update (GameTime time) [protected]
Allows the game to run logic such as updating the World, checking for collisions, gathering input, and playing audio.
Parameters
time Provides a snapshot of timing values.
Definition at line 101 of file Game1.cs.
References MelloMario.Sounds.BGMManager.Update(), and MelloMario.Theming.GameModel.Update().
        {
            base.Update(time);
            model.Update(time.ElapsedGameTime.Milliseconds);
            sounds.Update();
        }
Member Data Documentation
graphics
readonly GraphicsDeviceManager MelloMario.Game1.graphics [private]
Definition at line 20 of file Game1.cs.
model
 GameModel MelloMario.Game1.model [private]
Definition at line 21 of file Game1.cs.
sounds
 BGMManager MelloMario.Game1.sounds [private]
Definition at line 23 of file Game1.cs.
spriteBatch
SpriteBatch MelloMario.Game1.spriteBatch [private]
Definition at line 22 of file Game1.cs.
The documentation for this class was generated from the following file:
MelloMario/MelloMario/ Game1.cs