MelloMario.ISprite Interface Reference
Public Member Functions
void Draw (int time, SpriteBatch spriteBatch, Rectangle destination)
Properties
Point PixelSize [get]
Detailed Description
Definition at line 23 of file ISprite.cs.
Member Function Documentation
Draw()
void MelloMario.ISprite.Draw (int time, SpriteBatch spriteBatch, Rectangle destination)
Implemented in MelloMario.Graphics.Sprites.BaseSprite .
Referenced by MelloMario.Objects.BaseGameObject.Draw(), MelloMario.Objects.UserInterfaces.HUD.OnDraw(), and MelloMario.Objects.UserInterfaces.GameOver.OnDraw().
Property Documentation
PixelSize
Point MelloMario.ISprite.PixelSize [get]
Definition at line 25 of file ISprite.cs.
Referenced by MelloMario.Objects.BaseGameObject.ShowSprite().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Graphics/ ISprite.cs