MelloMario.ISoundArgs Interface Reference
Public Member Functions
void SetMethodCalled ()
Properties
bool HasArgs [get]
string MethodCalled [get]
Detailed Description
Definition at line 15 of file ISoundable.cs.
Member Function Documentation
SetMethodCalled()
void MelloMario.ISoundArgs.SetMethodCalled ()
Implemented in MelloMario.Sounds.SoundArgs .
Referenced by MelloMario.Objects.Characters.MarioCharacter.Action(), MelloMario.Objects.Blocks.Question.Bump(), MelloMario.Objects.Blocks.Brick.Bump(), MelloMario.Objects.Items.Coin.Collect(), MelloMario.Objects.Characters.MarioCharacter.FireCreate(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Characters.MarioCharacter.Jump(), MelloMario.Objects.Characters.MarioCharacter.NormalCreate(), MelloMario.Objects.Characters.Mario.OnDeath(), MelloMario.Objects.Blocks.Brick.OnDestroy(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Sounds.SoundEffectListener.Sound(), MelloMario.Objects.Items.Star.Star(), MelloMario.Objects.Characters.MarioCharacter.SuperCreate(), MelloMario.Objects.Items.SuperMushroom.SuperMushroom(), MelloMario.Objects.Characters.Mario.UpgradeToFire(), and MelloMario.Objects.Characters.Mario.UpgradeToSuper().
Property Documentation
HasArgs
bool MelloMario.ISoundArgs.HasArgs [get]
Definition at line 17 of file ISoundable.cs.
Referenced by MelloMario.Sounds.SoundEffectListener.BlockSoundEffect(), and MelloMario.Sounds.SoundEffectListener.MarioSoundEffect().
MethodCalled
string MelloMario.ISoundArgs.MethodCalled [get]
Definition at line 18 of file ISoundable.cs.
Referenced by MelloMario.Sounds.SoundEffectListener.BlockSoundEffect(), MelloMario.Sounds.SoundEffectListener.ItemSoundEffect(), and MelloMario.Sounds.SoundEffectListener.MarioSoundEffect().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/ ISoundable.cs