MelloMario.IWorld Interface Reference
Public Member Functions
void Extend (int left, int right, int top, int bottom)
IEnumerable< IGameObject > ScanNearby (Rectangle range)
Point GetRespawnPoint (Point location)
void Add (T value)
void Move (T value)
void Remove (T value)
void Update ()
Properties
string ID [get]
 WorldType Type [get]
Rectangle Boundary [get]
Detailed Description
Definition at line 18 of file IWorld.cs.
Member Function Documentation
Add()
void MelloMario.IContainer< T >.Add (T value) [inherited]
Extend()
void MelloMario.IWorld.Extend (int left, int right, int top, int bottom)
Implemented in MelloMario.Containers.World .
Referenced by MelloMario.LevelGen.StaticGenerator.Request(), and MelloMario.LevelGen.GroundGenerator.Request().
GetRespawnPoint()
Point MelloMario.IWorld.GetRespawnPoint (Point location)
Implemented in MelloMario.Containers.World .
Referenced by MelloMario.Theming.Player.Init(), and MelloMario.Theming.Player.Reset().
Move()
void MelloMario.IContainer< T >.Move (T value) [inherited]
Remove()
void MelloMario.IContainer< T >.Remove (T value) [inherited]
ScanNearby()
IEnumerable< IGameObject> MelloMario.IWorld.ScanNearby (Rectangle range)
Implemented in MelloMario.Containers.World .
Referenced by MelloMario.LevelGen.JsonGenerator.GetObjs(), and MelloMario.Theming.GameModel.UpdateGameObjects().
Update()
void MelloMario.IContainer< T >.Update () [inherited]
Property Documentation
Boundary
Rectangle MelloMario.IWorld.Boundary [get]
Definition at line 22 of file IWorld.cs.
Referenced by MelloMario.LevelGen.JsonGenerator.GetObjs(), MelloMario.LevelGen.InfiniteGenerator.InfiniteGenerator(), MelloMario.LevelGen.StaticGenerator.Request(), and MelloMario.LevelGen.GroundGenerator.Request().
ID
string MelloMario.IWorld.ID [get]
Definition at line 20 of file IWorld.cs.
Referenced by MelloMario.Theming.GameModel.LoadLevel().
Type
 WorldType MelloMario.IWorld.Type [get]
Definition at line 21 of file IWorld.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdateBGM().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Containers/ IWorld.cs