MelloMario.ISpriteFactory< T > Interface Template Reference
Public Member Functions
void BindLoader (T loader)
 ISprite CreateTextSprite (string text, float fontSize=18f)
 ISprite CreateSplashSprite ()
 ISprite CreateMarioSprite (string powerUpStatus, string movementStatus, string protectionStatus, string facing)
 ISprite CreateGoombaSprite (string status)
 ISprite CreateKoopaSprite (string color, string status)
 ISprite CreatePiranhaSprite (string color)
 ISprite CreateFireSprite ()
 ISprite CreateStarSprite ()
 ISprite CreateCoinSprite (bool isHud=false)
 ISprite CreateSuperMushroomSprite ()
 ISprite CreateFireFlowerSprite ()
 ISprite CreateOneUpMushroomSprite ()
 ISprite CreateQuestionSprite (string status)
 ISprite CreateBrickSprite (string status)
 ISprite CreateFloorSprite ()
 ISprite CreateStairSprite ()
 ISprite CreatePipelineSprite (string type)
 ISprite CreateFlagSprite (bool isTop)
 ISprite CreateSceneSprite (string type, ZIndex zIndex)
 ISprite CreateTitle (ZIndex zIndex)
 ISprite CreateThwompSprite (string name)
Detailed Description
Definition at line 3 of file ISpriteFactory.cs.
Member Function Documentation
BindLoader()
void MelloMario.ISpriteFactory< T >.BindLoader (T loader)
Referenced by MelloMario.Game1.LoadContent().
CreateBrickSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateBrickSprite (string status)
Referenced by MelloMario.Objects.Blocks.Brick.UpdateSprite().
CreateCoinSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateCoinSprite (bool isHud = false)
Referenced by MelloMario.Objects.UserInterfaces.GameOver.GameOver(), MelloMario.Objects.UserInterfaces.HUD.HUD(), and MelloMario.Objects.Items.Coin.UpdateSprite().
CreateFireFlowerSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateFireFlowerSprite ()
Referenced by MelloMario.Objects.Items.FireFlower.UpdateSprite().
CreateFireSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateFireSprite ()
Referenced by MelloMario.Objects.Items.FireBall.FireBall().
CreateFlagSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateFlagSprite (bool isTop)
Referenced by MelloMario.Objects.Blocks.Flag.UpdateSprite().
CreateFloorSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateFloorSprite ()
Referenced by MelloMario.Objects.Blocks.Floor.UpdateSprite().
CreateGoombaSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateGoombaSprite (string status)
Referenced by MelloMario.Objects.Enemies.Goomba.UpdateSprite().
CreateKoopaSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateKoopaSprite (string color, string status)
Referenced by MelloMario.Objects.Enemies.Koopa.UpdateSprite().
CreateMarioSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateMarioSprite (string powerUpStatus, string movementStatus, string protectionStatus, string facing)
Referenced by MelloMario.Objects.UserInterfaces.GameOver.GameOver(), and MelloMario.Objects.Characters.Mario.UpdateSprite().
CreateOneUpMushroomSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateOneUpMushroomSprite ()
Referenced by MelloMario.Objects.UserInterfaces.HUD.HUD(), and MelloMario.Objects.Items.OneUpMushroom.UpdateSprite().
CreatePipelineSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreatePipelineSprite (string type)
Referenced by MelloMario.Objects.Blocks.Pipeline.UpdateSprite().
CreatePiranhaSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreatePiranhaSprite (string color)
Referenced by MelloMario.Objects.Enemies.Piranha.Piranha().
CreateQuestionSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateQuestionSprite (string status)
Referenced by MelloMario.Objects.Blocks.Question.UpdateSprite(), and MelloMario.Objects.Blocks.Brick.UpdateSprite().
CreateSceneSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateSceneSprite (string type, ZIndex zIndex)
Referenced by MelloMario.Objects.Miscs.Background.UpdateSprite().
CreateSplashSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateSplashSprite ()
Referenced by MelloMario.Objects.UserInterfaces.GameOver.GameOver(), and MelloMario.Objects.UserInterfaces.GameWon.GameWon().
CreateStairSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateStairSprite ()
Referenced by MelloMario.Objects.Blocks.Stair.UpdateSprite().
CreateStarSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateStarSprite ()
Referenced by MelloMario.Objects.Items.Star.UpdateSprite().
CreateSuperMushroomSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateSuperMushroomSprite ()
Referenced by MelloMario.Objects.Items.SuperMushroom.UpdateSprite().
CreateTextSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateTextSprite (string text, float fontSize = 18f)
Referenced by MelloMario.Objects.UserInterfaces.GameOver.GameOver(), MelloMario.Objects.UserInterfaces.GameStart.GameStart(), MelloMario.Objects.UserInterfaces.GameWon.GameWon(), MelloMario.Objects.UserInterfaces.HUD.HUD(), MelloMario.Objects.UserInterfaces.GameOver.OnDraw(), MelloMario.Objects.UserInterfaces.HUD.OnUpdate(), and MelloMario.Objects.UserInterfaces.PopingUpPoints.PopingUpPoints().
CreateThwompSprite()
 ISprite MelloMario.ISpriteFactory< T >.CreateThwompSprite (string name)
Referenced by MelloMario.Objects.Enemies.Thwomp.UpdateSprite().
CreateTitle()
 ISprite MelloMario.ISpriteFactory< T >.CreateTitle (ZIndex zIndex)
Referenced by MelloMario.Objects.UserInterfaces.GameStart.GameStart().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Factories/ ISpriteFactory.cs