MelloMario.IPlayer Interface Reference
Public Member Functions
void AddCoin ()
void AddLife ()
void AddScore (int delta)
void Init (string type, IWorld newWorld, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
void Spawn (IWorld newWorld, Point newLocation)
void Reset (string type, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
void Win ()
void Update (int time)
Properties
 ICharacter Character [get]
 ICamera Camera [get]
int Coins [get]
int Score [get]
int Lifes [get]
int TimeRemain [get]
Detailed Description
Definition at line 9 of file IPlayer.cs.
Member Function Documentation
AddCoin()
void MelloMario.IPlayer.AddCoin ()
Implemented in MelloMario.Theming.Player .
AddLife()
void MelloMario.IPlayer.AddLife ()
Implemented in MelloMario.Theming.Player .
AddScore()
void MelloMario.IPlayer.AddScore (int delta)
Implemented in MelloMario.Theming.Player .
Init()
void MelloMario.IPlayer.Init (string type, IWorld newWorld, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Implemented in MelloMario.Theming.Player .
Referenced by MelloMario.Theming.GameModel.Infinite(), and MelloMario.Theming.GameModel.Normal().
Reset()
void MelloMario.IPlayer.Reset (string type, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Implemented in MelloMario.Theming.Player .
Referenced by MelloMario.Theming.GameModel.Transist().
Spawn()
void MelloMario.IPlayer.Spawn (IWorld newWorld, Point newLocation)
Implemented in MelloMario.Theming.Player .
Referenced by MelloMario.Objects.Blocks.Pipeline.OnUpdate().
Update()
void MelloMario.IPlayer.Update (int time)
Implemented in MelloMario.Theming.Player .
Referenced by MelloMario.Theming.GameModel.UpdateGameObjects().
Win()
void MelloMario.IPlayer.Win ()
Implemented in MelloMario.Theming.Player .
Referenced by MelloMario.Theming.GameModel.TransistGameWon().
Property Documentation
Camera
 ICamera MelloMario.IPlayer.Camera [get]
Definition at line 12 of file IPlayer.cs.
Referenced by MelloMario.Objects.BaseUIObject.BaseUIObject(), MelloMario.Objects.BaseUIObject.Offset(), and MelloMario.Objects.BaseUIObject.UpdateOrigin().
Character
 ICharacter MelloMario.IPlayer.Character [get]
Definition at line 11 of file IPlayer.cs.
Referenced by MelloMario.Containers.Session.GetKey(), MelloMario.Theming.GameModel.Init(), MelloMario.Theming.GameModel.Pause(), MelloMario.Theming.GameModel.Resume(), MelloMario.Theming.GameModel.Transist(), MelloMario.Theming.GameModel.TransistGameWon(), MelloMario.Theming.Database.Update(), and MelloMario.Theming.GameModel.UpdateGameObjects().
Coins
int MelloMario.IPlayer.Coins [get]
Definition at line 14 of file IPlayer.cs.
Lifes
int MelloMario.IPlayer.Lifes [get]
Definition at line 16 of file IPlayer.cs.
Score
int MelloMario.IPlayer.Score [get]
Definition at line 15 of file IPlayer.cs.
TimeRemain
int MelloMario.IPlayer.TimeRemain [get]
Definition at line 17 of file IPlayer.cs.
Referenced by MelloMario.Sounds.BGMManager.UpdateBGM().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/ IPlayer.cs