MelloMario.IBlockState Interface Reference
Public Member Functions
void Show ()
void Hide ()
void Bump (Mario mario)
void Update (int time)
Detailed Description
Definition at line 9 of file IBlockState.cs.
Member Function Documentation
Bump()
void MelloMario.IBlockState.Bump (Mario mario)
Implemented in MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Destroyed , MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Blocks.QuestionStates.Normal , and MelloMario.Objects.Blocks.QuestionStates.Used .
Referenced by MelloMario.Objects.Blocks.Question.Bump(), and MelloMario.Objects.Blocks.Brick.Bump().
Hide()
void MelloMario.IBlockState.Hide ()
Implemented in MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Destroyed , MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Blocks.QuestionStates.Normal , and MelloMario.Objects.Blocks.QuestionStates.Used .
Show()
void MelloMario.IBlockState.Show ()
Implemented in MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Destroyed , MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Blocks.QuestionStates.Normal , and MelloMario.Objects.Blocks.QuestionStates.Used .
Update()
void MelloMario.IState.Update (int time) [inherited]
Implemented in MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Characters.PowerUpStates.Standard , MelloMario.Objects.Characters.MovementStates.Standing , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , MelloMario.Objects.Characters.PowerUpStates.Fire , MelloMario.Objects.Characters.PowerUpStates.Super , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Enemies.KoopaStates.Defeated , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Normal , MelloMario.Objects.Blocks.QuestionStates.Used , MelloMario.Objects.Enemies.KoopaStates.MovingShell , MelloMario.Objects.BaseTimedState< T > , MelloMario.Objects.Enemies.KoopaStates.Normal , MelloMario.Objects.Items.CoinStates.Unveil , MelloMario.Objects.Items.FireFlowerStates.Unveil , MelloMario.Objects.Items.OneUpMushroomStates.Unveil , MelloMario.Objects.Items.StarStates.Unveil , MelloMario.Objects.Items.SuperMushroomStates.Unveil , MelloMario.Objects.Enemies.GoombaStates.Defeated , MelloMario.Objects.Characters.ProtectionStates.Normal , MelloMario.Objects.Enemies.GoombaStates.Normal , MelloMario.Objects.Enemies.ThwompStates.Defeated , MelloMario.Objects.Enemies.ThwompStates.Normal , MelloMario.Objects.Items.CoinStates.Normal , MelloMario.Objects.Items.FireFlowerStates.Normal , MelloMario.Objects.Items.OneUpMushroomStates.Normal , MelloMario.Objects.Items.StarStates.Normal , MelloMario.Objects.Items.SuperMushroomStates.Normal , MelloMario.Objects.Enemies.PiranhaStates.Defeated , MelloMario.Objects.Enemies.PiranhaStates.MovingDown , MelloMario.Objects.Enemies.PiranhaStates.MovingUp , and MelloMario.Objects.BaseState< T > .
Referenced by MelloMario.Objects.Enemies.Thwomp.OnUpdate(), MelloMario.Objects.Enemies.Goomba.OnUpdate(), MelloMario.Objects.Items.OneUpMushroom.OnUpdate(), MelloMario.Objects.Enemies.Piranha.OnUpdate(), MelloMario.Objects.Items.Star.OnUpdate(), MelloMario.Objects.Items.FireFlower.OnUpdate(), MelloMario.Objects.Enemies.Koopa.OnUpdate(), MelloMario.Objects.Items.Coin.OnUpdate(), MelloMario.Objects.Blocks.Question.OnUpdate(), MelloMario.Objects.Items.SuperMushroom.OnUpdate(), MelloMario.Objects.Blocks.Brick.OnUpdate(), and MelloMario.Objects.Characters.Mario.OnUpdate().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Objects/States/ IBlockState.cs