MelloMario.IController Interface Reference
Public Member Functions
void AddCommand (object key, ICommand value, KeyBehavior behavior= KeyBehavior.press)
void Update ()
void Reset ()
Detailed Description
Definition at line 10 of file IController.cs.
Member Function Documentation
AddCommand()
void MelloMario.IController.AddCommand (object key, ICommand value, KeyBehavior behavior = KeyBehavior.press)
Implemented in MelloMario.Controls.Controllers.BaseController< T > .
Referenced by MelloMario.Controls.Scripts.PausedScript.Bind(), MelloMario.Controls.Scripts.TransistScript.Bind(), MelloMario.Controls.Scripts.StartScript.Bind(), and MelloMario.Controls.Scripts.PlayingScript.Bind().
Reset()
void MelloMario.IController.Reset ()
Implemented in MelloMario.Controls.Controllers.BaseController< T > .
Referenced by MelloMario.Controls.Scripts.PausedScript.Bind(), MelloMario.Controls.Scripts.TransistScript.Bind(), MelloMario.Controls.Scripts.StartScript.Bind(), and MelloMario.Controls.Scripts.PlayingScript.Bind().
Update()
void MelloMario.IController.Update ()
Implemented in MelloMario.Controls.Controllers.BaseController< T > .
Referenced by MelloMario.Theming.GameModel.UpdateController().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Controls/ IController.cs