MelloMario.IMarioMovementState Interface Reference
Public Member Functions
void Crouch ()
void Idle ()
void Land ()
void Jump ()
void Walk ()
void Update (int time)
Detailed Description
Definition at line 3 of file IMarioMovementState.cs.
Member Function Documentation
Crouch()
void MelloMario.IMarioMovementState.Crouch ()
Implemented in MelloMario.Objects.Characters.MovementStates.Jumping , MelloMario.Objects.Characters.MovementStates.Crouching , MelloMario.Objects.Characters.MovementStates.Standing , and MelloMario.Objects.Characters.MovementStates.Walking .
Referenced by MelloMario.Objects.Characters.MarioCharacter.Crouch().
Idle()
void MelloMario.IMarioMovementState.Idle ()
Implemented in MelloMario.Objects.Characters.MovementStates.Jumping , MelloMario.Objects.Characters.MovementStates.Standing , MelloMario.Objects.Characters.MovementStates.Walking , and MelloMario.Objects.Characters.MovementStates.Crouching .
Referenced by MelloMario.Objects.Characters.MarioCharacter.CrouchRelease(), MelloMario.Objects.Characters.MarioCharacter.LeftRelease(), and MelloMario.Objects.Characters.MarioCharacter.RightRelease().
Jump()
void MelloMario.IMarioMovementState.Jump ()
Implemented in MelloMario.Objects.Characters.MovementStates.Jumping , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , and MelloMario.Objects.Characters.MovementStates.Standing .
Referenced by MelloMario.Objects.Characters.MarioCharacter.Jump().
Land()
void MelloMario.IMarioMovementState.Land ()
Implemented in MelloMario.Objects.Characters.MovementStates.Jumping , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , and MelloMario.Objects.Characters.MovementStates.Standing .
Referenced by MelloMario.Objects.Characters.Mario.OnCollision().
Update()
void MelloMario.IState.Update (int time) [inherited]
Implemented in MelloMario.Objects.Blocks.BrickStates.Hidden , MelloMario.Objects.Blocks.BrickStates.Bumped , MelloMario.Objects.Blocks.QuestionStates.Bumped , MelloMario.Objects.Blocks.BrickStates.Normal , MelloMario.Objects.Characters.PowerUpStates.Standard , MelloMario.Objects.Characters.MovementStates.Standing , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Crouching , MelloMario.Objects.Characters.PowerUpStates.Fire , MelloMario.Objects.Characters.PowerUpStates.Super , MelloMario.Objects.Blocks.QuestionStates.Hidden , MelloMario.Objects.Enemies.KoopaStates.Defeated , MelloMario.Objects.Blocks.BrickStates.Used , MelloMario.Objects.Blocks.QuestionStates.Normal , MelloMario.Objects.Blocks.QuestionStates.Used , MelloMario.Objects.Enemies.KoopaStates.MovingShell , MelloMario.Objects.BaseTimedState< T > , MelloMario.Objects.Enemies.KoopaStates.Normal , MelloMario.Objects.Items.CoinStates.Unveil , MelloMario.Objects.Items.FireFlowerStates.Unveil , MelloMario.Objects.Items.OneUpMushroomStates.Unveil , MelloMario.Objects.Items.StarStates.Unveil , MelloMario.Objects.Items.SuperMushroomStates.Unveil , MelloMario.Objects.Enemies.GoombaStates.Defeated , MelloMario.Objects.Characters.ProtectionStates.Normal , MelloMario.Objects.Enemies.GoombaStates.Normal , MelloMario.Objects.Enemies.ThwompStates.Defeated , MelloMario.Objects.Enemies.ThwompStates.Normal , MelloMario.Objects.Items.CoinStates.Normal , MelloMario.Objects.Items.FireFlowerStates.Normal , MelloMario.Objects.Items.OneUpMushroomStates.Normal , MelloMario.Objects.Items.StarStates.Normal , MelloMario.Objects.Items.SuperMushroomStates.Normal , MelloMario.Objects.Enemies.PiranhaStates.Defeated , MelloMario.Objects.Enemies.PiranhaStates.MovingDown , MelloMario.Objects.Enemies.PiranhaStates.MovingUp , and MelloMario.Objects.BaseState< T > .
Referenced by MelloMario.Objects.Enemies.Thwomp.OnUpdate(), MelloMario.Objects.Enemies.Goomba.OnUpdate(), MelloMario.Objects.Items.OneUpMushroom.OnUpdate(), MelloMario.Objects.Enemies.Piranha.OnUpdate(), MelloMario.Objects.Items.Star.OnUpdate(), MelloMario.Objects.Items.FireFlower.OnUpdate(), MelloMario.Objects.Enemies.Koopa.OnUpdate(), MelloMario.Objects.Items.Coin.OnUpdate(), MelloMario.Objects.Blocks.Question.OnUpdate(), MelloMario.Objects.Items.SuperMushroom.OnUpdate(), MelloMario.Objects.Blocks.Brick.OnUpdate(), and MelloMario.Objects.Characters.Mario.OnUpdate().
Walk()
void MelloMario.IMarioMovementState.Walk ()
Implemented in MelloMario.Objects.Characters.MovementStates.Jumping , MelloMario.Objects.Characters.MovementStates.Walking , MelloMario.Objects.Characters.MovementStates.Standing , and MelloMario.Objects.Characters.MovementStates.Crouching .
Referenced by MelloMario.Objects.Characters.MarioCharacter.Left(), and MelloMario.Objects.Characters.MarioCharacter.Right().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Objects/States/ IMarioMovementState.cs