MelloMario.IContainer< T > Interface Template Reference
Public Member Functions
void Add (T value)
void Move (T value)
void Remove (T value)
void Update ()
Detailed Description
Definition at line 3 of file IContainer.cs.
Member Function Documentation
Add()
void MelloMario.IContainer< T >.Add (T value)
Referenced by MelloMario.Objects.BaseGameObject.BaseGameObject(), and MelloMario.LevelGen.StaticGenerator.Request().
Move()
void MelloMario.IContainer< T >.Move (T value)
Referenced by MelloMario.Objects.BaseGameObject.Resize().
Remove()
void MelloMario.IContainer< T >.Remove (T value)
Update()
void MelloMario.IContainer< T >.Update ()
Referenced by MelloMario.Theming.GameModel.UpdateContainers().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Containers/ IContainer.cs