MelloMario.IListener< in in T > Interface Template Reference
Public Member Functions
void Subscribe (T objectListened)
Detailed Description
Definition at line 3 of file IListener.cs.
Member Function Documentation
Subscribe()
void MelloMario.IListener< in in T >.Subscribe (T objectListened)
Referenced by MelloMario.Objects.BaseCollidableObject.BaseCollidableObject(), MelloMario.Objects.Blocks.Brick.Brick(), MelloMario.Objects.Items.Coin.Coin(), MelloMario.Objects.Items.FireFlower.FireFlower(), MelloMario.Objects.Blocks.Flag.Flag(), MelloMario.Objects.Characters.Mario.Mario(), MelloMario.Objects.Items.OneUpMushroom.OneUpMushroom(), MelloMario.Objects.Blocks.Pipeline.Pipeline(), MelloMario.Objects.Blocks.Question.Question(), MelloMario.Objects.Items.Star.Star(), and MelloMario.Objects.Items.SuperMushroom.SuperMushroom().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/ IListener.cs