MelloMario.IGameObjectFactory Interface Reference
Public Member Functions
 ICharacter CreateCharacter (string type, IWorld world, IPlayer player, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
 ICamera CreateCamera ()
 IGameObject CreateGameObject (string type, IWorld world, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
IEnumerable< IGameObject > CreateGameObjectGroup (string type, IWorld world, Point location, int count, IListener< IGameObject > listener)
Detailed Description
Definition at line 10 of file IGameObjectFactory.cs.
Member Function Documentation
CreateCamera()
 ICamera MelloMario.IGameObjectFactory.CreateCamera ()
Implemented in MelloMario.Factories.GameObjectFactory .
Referenced by MelloMario.Theming.Player.Init().
CreateCharacter()
 ICharacter MelloMario.IGameObjectFactory.CreateCharacter (string type, IWorld world, IPlayer player, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Implemented in MelloMario.Factories.GameObjectFactory .
Referenced by MelloMario.Theming.Player.Init(), and MelloMario.Theming.Player.Reset().
CreateGameObject()
 IGameObject MelloMario.IGameObjectFactory.CreateGameObject (string type, IWorld world, Point location, IListener< IGameObject > listener, IListener< ISoundable > soundListener)
Implemented in MelloMario.Factories.GameObjectFactory .
Referenced by MelloMario.LevelGen.JsonConverters.Util.CreateItemList(), and MelloMario.Objects.Items.SuperMushroom.GetFireFlower().
CreateGameObjectGroup()
IEnumerable< IGameObject> MelloMario.IGameObjectFactory.CreateGameObjectGroup (string type, IWorld world, Point location, int count, IListener< IGameObject > listener)
Implemented in MelloMario.Factories.GameObjectFactory .
Referenced by MelloMario.LevelGen.JsonConverters.GameEntityConverter.CreateFlag().
The documentation for this interface was generated from the following file:
MelloMario/MelloMario/Interfaces/Factories/ IGameObjectFactory.cs